alphagov/govuk-content-schemas

- formats/finder/frontend/examples/finder.json
- formats/finder/frontend/schema.json
- formats/finder/publisher/details.json
- formats/finder/publisher/links.json
- formats/finder/publisher/schema.json
This commit adds the content schema for the Finder format.
> Add finder content schema

- formats/redirect/publisher/schema.json
This was missed from 390374a0891fb6dc21390d46ca6fa63d07a9065e
> Deprecate base_path from redirect items

- README.md
- docs/contract-testing-howto.md
this is a draft of documentation about contract testing for feedback
/cc @tommyp @danielroseman
> [DRAFT] Document contract testing

- README.md
- Rakefile
- docs/adding-a-new-format.md
- templates/details.json
- templates/links.json
Helps get the ball rolling by creating the necessary folders and files for a new content format schema.
> Add rake task for generating a new format

- README.md
> Correct redundant language in README

- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/frontend/schema.json
- formats/policy/publisher/links.json
- formats/policy/publisher/schema.json
Adds "people" to the list of valid links on a policy
> Update policy schema to include people

- README.md
- docs/contract-testing-howto.md
- docs/why-contract-testing.md
Having done this a few times, I've been able to simplify the instructions a bit.
> Simplify how to for adding contract tests to your app

- formats/policy/frontend/examples/minimal_policy_area.json
One which doesn't include so many links.
> Add minimal policy area example

- formats/case_study/frontend/examples/archived.json
- formats/case_study/frontend/examples/case_study.json
- formats/case_study/frontend/examples/translated.json
- formats/case_study/frontend/schema.json
- formats/case_study/publisher/details.json
- formats/case_study/publisher/schema.json
Required for this change: https://github.com/alphagov/whitehall/pull/2117
> Add policy tagging to case studies.

- formats/finder/frontend/examples/esi-funds.json
Related to https://github.com/alphagov/specialist-publisher/pull/474 and https://github.com/alphagov/govuk-content-schemas/pull/49
> Add the ESI Fund logo to the example

- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/publisher/schema.json
- formats/manual_section/frontend/examples/what-is-content-design.json
- formats/manual_section/publisher/details.json
A separate schema will be required for HMRC manual sections.
> Add schema for manual_sections

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/finder/publisher/details.json
- formats/policy/publisher/details.json
Reverts alphagov/govuk-content-schemas#63
> Revert "Add 'result_metadata_name_key' to finder schemas"

- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/policy/frontend/examples/minimal_policy_area.json
- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/frontend/examples/policy_with_inapplicable_nations.json
- formats/policy/publisher/links.json
Required for https://trello.com/c/pV7ExOoE/203-5-associate-policy-to-a-group
> Add working groups to policy

- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- formats/topic/frontend/examples/curated_subtopic.json
- formats/topic/frontend/examples/uncurated_subtopic.json
- formats/topic/publisher/links.json
So that subtopics can include information about their parent topic.
> Add parent link to topics.

- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- formats/topic/frontend/examples/topic-in-beta.json
- formats/topic/frontend/examples/topic.json
- formats/topic/publisher/links.json
This will allow us to render topic pages entirely from the
content-store.
> Add children links to topic.

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- formats/mainstream_browse_page/frontend/examples/top_level_page.json
- formats/mainstream_browse_page/frontend/examples/top_level_page_with_child_pages_in_curated_order.json
- formats/mainstream_browse_page/publisher/details.json
See discussion on https://github.com/alphagov/govuk-content-schemas/pull/92 for details.
> Rename 2nd_level_ordering field on mainstream_browse_pages

- README.md
- bin/convert_finder_schemas
- docs/converting-finder-schemas.md
Add some clear documentation about this (rather than leaving it in the [pull request](https://github.com/alphagov/govuk-content-schemas/pull/95))
> Add documentation about converting finder schemas

- dist/formats/redirect/publisher/schema.json
- formats/redirect/publisher/examples/redirect.json
- formats/redirect/publisher/schema.json
All items in the content store should have a content id.
> Allow redirects to have content_id

- dist/formats/specialist_document/publisher/schema.json
- formats/specialist_document/publisher/details.json
Fixes error in validation of tax-tribunal-decisions example.
> Add bulk_published to tax-tribunal-decisions schema

- dist/formats/redirect/publisher/schema.json
- dist/formats/unpublishing/frontend/schema.json
- dist/formats/unpublishing/publisher/schema.json
- formats/redirect/publisher/examples/redirect-with-replacement.json
- formats/redirect/publisher/schema.json
- formats/unpublishing/frontend/examples/unpublishing.json
- formats/unpublishing/publisher/links.json
Also renames the same field in redirects.
> Add can_be_replaced_by to unpublishings

- dist/formats/gone/publisher/schema.json
- dist/formats/redirect/publisher/schema.json
- formats/gone/publisher/schema.json
- formats/redirect/publisher/schema.json
Part of https://trello.com/c/pULByuHs/393-fix-invalid-content-store-data
Related to https://github.com/alphagov/whitehall/pull/2373
> Add `can_be_replaced_by` to gone items.

- dist/formats/redirect/publisher/schema.json
- formats/redirect/publisher/schema.json
Part of https://trello.com/c/pULByuHs/393-fix-invalid-content-store-data
> Make content ID required for redirects.

- dist/formats/travel_advice/frontend/schema.json
- dist/formats/travel_advice/publisher/schema.json
- dist/formats/travel_advice_index/frontend/schema.json
- dist/formats/travel_advice_index/publisher/schema.json
- formats/travel_advice/frontend/examples/full-country.json
- formats/travel_advice/frontend/examples/no-parts.json
- formats/travel_advice/publisher/details.json
- formats/travel_advice/publisher/links.json
- formats/travel_advice_index/frontend/examples/index.json
- formats/travel_advice_index/publisher/details.json
- formats/travel_advice_index/publisher/links.json
I believe this contains everything necessary to render these pages. I'd appreciate feedback on whether there's anything I've missed, or whether any of this should be modelled differently.
> Add schemas for travel-advice (index and country pages)

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/publisher/schema.json
- dist/formats/taxon/publisher_v2/links.json
- dist/formats/taxon/publisher_v2/schema.json
- formats/taxon/frontend/examples/taxon.json
- formats/taxon/publisher/details.json
- formats/taxon/publisher/links.json
We are introducing taxon content items to start building a new taxonomy
for GOVUK. This will help us to start tagging content items to specific
parts of the taxonomy.
> Add new taxon schema

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/publisher/details.json
https://trello.com/c/4euyRTaI/229-add-additional-report-type-to-aaib-reports-finder-large
> Add new Safety Study AAIB report type

- dist/formats/travel_advice_index/frontend/schema.json
- dist/formats/travel_advice_index/publisher/schema.json
- dist/formats/travel_advice_index/publisher_v2/schema.json
- formats/travel_advice_index/frontend/examples/index.json
- formats/travel_advice_index/publisher/details.json
- formats/travel_advice_index/publisher_v2/examples/travel_advice_index.json
Depends on https://github.com/alphagov/travel-advice-publisher/pull/96 being merged.
> Add updated_at to travel_advice_index countries

- dist/formats/statistics_announcement/frontend/schema.json
- dist/formats/statistics_announcement/publisher/schema.json
- dist/formats/statistics_announcement/publisher_v2/links.json
- dist/formats/statistics_announcement/publisher_v2/schema.json
- formats/statistics_announcement/frontend/examples/cancelled_official_statistics.json
- formats/statistics_announcement/frontend/examples/national_statistics.json
- formats/statistics_announcement/frontend/examples/official_statistics.json
- formats/statistics_announcement/frontend/examples/release_date_changed.json
- formats/statistics_announcement/publisher/details.json
- formats/statistics_announcement/publisher/links.json
Adds the schemata and front end examples for Statistics Announcements.
Trello: https://trello.com/c/grRZvVD9
> Statistics announcement schema and examples

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/frontend/examples/european-structural-investment-funds.json
- formats/specialist_document/publisher/details.json
Altered the schema to ensure the document_type matches that of publishing-api for european-structural-investment-funds.
> Change document_type to esi_fund

- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/publisher/schema.json
- dist/formats/html_publication/publisher_v2/links.json
- dist/formats/html_publication/publisher_v2/schema.json
- formats/html_publication/frontend/examples/published.json
- formats/html_publication/frontend/examples/updated.json
- formats/html_publication/publisher/details.json
- formats/html_publication/publisher/links.json
Trello: https://trello.com/c/Wcl1hWJ2
Adds both the schema and related examples to highlight a first published and an updated HTML publication.
> HTML publications schema and examples

- formats/html_publication/frontend/examples/arabic_translation.json
- formats/html_publication/frontend/examples/fractions_and_unnumbered_headings.json
- formats/html_publication/frontend/examples/long_form_and_automatically_numbered_headings.json
- formats/html_publication/frontend/examples/multiple_organisations.json
- formats/html_publication/frontend/examples/prime_ministers_office.json
- formats/html_publication/frontend/examples/published.json
- formats/html_publication/frontend/examples/stats_headline_and_manually_numbered_headings.json
- formats/html_publication/frontend/examples/updated.json
Trello: https://trello.com/c/Wcl1hWJ2
Adds a branding identifier, a formatted title to respect the
organisation's formatting wishes and a crest identifier.
> Add logo related branding

- dist/formats/coming_soon/frontend/schema.json
- dist/formats/coming_soon/publisher/schema.json
- dist/formats/coming_soon/publisher_v2/schema.json
- dist/formats/gone/publisher_v2/schema.json
- dist/formats/redirect/publisher_v2/schema.json
- dist/formats/unpublishing/frontend/schema.json
- dist/formats/unpublishing/publisher/schema.json
- dist/formats/unpublishing/publisher_v2/schema.json
- formats/coming_soon/publisher/details.json
- formats/gone/publisher_v2/schema.json
- formats/redirect/publisher_v2/examples/redirect-with-replacement.json
- formats/redirect/publisher_v2/examples/redirect.json
- formats/redirect/publisher_v2/schema.json
- formats/unpublishing/publisher/details.json
Adds to:
- redirect
- gone
- unpublishing
- coming_soon
This allows us to publish content, when that content has not been
published before, but has an "update_type" of "major".
>     Add public_updated_at as an optional property

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- formats/placeholder/frontend/examples/organisation.json
- formats/placeholder/publisher/details.json
Modify the placeholder schema to accommodate the branding / logo information on the organisation model. Also adds an example.
https://trello.com/c/cJGrtnc1
> Change placeholder schema for organisations

- startup.sh
It looks like most of our other apps have this, and I was expecting it to be there. So I just quickly added it.
> Add ./startup.sh script.

- deploy.sh
- docs/adding-a-new-format.md
- docs/changing-a-format.md
Documents https://github.com/alphagov/govuk-puppet/pull/4249
https://trello.com/c/6fnMMZaX/642-1-make-govuk-content-schemas-visible-to-the-publishing-api-in-prod
> Add script and docs for deploying schema changes.

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- formats/detailed_guide/frontend/examples/political_detailed_guide.json
- formats/detailed_guide/frontend/examples/related_mainstream_detailed_guide.json
- formats/detailed_guide/frontend/examples/withdrawn_detailed_guide.json
- formats/detailed_guide/publisher/links.json
* Add related guide to examples, to build frontend against
* Add document collections to detailed guide schema, and include examples
* Add examples of related mainstream content, document collections and related guides
Examples used:
https://www.gov.uk/guidance/onshore-wind-part-of-the-uks-energy-mix
https://www.gov.uk/guidance/living-in-fiji
https://www.gov.uk/guidance/living-in-fiji--2
Part of:
https://trello.com/c/k6H9gNKF/316-6-detailed-guides-migration-front-end-work-small
cc @mgrassotti @tvararu
> Add document collections to detailed guides, add examples of more features

- formats/html_publication/frontend/examples/arabic_translation.json
- formats/html_publication/frontend/examples/fractions_and_unnumbered_headings.json
- formats/html_publication/frontend/examples/long_form_and_automatically_numbered_headings.json
- formats/html_publication/frontend/examples/multiple_organisations.json
- formats/html_publication/frontend/examples/prime_ministers_office.json
- formats/html_publication/frontend/examples/published.json
- formats/html_publication/frontend/examples/stats_headline_and_manually_numbered_headings.json
- formats/html_publication/frontend/examples/updated.json
- Add schema_name and document_type to parent link
- Move brand and logo data into organisation’s details hash
> Update HTML Publications examples

- formats/document_collection/frontend/examples/document_collection.json
- formats/document_collection/frontend/examples/document_collection_with_body.json
As part of https://trello.com/c/ZWU9N8Bc/414-add-missing-details-to-document-list-for-document-collection-format-medium
> Add public_updated_at metadata to examples

- README.md
Small updates in the README to explanation of how metadata is used when combining schemas
> Update a couple of inaccuracies in the README

- dist/formats/service_manual_topic/frontend/schema.json
- dist/formats/service_manual_topic/publisher/schema.json
- dist/formats/service_manual_topic/publisher_v2/schema.json
- formats/service_manual_topic/frontend/examples/service_manual_topic.json
- formats/service_manual_topic/frontend/examples/service_manual_topic_collapsed.json
- formats/service_manual_topic/publisher/details.json
- formats/service_manual_topic/publisher_v2/examples/service_manual_topic.json
> Remove service manual topic group contents

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher_v2/examples/dfid_research_output.json
Can be `unreviewed` or `peer_reviewed`
> Add dfid_review_status to research outputs

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher_v2/examples/dfid_research_output.json
... to the dfid_research_output properties. Also update the example.
> Add DFID's twelve top-level themes

- dist/message_queue.json
- formats/message_queue_base.json
- lib/govuk_content_schemas/message_queue_schema_generator.rb
- lib/tasks/combine_schemas.rake
- spec/lib/message_queue_schema_generator_spec.rb
See individual commits for details.
> Update message queue schemas

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- dist/message_queue.json
- formats/specialist_document/publisher/details.json
* No longer in use as of last week
> Remove DFID 'Questionnaire' document type

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- formats/detailed_guide/publisher/links.json
This is required as part of migrating detailed guides.
[Trello](https://trello.com/c/CkHu0suq/317-6-detailed-guides-migration-final-tasks-deploy-1-medium)
> Add policy areas & related policies to detailed guides

- dist/formats/fatality_notice/frontend/schema.json
- dist/formats/fatality_notice/publisher/schema.json
- dist/formats/fatality_notice/publisher_v2/links.json
- dist/formats/fatality_notice/publisher_v2/schema.json
- dist/message_queue.json
- formats/fatality_notice/frontend/examples/fatality_notice.json
- formats/fatality_notice/frontend/examples/fatality_notice_with_minister.json
- formats/fatality_notice/frontend/examples/withdrawn_fatality_notice.json
- formats/fatality_notice/publisher/details.json
- formats/fatality_notice/publisher/links.json
Add schema and examples for fatality notice
Mobbed on by @gpeng @boffbowsh @binaryberry @bevanloon @andrewgarner @nickcolley @mgrassotti 💯  😸 
[Related Trello card](https://trello.com/c/pNrZoQex/310-8-fatality-notice-migration-mvp-content-schema-examples-and-front-end-work-medium)
> Add fatality notice format

- formats/fatality_notice/frontend/examples/fatality_notice.json
- formats/fatality_notice/frontend/examples/fatality_notice_with_minister.json
Mobbed by @gpeng @andrewgarner 
Trello https://trello.com/c/pNrZoQex/310-8-fatality-notice-migration-mvp-content-schema-examples-and-front-end-work-medium
> Fix public_updated_at for example Fatality Notice

- formats/document_collection/frontend/examples/document_collection_political.json
- formats/document_collection/frontend/examples/document_collection_with_history.json
- formats/document_collection/frontend/examples/document_collection_withdrawn.json
Add individual feature examples for document collection.
A subsequent PR will remove these features from the base example once government-frontend has been updated.
Mobbed with @andrewgarner @gpeng @MatMoore @tvararu 
[Trello](https://trello.com/c/DoIbAkZB/)
> Add further document collection examples

- formats/document_collection/frontend/examples/document_collection.json
- formats/document_collection/frontend/examples/document_collection_with_body.json
- formats/document_collection/frontend/examples/document_collection_with_history.json
Mobbed with @andrewgarner @gpeng @MatMoore 
[Trello](https://trello.com/c/DoIbAkZB/428-11-document-collection-migration-implement-publishing-of-format-to-publishing-api)
> Simplify basic document collection examples

- dist/formats/publication/frontend/schema.json
- dist/formats/publication/publisher/schema.json
- dist/formats/publication/publisher_v2/links.json
- formats/publication/frontend/examples/political_publication.json
- formats/publication/publisher/links.json
This brings the Publication format into line with other Editioned format that have related_policies.
> Add related_policies links for publications

- deploy.sh
- docs/deployment.md
govuk-content-schemas is now deployed as a standard app.
> Deployment changes

- formats/travel_advice_index/frontend/examples/index.json
The list of countries on the frontend has a bug in which countries with
characters such as a-tilde are not sorted correctly. This commit adds
one such country to the example index json so this ordering can be tested on
frontend.
> Add country to test utf-8 sort on frontend

- Gemfile
- Gemfile.lock
> Add pry-byebug gem

- formats/statistical_data_set/publisher/details.json
Fixing indentation in `details.json` for Statistical Data Sets, based on this [comment](https://github.com/alphagov/govuk-content-schemas/pull/447#pullrequestreview-10723190)
cc (once more).... @fofr
> Fix indentation

- formats/document_collection/frontend/examples/document_collection_with_withdrawn_links_documents.json
This is useful for testing
https://trello.com/c/IFfWVlb6/533-filter-out-withdrawn-documents-in-document-collections-medium
> Add Document Collection withdrawn example

- dist/formats/redirect/publisher_v2/schema.json
- formats/redirect/publisher_v2/schema.json
Publishing API no longer supports format field.
> Remove optional format fields from redirect schema

- Jenkinsfile
This is a spike to work out how best to trigger builds of projects which depend on the schemas.
In this approach, we call the downstream builds directly from the govuk-content-schemas Jenkinsfile. We'll have to test whether this approach updates pull request checks correctly.
It's separate from PR #458, because we might be able to merge that one as soon as this project is being built by Jenkins 2.
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration
> Configure downstream builds in Jenkins 2

- Jenkinsfile
Trigger the builds of several projects, to test the production version of those against the latest changes to the content schema.
Ensure the builds happen in parallel to reduce the elapsed time for checking the latest content schemas.
This is not the full list of dependent projects - this is just the subset which have been recently configured in puppet to handle builds of 'deployed-to-production' correctly in alphagov/govuk-puppet#5335. Other downstream builds will be migrated from Jenkins 1 once they have also been updated in Puppet.
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration
> Configure more dependent builds in Jenkins 2

- Jenkinsfile
This removes the Jenkins 2 build's dependency on the old jenkins.sh.
The jenkins.sh file cannot be deleted yet because it is still used in the Jenkins 1 build before the schema tests are triggered. It will be safe to delete once all the downstream schema test builds have been migrated to Jenkins 2.
Jenkins: https://trello.com/c/S4DZbsPa/285-jenkins-2-migration
> Migrate all CI build steps into Jenkinsfile

- dist/formats/need/frontend/schema.json
- dist/formats/need/notification/schema.json
- dist/formats/need/publisher/schema.json
- dist/formats/need/publisher_v2/schema.json
- formats/need/publisher/details.json
This information is stored in the Publishing API state.
> Remove the status field

- dist/formats/answer/frontend/schema.json
- dist/formats/answer/notification/schema.json
- dist/formats/answer/publisher/schema.json
- dist/formats/answer/publisher_v2/links.json
- dist/formats/answer/publisher_v2/schema.json
- formats/answer/frontend/examples/answer.json
- formats/answer/publisher/details.json
- formats/answer/publisher_v2/examples/answer.json
https://trello.com/c/h8y2bihg/638-migrate-answer-format-to-rendered
> Add Answer format

- dist/formats/local_transaction/frontend/schema.json
- dist/formats/local_transaction/notification/schema.json
- dist/formats/local_transaction/publisher/schema.json
- dist/formats/local_transaction/publisher_v2/links.json
- dist/formats/local_transaction/publisher_v2/schema.json
- formats/local_transaction/frontend/examples/local_transaction.json
- formats/local_transaction/publisher/details.json
Add and generate local transaction schema.
https://trello.com/c/kfAEfcnM/639-migrate-localtransaction-format-to-rendered
> Create local transaction schema

- formats/contact/frontend/examples/contact_with_email_and_no_other_contacts.json
- formats/contact/frontend/examples/contact_with_webchat.json
- formats/contact/frontend/examples/contact_with_welsh.json
to give better coverage of features in contacts
> Add in extra contact examples

- dist/formats/simple_smart_answer/frontend/schema.json
- dist/formats/simple_smart_answer/notification/schema.json
- dist/formats/simple_smart_answer/publisher/schema.json
- dist/formats/simple_smart_answer/publisher_v2/links.json
- dist/formats/simple_smart_answer/publisher_v2/schema.json
- formats/simple_smart_answer/frontend/examples/simple-smart-answer.json
- formats/simple_smart_answer/publisher/details.json
Also added definitions for nodes and node options.
Generate simple smart answer schema.
Also regenerate all other schemas as we added definitions.
https://trello.com/c/2ucbq949/643-migrate-simple-smart-answer-format-to-rendered
> Add Simple smart answer schema

- dist/formats/completed_transaction/frontend/schema.json
- dist/formats/completed_transaction/notification/schema.json
- dist/formats/completed_transaction/publisher/schema.json
- dist/formats/completed_transaction/publisher_v2/links.json
- dist/formats/completed_transaction/publisher_v2/schema.json
- formats/completed_transaction/frontend/examples/completed_transaction.json
- formats/completed_transaction/frontend/examples/completed_transaction_with_promotion.json
- formats/completed_transaction/publisher/details.json
- formats/completed_transaction/publisher_v2/examples/completed_transaction.json
Add Completed Transaction schema
https://trello.com/c/unTNbCHi/658-migrate-completed-transaction-format-to-rendered
Mobbed with @emmabeynon @whoojemaflip @binaryberry
> Add Completed Transaction schema

- dist/formats/place/frontend/schema.json
- dist/formats/place/notification/schema.json
- dist/formats/place/publisher/schema.json
- dist/formats/place/publisher_v2/links.json
- dist/formats/place/publisher_v2/schema.json
- formats/place/frontend/examples/find-regional-passport-office.json
- formats/place/publisher/details.json
- formats/place/publisher_v2/examples/registrars-offices.json
https://trello.com/c/t3DXuS2t/660-migrate-place-format-to-rendered
> Add place schema

- Jenkinsfile
This reports the runtime of the dependent builds to statsd. With this, we will be able to track:
- How much time the entire test suite is taking
- Which applications are the slowest
This will then allow us to fix the most pressing problems (currently whitehall).
This is the Grafana dashboard:
https://grafana.integration.publishing.service.gov.uk/dashboard/db/ci-performance
Notes that we don't yet know how this behaves for failing tests, that's something to look out for.
https://trello.com/c/5EGPSkfa
> Report runtime of dependent builds to statsd

- Jenkinsfile
Set a flag on those apps that are using the centralised buildProject
script. If so, don't wait for them to complete; they will report their
status individually to the triggering PR (https://github.com/alphagov/govuk-puppet/pull/5625).
https://trello.com/c/5psKmk85
> Send current commit sha to downstream jobs.

- Jenkinsfile
> Add content-store as downstream build

- dist/formats/fatality_notice/publisher_v2/schema.json
- formats/fatality_notice/publisher/edition_links.json
https://trello.com/c/0XEmDdrp/642-fatality-notice-draft-preview
Adds edition links to the fatality notice format.
> Add edition links to fatality notices

- dist/formats/consultation/publisher_v2/schema.json
- formats/consultation/publisher/edition_links.json
Consultations need this to use the draft preview environment.
> Add edition links to consultations

- dist/formats/corporate_information_page/publisher_v2/schema.json
- formats/corporate_information_page/publisher/edition_links.json
Forgot in https://github.com/alphagov/govuk-content-schemas/pull/623 and https://github.com/alphagov/govuk-content-schemas/pull/622.
https://trello.com/c/86sDRf3t
> Add `primary_publishing_organisation` to corporate info

- formats/redirect/README.md
Redirect will behave according to various combinations of attributes. This needed to be captured in documentation for better reference, especially after I couldn't remember how it worked when trying to explain it to someone. I then couldn't find any docs. 
@timblair also requested that this be documented.
> Add details on redirect behaviour

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- lib/govuk_content_schemas/allowed_document_types.yml
Content items with this document type have been removed from the
publishing-api.
> Remove financial releases document types

- dist/formats/calendar/frontend/schema.json
- dist/formats/calendar/notification/schema.json
- dist/formats/calendar/publisher_v2/links.json
- dist/formats/calendar/publisher_v2/schema.json
- formats/calendar.jsonnet
We need to pass the body text to publishing API to allow search indexing by rummager.
https://trello.com/c/EkBg17Ji/499-make-calendars-indexable
> Add calendar schema

- dist/formats/transaction/frontend/schema.json
- dist/formats/transaction/notification/schema.json
- dist/formats/transaction/publisher_v2/schema.json
- formats/shared/definitions/hidden_search_terms.jsonnet
- formats/transaction.jsonnet
https://trello.com/c/tSPsLjz3/489-make-smartanswers-indexable
> Smart answer nodes

- dist/formats/transaction/frontend/schema.json
- dist/formats/transaction/notification/schema.json
- dist/formats/transaction/publisher_v2/schema.json
- formats/shared/definitions/hidden_search_terms.jsonnet
https://trello.com/c/tSPsLjz3/489-make-smartanswers-indexable
> Add description to hidden search terms

- dist/formats/external_content/notification/schema.json
Regenerate schemas to fix the master build. I merged a PR without rebasing, which caused this discrepancy.
> Regenerate schemas

- examples/document_collection/frontend/document_collection.json
Added document_type to organisations and topics links in document_collection example
> Added document_type to organisations and topic links

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
https://trello.com/c/bqRROK99/67-countryside-stewardship-grants-add-4-new-categories
PRs to merge after this one:
- https://github.com/alphagov/rummager/pull/1148
- https://github.com/alphagov/specialist-publisher/pull/1128
> Add four new categories to the CSG finder

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/finder/frontend/aaib-reports.json
- examples/specialist_document/frontend/aaib-reports.json
- formats/shared/definitions/_specialist_document.jsonnet
https://trello.com/c/7z1oGLZ1/1-2-aaib-reports-finder-add-a-new-label-to-aircraft-category
> Add unmanned aircraft systems category

- examples/specialist_document/frontend/residential-property-tribunal-decision.json
For: https://trello.com/c/BvCDLMMQ/27-moj-residential-tribunals-finder
> Rename subcategories for residential tribunal decisions

- examples/speech/frontend/speech.json
Update this example with current data, it will be used by government-frontend integration tests.
> Amend speech example required by integration tests

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- examples/step_by_step_nav/frontend/learn_to_drive_a_car.json
- examples/step_by_step_nav/publisher_v2/learn_to_drive_a_car.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
This enables us to show `and` / `or` as part of the step by step navigation
journey.
> Add  logic to step nav

- Gemfile
- Gemfile.lock
> Remove foreman gem

- examples/publication/frontend/publication-with-step-navs.json
We need this for government-frontend tests.  (I missed this from https://github.com/alphagov/govuk-content-schemas/pull/725 )
> Add publication with step navs example

- examples/consultation/frontend/best-practice-consultation.json
Add consultation best practice example to link to in the guidance for publishers
> Add consultation best practice example

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- examples/step_by_step_nav/frontend/step_by_step_nav-no-steps.json
- examples/step_by_step_nav/publisher_v2/step_by_step_nav-no-steps.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
We want to be able to preview things with titles and introductions only.
This means we have to be able to submit things without step content to the publishing api, which means we need to remove the minItems constraint.
I don't envisage publishing one of these with zero steps!
> Make steps optional

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- examples/step_by_step_nav/frontend/learn_to_drive_a_car.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
The step by step navigation component supports list items with no link.
> Allow list items with no href

- dist/formats/person/frontend/schema.json
- dist/formats/person/notification/schema.json
- dist/formats/person/publisher_v2/schema.json
- formats/person.jsonnet
This commit adds a biography field to the person schema.
> Add biography to person schema

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/knowledge_alpha/frontend/schema.json
- dist/formats/knowledge_alpha/notification/schema.json
- dist/formats/knowledge_alpha/publisher_v2/links.json
- dist/formats/knowledge_alpha/publisher_v2/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- formats/knowledge_alpha.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
- lib/schema_generator/format.rb
See https://github.com/alphagov/publisher/pull/878 for the full backstory.
https://trello.com/c/4mRr4Mzi/30-create-knowledge-api
> Create schema for experimental knowledge API

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
https://trello.com/c/Hf90xZZq/219-drop-down-for-organisations-in-eu-exit-statutory-instrument-specialist-publisher-document-type
Adds `primary_publishing_organisation` and `organisations`.
> Add organisations to statutory instruments

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Reverts alphagov/govuk-content-schemas#777
These should have been placed in `edition_links`
> Revert "Add organisations to statutory instruments"

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
https://trello.com/c/FC7XKG6H/257-add-regional-location-as-a-facet-to-the-finance-and-support-for-your-business-finder
> Add regions to business finance support finder

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Reverts alphagov/govuk-content-schemas#786
> Revert "Add regions to business finance support finder"

- examples/case_study/frontend/case_study.json
These fields are all in the live content-item of that case study. I need the
publishing-app field to be there to change tests I'm carrying out in
govuk-publishing-components.
https://trello.com/c/vhfMGngX/239-investigate-and-correct-smart-answer-google-analytics-tracking
> Update case study example

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Restores alphagov/govuk-content-schemas#786
https://trello.com/c/yUWfjwSN/514-deploy-regional-location-facet-to-finance-and-support-for-your-business-finder
> Revert "Revert "Add regions to business finance support finder""

- dist/formats/gone/notification/schema.json
- dist/formats/redirect/notification/schema.json
- dist/formats/vanish/notification/schema.json
- examples/gone/notification/gone.json
- examples/gone/notification/gone_with_no_base_path.json
- lib/schema_generator/notification_schema_generator.rb
Relates to:
https://github.com/alphagov/publishing-api/pull/1390
https://github.com/alphagov/publishing-api/pull/1391
https://github.com/alphagov/publishing-api/pull/1392
> Require locale in redirect gone and vanish messages

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
Optional boolean to indicate if a finder frontend page should be
indexed with a canonical link by search engines.
> Add optional Canonical field to Finder schema

- docs/contract-testing-howto.md
Remove outdated bits and point to the new repo.
> Update "Adding contract tests to your app"

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- examples/finder/frontend/employment-tribunal-decisions.json
- formats/shared/definitions/finder.jsonnet
Ticket: https://trello.com/c/sEGGP7dF/470-turn-on-option-select-filters-for-finders
> Add "show_option_select_filter" key to schema

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
Trello: https://trello.com/c/CkBPvmeH/532-allow-hidden-facets-to-appear-in-facet-tags-if-used
> Adds hidden clearable facet

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
https://trello.com/c/1yxNntVF/931-add-new-metadata-filters-to-service-standard-reports-finder
> Add new fields to service standard reports

- dist/formats/corporate_information_page/frontend/schema.json
- dist/formats/corporate_information_page/notification/schema.json
- dist/formats/corporate_information_page/publisher_v2/schema.json
- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- formats/corporate_information_page.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
The previous name was incorrect.
https://trello.com/c/sw3IFEw4/1069-change-name-of-new-corporate-information-page-type-in-whitehall
> Change the accessibility statement type name

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
This value is required for associating the correct facets for
constructing facet value linked subscriber lists.
> Adds optional content_id to finder_email_signup

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
[Trello card](https://trello.com/c/3vWYXrjO/801-cma-case-finder-tool-update)
> Add state aid type and outcomes to CMA cases

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
[Trello card](https://trello.com/c/3CyH4j89/892-specialist-publisher-schema-validation-errors)
> Make UK MCAB schema consistent with specialist-publisher

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Adds additional value to UKMCAB types.
Ref: https://github.com/alphagov/specialist-publisher/pull/1509/commits/6f4be3b4d09861efb80f42318912242181bd900d
[trello card](https://trello.com/c/Mr1uHg09/1012-changes-to-the-uk-market-conformity-assessment-bodies-specialist-publisher)
> Update specialist_document schema

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/government/frontend/schema.json
- dist/formats/government/notification/schema.json
- dist/formats/government/publisher_v2/links.json
- dist/formats/government/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- formats/government.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
In preparation for Whitehall publishing governments to the Publishing API.
> Add a government schema

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
- formats/specialist_document.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
https://trello.com/c/TjKgnXWO/1210-create-a-functional-prototype-for-mca-specialist-finder
Related to:
* https://github.com/alphagov/search-api/pull/1857
* https://github.com/alphagov/specialist-publisher/pull/1548
> Create schemas for marine notices

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder_email_signup/frontend/cma-cases-email-signup.json
- formats/finder_email_signup.jsonnet
Related alphagov/search-api#1953
https://trello.com/c/UX2Cd7vr/1211
> Add facet connector to email signups

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
- formats/specialist_document.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
https://trello.com/c/T7fwkaMJ/1177-specialist-traffic-commissioner-judicial-decisions-working-title
> Add traffic_commissioner_regulatory_decision to specialist document schema

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/notification/schema.json
- dist/formats/consultation/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- formats/consultation.jsonnet
- formats/publication.jsonnet
/definitions/multiple_content_types is already an array
> Fix featured_attachments field type

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/notification/schema.json
- dist/formats/consultation/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- formats/consultation.jsonnet
- formats/publication.jsonnet
We're going to have the frontend render these by looking up each ID in
the metadata list and plug that into a component.
> Change featured attachments lists to be lists of attachment IDs 

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Jenkinsfile
- Rakefile
- app.rb
- lib/schema_generator/apply_change_history_definitions.rb
- lib/schema_generator/definitions_resolver.rb
- lib/schema_generator/expanded_links.rb
- lib/schema_generator/format.rb
- lib/schema_generator/frontend_schema_generator.rb
- lib/schema_generator/notification_schema_generator.rb
- lib/schema_generator/publisher_content_schema_generator.rb
- lib/schema_generator/publisher_links_schema_generator.rb
- lib/schema_generator/schema.rb
- lib/tasks/validate.rake
- spec/integration/preview_app_spec.rb
- spec/lib/schema_generator/schema_spec.rb
- spec/spec_helper.rb
- spec/support/schema_builder_helpers.rb
- spec/tasks/validate_uniqueness_of_frontend_example_base_paths_spec.rb
See individual commits for more information.
> Fix linting issues

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- formats/detailed_guide.jsonnet
Related to https://github.com/alphagov/whitehall/pull/5783
> Permit detailed guide edition links

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
This is a new category that MHRA would like to start using.
[Trello Card](https://trello.com/c/gnHVgWtw/2131-add-national-patient-safety-alerts) &middot; [Zendesk Ticket](https://govuk.zendesk.com/agent/tickets/4210399)
> Add National Patient Safety medical alert

- Gemfile
- Gemfile.lock
- Rakefile
- spec/spec_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Please see the commits for more details.
> Add SimpleCov to monitor coverage

- Jenkinsfile
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This is another application that uses content schemas.
> Run tests against content-publisher

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Add Albania as an option for protected foods 
[Trello](https://trello.com/c/SSBGIovv/2277-add-albania-to-protected-food-drink-names-finder)
> [WIP]Add Albania as an option for Protected Foods

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
This is a new category for medical alters to replace the drugs and company-led-drugs categories.
Relates to alphagov/specialist-publisher#1807.
https://trello.com/c/GvEQmeaW/2328-further-changes-to-mhra-finder-categories
> Add medicines-recall-notification

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
The name was updated in [this PR].
[this PR]: https://github.com/alphagov/specialist-publisher/pull/1810
Related [Specialist Publisher change](https://github.com/alphagov/specialist-publisher/pull/1811).
Trello:
https://trello.com/c/rWJ6jhKH/2317-3-add-email-subscription-filters-to-flood-research-report-finder
> Update schema field name

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- formats/publication.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
Trello:
https://trello.com/c/ugeapNY0/2318-5-create-new-standard-document-sub-type-in-whitehall
> Add standard doc type

- examples/role/frontend/prime_minister.json
Add a new example schema for a role. 
context:
https://github.com/alphagov/collections/pull/2294#discussion_r585419358
> Add an example schema for roles

- Jenkinsfile
- README.md
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
Please see the commit messages for more details. I've gone a bit further
in this PR to try and simplify the rest of the README.
> Revise tech docs in README to favour GOV.UK Docker

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/uk-market-conformity-assessment-body.json
- formats/shared/definitions/_specialist_document.jsonnet
https://trello.com/c/Eq7yU0wm/2756-changes-to-ukmcab-specialist-finder-3
> Add new valid options for MCAB Registered Offices

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/product-safety-alerts-reports-recalls.json
- formats/shared/definitions/_specialist_document.jsonnet
- formats/specialist_document.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
Edit product safety alert specialist document and finder after feedback.
Trello: https://trello.com/c/ojsFViiX/2746-create-new-specialist-document-and-finder-product-safety-alerts-unsafe-products-and-recalls-3-5
> Edit product safety alerts specialist document

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- formats/organisation.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
[Trello card](https://trello.com/c/GArvRPWm)
> Add 'Special Health Authority' organisation type

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
This will add Cancelled option to the status field.
[Trello card](https://trello.com/c/ZGpx4wvb/653-5046102-making-changes-to-the-protected-food-and-drink-names-register-on-specialist-publisher-defra-department-for-environment-f)
> Change to a Defra specialist document

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/finder/frontend/maib-reports.json
- examples/specialist_document/frontend/maib-reports.json
- formats/shared/definitions/_specialist_document.jsonnet
As requested [Trello card](https://trello.com/c/6OoRo5vK/708-change-report-type-for-marine-accident-investigation-branch-reports)
> Change report type for Marine Accident Investigation Branch reports

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- dist/formats/topical_event/frontend/schema.json
- dist/formats/topical_event/notification/schema.json
- dist/formats/topical_event/publisher_v2/schema.json
- dist/formats/world_location_news/frontend/schema.json
- dist/formats/world_location_news/notification/schema.json
- dist/formats/world_location_news/publisher_v2/schema.json
- examples/specialist_document/frontend/animal-disease-case.json
- formats/shared/definitions/_specialist_document.jsonnet
- formats/specialist_document.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
Add new specialist document
Trello card: https://trello.com/c/bXI3zWdc/584-create-new-specialist-finder-for-animal-disease-cases-and-disease-control-zones
> Add animal disease case

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/animal-disease-case.json
- formats/shared/definitions/_specialist_document.jsonnet
Publisher requested amendments to the disease finder:
- Make virus strain a free text field
- add new disease zone types
Trello card: https://trello.com/c/bXI3zWdc/584-create-new-specialist-finder-for-animal-disease-cases-and-disease-control-zones
> Amendments to disease finder

- examples/specialist_document/frontend/export-health-certificates.json
Trello card: https://github.com/alphagov/specialist-publisher/tree/rename-eurasian-customs-union
> rename eurasian customs union to eurasian economic union

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/countryside-stewardship-grants.json
- formats/shared/definitions/_specialist_document.jsonnet
Trello card: https://trello.com/c/pauLWXuH/827-5102253-request-for-an-additional-filter-content-change-request-rural-payments-agency-rpa
> Add new land use filter
