alphagov/govuk-content-schemas

- formats/case_study/frontend/examples/translated.json
This is to make the example more useful in testing.
> Add another locale to translated example.

- formats/case_study/publisher/schema.json
- formats/coming_soon/publisher/schema.json
- formats/finder/publisher/schema.json
- formats/metadata.json
- formats/unpublishing/publisher/schema.json
- lib/govuk_content_schemas/frontend_schema_generator.rb
- spec/lib/frontend_schema_generator_spec.rb
We want to remove base_path from the request body in the publishing context as
it is a potential source of error. Making it optional is the first step to
removing it.
The frontend representation will continue to include `base_path`. This will be
automatically inserted by the content store.
> Deprecate base_path in publishing context

- formats/finder/frontend/examples/contacts.json
- formats/finder/frontend/schema.json
- formats/finder/publisher/details.json
- formats/finder/publisher/links.json
- formats/finder/publisher/schema.json
Allowing unspecified properties leaves the way open for typos in field names,
undocumented fields and other errors. I found some problems in contacts-admin
after making this change.
I've also added an example for a Contact finder as they are a bit different.
cc @evilstreak @edds @tommyp
> Disallow unspecified properties in finders

- formats/case_study/frontend/examples/archived.json
This means that all of the existing examples can be uniquely identified by the
base_path. This makes it easier to tell which is which, and also means that the
base_path can be used as a key in a hash or test name.
> Make examples have distinct base_paths

- Makefile
- bin/ensure_example_base_paths_unique
- spec/bin/ensure_example_base_paths_unique_spec.rb
It's convenient to ensure that all examples have unique base paths because then they can be referenced in tests by url.
> Enforce unique base path in examples

- formats/finder/frontend/examples/cma-cases.json
- formats/finder/frontend/schema.json
- formats/finder/publisher/details.json
- formats/finder/publisher/schema.json
I'm making some small changes in specialist-publisher so that it generates
valid documents according to this schema.
> Expand finder schema to cover specialist publisher's finders

- formats/case_study/frontend/examples/archived.json
- formats/case_study/frontend/examples/case_study.json
- formats/case_study/frontend/schema.json
- formats/case_study/publisher/links.json
- formats/case_study/publisher/schema.json
https://trello.com/c/pfvFRgg5
`government-frontend` doesn't display document collection membership next to 'Part of:' in the metadata section in the header or footer as shown here:
https://www.gov.uk/government/case-studies/clever-engineering-macrete-bridges-the-technology-gap
this field should carry that bit of information so that it gets displayed on government-frontend.
> Add document_collections to links

- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_with_inapplicable_nations.json
- formats/policy/frontend/schema.json
- formats/policy/publisher/details.json
- formats/policy/publisher/schema.json
This commit updates the schema for Policies to have nation applicability. The `nation_applicability` hash contains an array of strings which the nations that the Policy applies to along with an array of hashes with the nation and alt_poicy_url for each nation that the policy isn't applicable to.
> Add nation_applicability to Policies

- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
With changes to Policy Publisher, `nation_applicability` is only part of the published content item if it doesn't apply to all nations. This commit removes it from the Policy Area and Programme examples.
> Remove required nation applicability

- formats/finder/frontend/schema.json
- formats/finder/publisher/details.json
- formats/finder/publisher/schema.json
- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/frontend/examples/policy_with_inapplicable_nations.json
- formats/policy/frontend/schema.json
- formats/policy/publisher/details.json
- formats/policy/publisher/schema.json
This PR changes the Finder and Policy schemas to allow for Facets which don't have a `name` or `type`. This is the case in the update to the Policy examples which has `is_historic` and `government_name` which aren't treated as normal metadata by Finder Frontend and as such don't require these to be present.
> Change finder and policy metadata

- bin/combine_publisher_schema
- formats/placeholder/frontend/schema.json
- formats/placeholder/publisher/details.json
- formats/placeholder/publisher/links.json
- formats/placeholder/publisher/schema.json
- lib/govuk_content_schemas/schema_combiner.rb
We have around ~~149,161~~ 153,236 placeholder items, but we don't have a schema for the
format. I've developed this against the placeholders produced by (mainstream)
publisher and whitehall. Some small changes will be required for publisher to
supply additional fields like "locale", but Whitehall's placeholders are already valid against this schema.
Once this is merged, I'll open PRs to test Whitehall's placeholders and to add schema tests to Publisher.
> Add format for "placeholder" items

- formats/mainstream_browse_page/frontend/examples/level_2_page.json
- formats/mainstream_browse_page/frontend/examples/level_2_page_with_related_topics.json
- formats/mainstream_browse_page/frontend/examples/top_level_page.json
- formats/mainstream_browse_page/frontend/schema.json
- formats/mainstream_browse_page/publisher/details.json
- formats/mainstream_browse_page/publisher/links.json
- formats/mainstream_browse_page/publisher/schema.json
- formats/topic/frontend/examples/curated_subtopic.json
- formats/topic/frontend/examples/topic.json
- formats/topic/frontend/examples/uncurated_subtopic.json
- formats/topic/frontend/schema.json
- formats/topic/publisher/details.json
- formats/topic/publisher/links.json
- formats/topic/publisher/schema.json
Add schemas for topics and mainstream browse pages.
These are (or will shortly be) sent from the collections-publisher app.  I'll be adding contract tests on collections-publisher, collections-api and collections (frontend) after this is merged.
We're likely to greatly expand the information included in these formats in the reasonably near future, but for now I've just included the fields we've planned to include in our current piece of work (which is for linking from mainstream browse to topic pages).
I separated the automatically generated files into a separate commit; only the two commits for adding the topics and mainstream browse manually-generated files need to be reviewed.
> Add topics and mainstream browse page

- formats/email_alert_signup/frontend/examples/email_alert_signup.json
- formats/email_alert_signup/frontend/schema.json
- formats/email_alert_signup/publisher/details.json
- formats/email_alert_signup/publisher/links.json
- formats/email_alert_signup/publisher/schema.json
This commit adds a schema for the new email-alert-signup format along with an example. It currently only contains 2 items in the details hash: `tags` and `breadcrumbs`.
> Schema for email-alert-signup

- formats/policy/frontend/examples/minimal_policy_area.json
- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/frontend/examples/policy_with_inapplicable_nations.json
- formats/policy/frontend/schema.json
- formats/policy/publisher/links.json
- formats/policy/publisher/schema.json
This PR adds the `email_alert_signup` as an entry in the links array to policies. This is marked as being required as all policies should have a signup page.
I've also cleaned up some mismatched data in one of the policy examples.
> Email alert signup on policy

- Gemfile
- Gemfile.lock
- README.md
- dummy_content_store/README.md
- dummy_content_store/config.ru
- dummy_content_store/lib/dummy_content_store/app.rb
- dummy_content_store/lib/dummy_content_store/example_content_item.rb
- dummy_content_store/startup.sh
This is a self-contained rack app which will read example files from the
example folder.
It can be run either using the `startup.sh` shell script, or as a rack
up directly using rackup and the `config.ru` file.
We ensure that file changes propogate immediately by doing the
following:
- Set the `Cache-control: no-cache` header to ensure that the content
store client does not cache the fetched items.
- Always read the file from disk so that changes propogate immediately.
It runs on port 3068 (the content store port) and serves the examples using the urls in the example files themselves. Example urls are required to be unique.
> Dummy server for example content

- formats/email_alert_signup/frontend/examples/email_alert_signup.json
- formats/email_alert_signup/frontend/schema.json
- formats/email_alert_signup/publisher/details.json
- formats/email_alert_signup/publisher/schema.json
As we shouldn't be using the description for this purpose, I've changed email alert signup pages to have a summary in the details hash instead.
> Add a summary to email alert signups

- dummy_content_store/config.ru
When the content store is accessed via the public API, it receives
requests on /api/content, instead of just on /content.  Support this
route in the dummy server, so that we can test things in that context.
> Support the /api/content route

- formats/case_study/frontend/examples/archived.json
- formats/case_study/frontend/examples/case_study.json
- formats/case_study/frontend/examples/translated.json
- formats/finder/frontend/examples/cma-cases.json
- formats/finder/frontend/examples/contacts.json
- formats/finder/frontend/examples/finder.json
- formats/mainstream_browse_page/frontend/examples/level_2_page_with_related_topics.json
- formats/policy/frontend/examples/minimal_policy_area.json
- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/frontend/examples/policy_with_inapplicable_nations.json
- formats/unpublishing/frontend/examples/unpublishing.json
Now that the content store API is public, make all the `api_url` fields
in links point at it (ie, start with the
`https://www.gov.uk/api/content/` prefix).  Also, make all the `web_url`
fields point at `https://www.gov.uk` - most of these already did, but a
few pointed at `dev.gov.uk` or other places.
Previously, the examples were inconsistent in what environment they
pointed to.
This makes the examples consistent, and if applications use them they'll
be more likely to work correctly to at least some extent.
It would be nice in future PRs to validate that all examples used these
standard prefixes, and to make the dummy_content_store app parse these
to return the appropriate initial prefixes for the environment.
However, I would like to get this tidyup merged without waiting for such …
> Normalise the api_url and web_url paths in examples

- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
Policy finders are going to display metadata for orgs, document type and date updated.
This adds the facet options required to show them to both the policy and program example content, so they can be used by finder frontend as test fixtures and for manual testing against dummy content store.
Originally I took the approach of a `result_metadata_name_key` facet option that allowed `finder-frontend` to use config to decide which key to use. 
After discussion with @evilstreak and @rboulton I decided it would cleaner/simpler to keep this display logic in `finder-frontend`. Putting it in schemas feels more complicated, and would only get more complex/add many more options, for other display logic.
The long term solution is standardised field representations in rummager, but in the mean time …
> Update policy finder examples

- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
These are being added in the policy publisher and will be on all policy finders.
Policy publisher updated in https://github.com/alphagov/policy-publisher/pull/54
> Update policy examples with date filtering facets

- formats/case_study/frontend/schema.json
- formats/case_study/publisher/schema.json
- formats/coming_soon/frontend/examples/coming_soon.json
- formats/coming_soon/frontend/schema.json
- formats/coming_soon/publisher/schema.json
- formats/email_alert_signup/frontend/schema.json
- formats/email_alert_signup/publisher/schema.json
- formats/finder/frontend/schema.json
- formats/finder/publisher/schema.json
- formats/mainstream_browse_page/frontend/schema.json
- formats/mainstream_browse_page/publisher/schema.json
- formats/metadata.json
- formats/placeholder/frontend/schema.json
- formats/placeholder/publisher/schema.json
- formats/policy/frontend/schema.json
- formats/policy/publisher/schema.json
- formats/topic/frontend/schema.json
- formats/topic/publisher/schema.json
- formats/unpublishing/frontend/schema.json
- formats/unpublishing/publisher/schema.json
This is currently optional in content-store, making it required here is a route
to making it required there (and then backfilling the data).
We have been thinking of public_updated_at as "the updated date which users
see" and because some formats don't display this (eg gone/redirect items), it
has been optional.
However, it seems to me that it isn't about what the user sees, but when there
was last a (significant) semantic change to the content at the URL. Therefore,
everything should have a public_updated_at.
As an example, it being optional meant that a placeholder without a
public_updated_at was added by publisher which then broke an expectation in
email-alert-service and stopped it from consuming any more messages from the
queue.
To make the Whitehall tests pass for "coming soon" …
> Make public_updated_at required for renderable content

- formats/finder/frontend/examples/cma-cases.json
- formats/finder/frontend/schema.json
- formats/finder/publisher/details.json
- formats/finder/publisher/schema.json
As all Finders that want it now have email alert signup being live, we don't care about keeping this feature hidden. This commit removes it from the schema and the example that had it.
> Drop email alert signup enabled from Finders

- formats/finder/frontend/examples/esi-funds.json
- formats/finder/frontend/schema.json
- formats/finder/publisher/details.json
- formats/finder/publisher/schema.json
European Structural and Investment funds must comply with EU legislations and they therefore need to display the EU logo.
Quote from the legislation: "the Union emblem and the reference to the Union shall be visible, when landing on the website, inside the viewing area of a digital device, without requiring a user to scroll down the page".
ticket:
https://www.pivotaltracker.com/story/show/92225774
linked to:
alphagov/finder-frontend#189
https://github.com/alphagov/specialist-publisher/pull/474
> Add EU logo_path to finders schema

- Gemfile
- Gemfile.lock
no longer needed as dummy-content-store is now in a gem
> Remove rack

- dist/formats/manual/frontend/schema.json
- dist/formats/manual/publisher/schema.json
- formats/manual/frontend/examples/content-design.json
- formats/manual/publisher/details.json
Another schema will be required for HMRC manuals as they are similar but
different (mainly additive).
I used the real content-design manual as a frontend example, but truncated it as it ran
to ~800 lines.
Using this schema in specialist-publisher will come in a Pull Request after this is merged (the tests can't pass until then), but is in a branch here: https://github.com/alphagov/specialist-publisher/compare/validate_manuals_against_schema?expand=1
> Define a schema for manuals

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/finder/publisher/details.json
- formats/policy/publisher/details.json
This is used on policy finders and the finder of policies.
It's causing https://github.com/alphagov/policy-publisher/pull/60 to fail at the moment.
> Add 'result_metadata_name_key' to finder schemas

- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- formats/hmrc_manual/frontend/examples/vat-government-public-bodies.json
- formats/hmrc_manual/publisher/details.json
- formats/hmrc_manual_section/frontend/examples/vatgpb1000.json
- formats/hmrc_manual_section/publisher/details.json
I decided to do this as there wasn't much effort required (mainly copying and pasting) but it guards against us changing things in such a way that breaks hmrc-manuals-api, which is something of an odd-one-out.
Contract tests for hmrc-manuals-api in a branch here pending the merge of the schemas: https://github.com/alphagov/hmrc-manuals-api/compare/add_schema_tests 
and the same for manuals-frontend: https://github.com/alphagov/manuals-frontend/compare/contract_tests_for_hmrc_manuals?expand=1
> Add schemas for hmrc manuals

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- formats/email_alert_signup/frontend/examples/email_alert_signup.json
- formats/email_alert_signup/publisher/details.json
As we want to make Email Alert Signup work even when there are duplicate
topic names (thanks Govdelivery) we want to use a `govdelivery_title` to
allow us to specify something different to use when creating the topic
in govdelivery if it is a duplicate of an existing topic.
> Add govdelivery_title to email alert signup

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/finder/frontend/examples/policies_finder.json
- formats/finder/publisher/details.json
- formats/policy/publisher/details.json
For the Policies Finder, ordering by last update doesn't make sense as
the content being updated within each policy doesn't bubble up to update
the policy itself. This commit adds a `default_order` to the Finders and
Policy schemas along with adding an example to `/finders` of the Policy
Finder which uses this.
> Add default order to Finders

- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/publisher/links.json
In order to allow us to infer tagging from programmes to policy areas we
need to send the content ids of the parent policy in a programme.
> Add policy areas in programmes

- Makefile
The `wildcard` call for the publisher schema was being expanded at parse
time, and therefore doesn't handle expansion of the `%` variable.  This
meant that changes to the links.json weren't being noticed, and the
corresponding schemas not being rebuilt.  Fix this by using a simple
wildcard to depend on `*.json` in the publisher directory.
This also removes the unnecessary usage of the `%/..` to locate the
global definitons (metadata.json and frontend_links_definition.json) in
favor of pointing directly at the files.
> Fix dependencies in Makefile.

- dist/formats/case_study/frontend/schema.json
- dist/formats/coming_soon/frontend/schema.json
- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/finder/frontend/schema.json
- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/manual/frontend/schema.json
- dist/formats/manual_section/frontend/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/unpublishing/frontend/schema.json
- formats/frontend_links_definition.json
Necessary to allow rendering mainstream browse pages (eg https://www.gov.uk/browse/benefits) from the content-store.
This also includes an update to make the `title`, `base_path` and `locale` fields mandatory in the expansion.
Once this is merged, I'll raise a follow-up PR on content-store to include this field in the expansion.
> Allow description to be included in linked item expansion

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- formats/mainstream_browse_page/publisher/links.json
Needed to support rendering mainstream browse pages (eg
https://www.gov.uk/browse/benefits) from the content-store.
/cc @rboulton
> Add some link types to mainstream_browse_page

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- formats/mainstream_browse_page/frontend/examples/curated_level_2_page.json
- formats/mainstream_browse_page/publisher/details.json
Some mainstream browse pages will be getting curated lists of links, instead of a flat list.
This commit adds an optional `groups` array to the `mainstream_browse_page` schema. Specification for this is copied from the `topic` schema.
FAO @rboulton 
Trello: https://trello.com/c/dsgpdVKG
> Add curated links to mainstream browse pages

- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- formats/topic/frontend/examples/topic-in-beta.json
- formats/topic/publisher/details.json
Topics can be in beta now, so we need a boolean. It can also be null/empty, since older topics don't have the `beta` label set. Used the `finder` schema as an example ([source](https://github.com/alphagov/govuk-content-schemas/blob/master/formats/finder/publisher/details.json#L11)).
Trello: https://trello.com/c/H9UMp051/139-allow-topic-subtopics-to-be-labelled-as-beta
> Add `beta` attribute to topic 

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- formats/case_study/frontend/examples/archived.json
- formats/case_study/publisher/details.json
"archived" documents are now referred to as "withdrawn" in whitehall.
This lets us send withdrawn content to the content store as well as
archived. Once all content has been updated to start sending withdrawn a
further commit will be added to remove archived.
> Update archived to be withdrawn

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- formats/mainstream_browse_page/frontend/examples/curated_level_2_page.json
- formats/mainstream_browse_page/frontend/examples/level_2_page.json
- formats/mainstream_browse_page/frontend/examples/level_2_page_with_related_topics.json
- formats/mainstream_browse_page/frontend/examples/root_page.json
- formats/mainstream_browse_page/publisher/links.json
Browse pages need to be able to render themselves, therefore we're adding the links to sibling, parent and child pages to the schema.
> Add examples for browse page context links

- dist/formats/mainstream_browse_page/publisher/schema.json
- formats/mainstream_browse_page/publisher/links.json
We've changed the semantics of these a bit, so the descriptions needed
to be updated.  The main change is that we're always going to send
active_top_level_browse_page, except for on the root browse page.
> Correct comments about browse page links fields

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/coming_soon/frontend/schema.json
- dist/formats/coming_soon/publisher/schema.json
- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/manual/frontend/schema.json
- dist/formats/manual/publisher/schema.json
- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/publisher/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/unpublishing/frontend/schema.json
- dist/formats/unpublishing/publisher/schema.json
- docs/suggested-workflows.md
- formats/case_study/frontend/examples/access_limited.json
- formats/metadata.json
Adds an `access_limited` object to the metadata, which appears as the top level in all generated schemas. This currently consists of a single value, `users`, which is a list of user IDs.
(Note that user IDs generated from signon are inconsistent; some are GUIDs and some are what looks like hashed strings, so there is no attempt to enforce a format here.)
Also adds an example of access limiting in a case study.
> Add support for access limiting

- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/topic/publisher/schema.json
- formats/mainstream_browse_page/publisher/links.json
- formats/topic/publisher/links.json
Both the mainstream_browse_page active_top_level_browse_page, and the
topic parent link types are singuler types, and therefore should never
have more than one item in them.  This adds this restriction to the
schema.
> Enforce that singular link types are singular.

- formats/topic/frontend/examples/curated_subtopic.json
- formats/topic/frontend/examples/topic-in-beta.json
- formats/topic/frontend/examples/topic.json
- formats/topic/frontend/examples/uncurated_subtopic.json
We've moved topics to the /topic namespace. This commit updates the examples so they match the real world.
> Update topic examples with new namespace

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/finder/publisher/details.json
- formats/policy/frontend/examples/policy_area.json
- formats/policy/publisher/details.json
As we are introducing Pagination to Finders we need to be able to
specify the amount per page of the results. This commit adds it to both
the Finder and Policy formats and adds it to the Policy Area example.
> Add documents_per_page to Finders

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- formats/mainstream_browse_page/frontend/examples/top_level_page.json
- formats/mainstream_browse_page/frontend/examples/top_level_page_with_child_pages_in_curated_order.json
- formats/mainstream_browse_page/publisher/details.json
Currently, all 2nd level mainstream browse columns have the label "A to Z" on them. When a page has been curated, we shouldn't display this label, because it won't be true.
Therefore, collections,  needs to know the child ordering type for a top level mainstream browse pages in order to display related labels.
https://trello.com/c/bcTrheDZ/244-don-t-show-a-to-z-on-mainstream-browse-columns-which-aren-t-in-alphabetical-order
> Add child ordering to mainstream browse page

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- formats/finder/publisher/details.json
As we want to create a Finder which is a firehose of all policy tagged
content on GOVUK, we need to add `policies` to the `filter` hash within
the Finder.
> Add policies filter to finder

- formats/specialist_document/frontend/examples/aaib-reports.json
- formats/specialist_document/frontend/examples/cma-cases.json
- formats/specialist_document/frontend/examples/countryside-stewardship-grants.json
- formats/specialist_document/frontend/examples/drug-device-alerts.json
- formats/specialist_document/frontend/examples/drug-safety-update.json
- formats/specialist_document/frontend/examples/european-structural-investment-funds.json
- formats/specialist_document/frontend/examples/international-development-funding.json
- formats/specialist_document/frontend/examples/maib-reports.json
- formats/specialist_document/frontend/examples/raib-reports.json
In the specialist document examples, all the base_path values need to start with a slash for consistency and compatibility with the dummy-content-store.
> Base paths need a leading slash.

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- formats/specialist_document/frontend/examples/aaib-reports.json
- formats/specialist_document/frontend/examples/cma-cases.json
- formats/specialist_document/frontend/examples/countryside-stewardship-grants.json
- formats/specialist_document/frontend/examples/drug-device-alerts.json
- formats/specialist_document/frontend/examples/drug-safety-update.json
- formats/specialist_document/frontend/examples/european-structural-investment-funds.json
- formats/specialist_document/frontend/examples/international-development-funding.json
- formats/specialist_document/frontend/examples/maib-reports.json
- formats/specialist_document/frontend/examples/raib-reports.json
- formats/specialist_document/publisher/details.json
The `change_note` field contains the same content as the last entry in
the `change_history` (the last entry is the most recent one).
It's superfluous to duplicate that information in an additional
top-level field, and doing so introduces potential for confusion and
errors.
At present it's believed that the email alert api would use the
`change_note` field when listening on the message queue, however
specialist documents are not sent to the email-alert-api in that way and
we do not intend to do that in the future.
> Remove change_note from specialist documents

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- formats/placeholder/publisher/details.json
We want to consistently tag pages across GOV.UK in Google Analytics with:
* organisations
* world_locations
* world_organisations
Whitehall mints a short `analytics_identifier` for each of these things and sends it to Google Analytics in the frontend. This means content from content-store can't send the data to Google Analytics.
So, for content rendered from content-store, we will include these identifiers in the content item for each organisation/world_location/world_organisation, and then include it when expanding the `links` hash out for a content item so that it's available when the frontend is sending the data to Google Analytics.
The changes to include it in the frontend schema will come later, when we get to implementing the expansion.
/cc @danielroseman @rboulton
> Add optional analytics_identifier to placeholder format

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- formats/finder/publisher/details.json
In order to exclude certain values from a query built by a Finder we
need to add `reject` as an object, similar to the `filter`. This is then
used by Finder Frontend when constructing the query.
> Add reject to Finders

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- formats/mainstream_browse_page/frontend/examples/curated_level_2_page.json
- formats/mainstream_browse_page/publisher/details.json
- formats/topic/frontend/examples/curated_subtopic.json
- formats/topic/publisher/details.json
collections-publisher now sends details of curated list contents as
an array of base_paths as opposed to api_urls. Update the schema and
examples accordingly. This also validates that the values given are all
valid absolute URL paths.
> topic and mainstream_browse_page now use paths

- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- formats/hmrc_manual/publisher/links.json
HMRC Manuals're in the process of becoming 'linkable' to topics.
It was decided that we should publish a manual's list of topics as part of its
`links` data, as an array of topic content_ids.
> Add #/links/topics to HMRC Manuals

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/coming_soon/frontend/schema.json
- dist/formats/coming_soon/publisher/schema.json
- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/manual/frontend/schema.json
- dist/formats/manual/publisher/schema.json
- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/publisher/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/unpublishing/frontend/schema.json
- dist/formats/unpublishing/publisher/schema.json
- formats/metadata.json
So that we can easily expand the analytics identifiers in the links hash
add it to the root metadata.
The use case for this is that we have many things in the content store
that have short codes we use in analytics (to get around character
limits in dimensions). Any page which gets linked to any of these
objects should have those short codes exposed on the frontend. Adding
these codes to the links hash means that frontends won't need to make a
query to the content store for every object in the links hash. Having
the identifiers in the root object rather than in the details hash means
that we don't need to load the entire details hash to generate the links
hash objects.
> Add analytics identifier to root metadata

- bin/convert_finder_schemas
* Automate mapping from file name to document type when mapping not already provided in schema convert script.
* Log when implicit mapping has occurred, and inform how to override by adding an explicit mapping.
* Reduces the need to re-edit the script for future document types that adhere to usual file naming convention.
* Remove mappings that follow the usual naming convention.
> Auto-map from file name to document type in convert script

- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- formats/hmrc_manual/publisher/details.json
This change adds 'tags' under 'details', and 'topics' under those 'tags'.
This is the format expected by Email Alert Service in the Current World, as
demonstrated in the Case Study schema.
> Add topic tags to HMRC Manuals

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/coming_soon/frontend/schema.json
- dist/formats/coming_soon/publisher/schema.json
- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/manual/frontend/schema.json
- dist/formats/manual/publisher/schema.json
- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/publisher/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/unpublishing/frontend/schema.json
- dist/formats/unpublishing/publisher/schema.json
- formats/finder/frontend/examples/all_policies.json
- formats/metadata.json
This PR adds a phase attribute for a Content Item. It can only be present with
`alpha` or `beta` as the attributes. This can then be used by the Rendering
Application to switch functionality or visual features based on the phase.
> Add Phase for alpha or beta

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- formats/finder/frontend/examples/asylum-support-decisions.json
- formats/specialist_document/frontend/examples/asylum-support-decision.json
- formats/specialist_document/publisher/details.json
Add schema and examples for asylum support decisions - a new specialist document type.
> Add asylum support decision schema and examples

- dist/formats/gone/publisher/schema.json
- formats/gone/publisher/examples/gone.json
- formats/gone/publisher/schema.json
From the [content-store docs](https://github.com/alphagov/content-store/blob/0e96e934206abd54e057e63a7eb6beaf71d21f60/doc/gone_item.md
):
> To represent content that is no longer available, the content store supports items with a format of "gone". These will cause a gone route to be setup in the router so that the item returns a 410 HTTP status.
This item is based on [the redirect format](https://github.com/alphagov/govuk-content-schemas/tree/master/formats/redirect).
This format will be used for testing the creation of gone routes for draft content-items in https://github.com/alphagov/collections-publisher/pull/138.
Related Trello: https://trello.com/c/ybdnGMhl
> Add "Gone" format

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/coming_soon/frontend/schema.json
- dist/formats/coming_soon/publisher/schema.json
- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/hmrc_manual/frontend/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/manual/frontend/schema.json
- dist/formats/manual/publisher/schema.json
- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/publisher/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/unpublishing/frontend/schema.json
- dist/formats/unpublishing/publisher/schema.json
- formats/metadata.json
Given live is one of the [service design phases](https://www.gov.uk/service-manual/phases) it makes sense for it to be one of the allowed options. This will allow publishing apps to be simpler, avoiding examples like https://github.com/alphagov/collections-publisher/blob/master/app/presenters/tag_presenter.rb#L60-L63
Before this is merged, the [content-store validations](https://github.com/alphagov/content-store/blob/master/app/models/content_item.rb#L61-L64) will need to be updated to allow this value. I'd also suggest that the field should be defaulted to 'live' when not explicitly set in an incoming request.
> Allow service design phase to be 'live'

- dist/formats/case_study/publisher/schema.json
- dist/formats/coming_soon/publisher/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/hmrc_manual/publisher/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/manual/publisher/schema.json
- dist/formats/manual_section/publisher/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/unpublishing/publisher/schema.json
- formats/metadata.json
Routes are required by the content-store. We should make them mandatory here as well so that we can test that content we send to publishing-api is actually valid.
Inspired by https://github.com/alphagov/calendars/pull/93, where the contract tests passed, but publishing failed.
> Make routes required

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- formats/finder/publisher/details.json
- formats/policy/publisher/details.json
Now that Finders/Policies can use a `reject` hash to build the base query, we no
longer require a `filter` hash to be present.
> Finders don't require a Filter

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- formats/finder/frontend/examples/tax-tribunal-decisions.json
- formats/specialist_document/frontend/examples/tax-tribunal-decision.json
- formats/specialist_document/publisher/details.json
The Upper Tribunal (Tax and Chancery Chamber) publishes decisions that describe the outcome of a tribunal case.
Tribunal decision finders are used by public, professionals and the tribunals themselves to search for past decisions.
Published decisions form a part of case law and are used for research purposes and to prepare for current or future cases.
> Add tax tribunal decisions schema and examples

- Rakefile
When running `bundle exec rake` previously it only ran `make`, which
doesn't rebuild the schemas each time which sometimes passes when it
shouldn't.
This commit changes `rake` to run `make clean` which deletes all the
derived files and regenerates them.
> Running rake now runs make clean && make

- bin/combine_publisher_schema
A format can have a `metadata.json` and a `links.json` file, but these are not required. This warning gives the impression something is wrong when one of them is missing, while everything is :ok_hand:.
```
bundle exec ./bin/combine_publisher_schema formats/case_study/publisher dist/formats/case_study/publisher/schema.json
bundle exec ./bin/combine_publisher_schema formats/coming_soon/publisher dist/formats/coming_soon/publisher/schema.json
Warning: formats/coming_soon/publisher/links.json not found
bundle exec ./bin/combine_publisher_schema formats/email_alert_signup/publisher dist/formats/email_alert_signup/publisher/schema.json
bundle exec ./bin/combine_publisher_schema formats/finder/publisher dist/formats/finder/publisher/schema.json
bundle exec ./bin/combine_publisher_schema …
```
> Remove warning from build log

- spec/lib/finder_schema_converter_spec.rb
Depending on the OS, the results of Dir.glob might not be in the order
you expect them. http://ruby-doc.org/core-2.1.2/Dir.html#method-c-glob
This causes this test to fail sometimes.
> Don't expected Dir.glob to return ordered filenames

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- formats/specialist_document/publisher/details.json
https://trello.com/c/tiCatwpE/117-add-two-new-alert-types-to-mhra-drug-device-alerts-finder-small
MHRA are removing these remaining alerts away from publications to a
finder.
Related: 
https://github.com/alphagov/rummager/pull/530
https://github.com/alphagov/specialist-publisher/pull/581
> Add two new HMRA alert types

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- formats/service_manual_guide/frontend/examples/basic_with_related_discussions.json
- formats/service_manual_guide/publisher/details.json
We're working on [Service Manual Publisher](https://github.com/alphagov/service-manual-publisher) and are close to getting a prototype of a guide format merged in there. 
[One of the tests](https://github.com/alphagov/service-manual-publisher/commit/73f991e85ed7363a3816c2cac2bcc6c79572b7a2) relies on changes in this branch, I believe this schema represents the service manual guide format quite well and no major changes will need to be done, so this should be a good time to merge.
/cc @KushalP
> Add a schema for service manual publisher guide

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- formats/finder/frontend/examples/employment-appeal-tribunal-decisions.json
- formats/specialist_document/frontend/examples/employment-appeal-tribunal-decision.json
- formats/specialist_document/publisher/details.json
The Employment Appeal Tribunal publishes decisions that describe the outcome of a tribunal case.
Tribunal decision finders are used by public, professionals and the tribunals themselves to search for past decisions.
Published decisions form a part of case law and are used for research purposes and to prepare for current or future cases.
> Add employment appeal tribunal decisions schema and examples

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- formats/email_alert_signup/frontend/examples/email_alert_signup.json
- formats/email_alert_signup/publisher/details.json
- formats/email_alert_signup/publisher/links.json
As part of the effort to convert email alerting to rely on content IDs
rather than slugs, this change adds a field to email alert signup pages
that provides a reference to the parent piece of content. This makes it
easier for the email-alert-frontend to obtain the correct content ID to
send on to the email-alert-api.
> Add parent link to email_alert_signup schema

- templates/links.json
The `links.json` files no longer need to include this definition because
it's now part of the base format (defined in `formats/metadata.json`).
These templates are used by the `new_format` rake task.
> Remove guid_list definition from links template.

- dist/formats/redirect/publisher/schema.json
- formats/redirect/publisher/examples/redirect-with-replacement.json
- formats/redirect/publisher/schema.json
`replaced_content_item` is the optional content_id of the item this redirect is replacing.
It allows publishing-api to add special behaviour for putting back redirects.
It will also be added to the coming_soon format (https://github.com/alphagov/govuk-content-schemas/pull/141).
/cc @elliotcm
> Add `replaced_content_item` for redirects

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- formats/email_alert_signup/frontend/examples/email_alert_signup.json
- formats/email_alert_signup/publisher/details.json
This states explicitly the kind of page a given email signup is handling.
This improves clarity when viewing an email-signup content item retrieved
from the content store, and also helps the email-alert-frontend (for example)
resolve how to format its subscription payload for the email-alert-api.
The goal of all this is to handle email subscription/alerting via content
IDs in the links hash and eventually move away from the use of slugs.
> Add email_alert_type to email_alert_signup details hash

- dist/formats/redirect/publisher/schema.json
- formats/redirect/publisher/examples/redirect-with-replacement.json
- formats/redirect/publisher/examples/redirect.json
- formats/redirect/publisher/schema.json
After
https://github.com/alphagov/publishing-api/commit/5e5397f4c3e8bf680977ebc5417e0947d563cc18
made base_path mandatory, we need to update content schemas to reflect
this.
> Require base_path in redirect

- dist/formats/redirect/publisher/schema.json
- formats/redirect/publisher/schema.json
The v1 endpoints require this but the v2 endpoints
don't.
> Make update_type optional for redirects.

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- formats/service_manual_guide/frontend/examples/basic_with_related_discussions.json
- formats/service_manual_guide/publisher/details.json
We have realised that using publisher to indicate the group responsible for a
piece of content can be ambiguous because within GOV.UK we use the term
"publisher" to name applications that publish content.
I've used this opportunity to rename publisher.name to content_owner.title too
to make it consistent with code in other related repos and bring it in line
with "related_discussion" fields' naming conventions.
Other repos that need this renaming:
service-manual-publisher (branch rename_publisher)
government-frontend (branch service-manual-frontent-real-data)
We will not need to sync deploys or migrate data because none of those are used
in production.
Related: https://github.com/alphagov/government-frontend/pull/63
/cc @KushalP
> Rename publisher to content_owner within Service Manual Guide

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- formats/email_alert_signup/frontend/examples/email_alert_signup.json
- formats/email_alert_signup/publisher/details.json
Change the tag in the example to 'policies' as this is what is required
from the email alert attributes exported by the policy-publisher. The
goal of this change is to ultimately ensure that the
email-alert-frontend correctly subscribes users using tags named
'policies'.
> Update email_signup_alert example

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- formats/email_alert_signup/publisher/details.json
The contents of an email-alert-signup has changed: there is no longer a 'tags' key in the details hash - it is replaced by a new 'signup-tags' key (see https://github.com/alphagov/govuk-content-schemas/commit/1bc4952cfb021698340dbb6c29df2d25570c517e for reason why).
This change amends the JSON schema to enforce those changes.
Trello: https://trello.com/c/t42ZUP2j/434-make-signup-tags-required-in-govuk-content-schemas-email-alert-signup-and-remove-tags
> Enforce presence of signup_tags in details, remove tags in email_alert_signups

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- formats/mainstream_browse_page/publisher/details.json
- formats/topic/publisher/details.json
The `internal_name` field will be used in admin interfaces to provide context. 
In the case of topics and browse pages, it will contain "#{parent_title} / #{child_title)", so that we can populate the selectboxes without having to expand the link set (which the publishing-api doesn't do).
I'm assuming that a generic `internal_name` field can also be used in other formats to disambiguate items for use in admin interfaces. For example, the `internal_name` of organisations could be used to contain the acronym or alternative spellings, which would make them more easily findable.
@rboulton
> Add "internal_name" to topics and browse pages

- README.md
- The `bundle exec ./bin/generate_frontend_schema
formats/case_study/publisher/schema.json >
formats/case_study/frontend/schema.json` example, adapted for our
use in contacts, line errored with
"formats/contact/publisher/schema.json: no such file or directory"
because `schema.json` is a built file and therefore is only in the
`dist/` directory. Change the README example to refer to `dist/...`.
> Fix path error in the README section about frontend schema generation

- .gitignore
- These seem to be a new addition. We couldn't work out why they were
polluting our `git status` when we were generating new schemas and why
we'd never seen anything like them before, then we found this file and
determined they'd been missed when they were added.
> Gitignore *.json.publisher_v2.valid files

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/publisher/schema.json
- dist/formats/contact/publisher_v2/links.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact/frontend/examples/contact.json
- formats/contact/publisher/details.json
- formats/contact/publisher/links.json
We create the content schema for `contacts` (for how they are currently represented in the `content-store`), so that we can implement contract testing in `contacts-frontend` and `contacts-admin`. We make the change to add `organisations` to the links JSON, so that in future we can reference organisations from the content-store (currently we are passing `organisation` data in the details hash as well). 
The reason why we cannot not just switch to using the `organisations` from the `content-store` right now is that in `contacts-frontend` we require the `organisation.abbreviation` attribute, which is currently not stored for `content-store` organisations.
Improvements can be made in future PR's, removing `organisation` data from the details hash.
> Add contacts format

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/finder/frontend/examples/employment-tribunal-decisions.json
- formats/specialist_document/frontend/examples/employment-tribunal-decision.json
- formats/specialist_document/publisher/details.json
The Employment Tribunal publishes decisions that describe the outcome of a tribunal case.
Tribunal decision finders are used by public, professionals and the tribunals themselves to search for past decisions.
Published decisions form a part of case law and are used for research purposes and to prepare for current or future cases.
> Add employment tribunal decisions schema and examples

- formats/specialist_document/frontend/examples/employment-tribunal-decision.json
Fixes error caused by non-matching `tribunal_decision_categories` values in employment tribunal decisions examples.
> Change tribunal_decision_categories to match schema in examples

- formats/taxon/frontend/examples/taxon.json
We'll be using `/alpha-taxonomy` as a prefix for this format.
@mobaig
> Use real urls in taxon example

- lib/tasks/combine_publisher_schemas.rake
The handmade schema files are already checked-in in the `publisher_v2` `dist`
directory but get blown away if `dist` is regenerated from scratch. 
/cc @boffbowsh
> Copy handmade schemas to the publisher_v2 folders in `dist`

- Makefile
- lib/tasks/combine_publisher_schemas.rake
The idea is that everything in `dist/formats` should be generated.
To make sure that this is indeed the case, the `clean` step should
delete everything in that folder and the build should successfully
regenerate it.
/cc @boffbowsh
> More rigorous `clean` step

- dist/formats/email_alert_signup/publisher_v2/links.json
- dist/formats/financial_release/publisher_v2/links.json
- dist/formats/financial_releases_campaign/publisher_v2/links.json
- dist/formats/financial_releases_geoblocker/publisher_v2/links.json
- dist/formats/hmrc_manual/publisher_v2/links.json
- dist/formats/hmrc_manual_section/publisher_v2/links.json
- dist/formats/manual/publisher_v2/links.json
- dist/formats/manual_section/publisher_v2/links.json
- dist/formats/service_manual_guide/publisher_v2/links.json
- lib/tasks/combine_schemas.rake
If a schema doesn’t have a customised links.json, it should still use
the base, so we should generate it anyway.
> Build v2 links.json for all schemas

- formats/case_study/frontend/examples/case_study.json
Adds analytics specific data to enable integration style testing for the
`govuk_component` project's `analytics_meta_tags` component.
> Add analytics specific data

- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/topic/publisher_v2/links.json
- dist/formats/topic/publisher_v2/schema.json
- formats/topic/frontend/examples/service_manual_topic.json
- formats/topic/publisher/details.json
- formats/topic/publisher/links.json
After several discussions with the Finding Things team we've decided to use the existing Topics format for Service Manual Topics ([see example](http://service-manual-staging.herokuapp.com/agile-delivery/)). To make it work we need the following:
1. topic groups need an optional `description` field to describe each group ("sub-section"?)
2. reference linked items within groups using `content_id`s
3. be able to "expand" `content_id`s so that a URL and a title for the referenced content items could be displayed on a frontend page.
To implement 3 we have decided to *temporarily* use the `links -> linked_items` hash. Content ids in the links hash are automatically expanded by the content-store. This can later be used to match the expanded content items to match with their references in `groups …
> Topic enhancements to support Service Manual Topics

- formats/hmrc_manual/frontend/examples/vat-government-public-bodies.json
- formats/hmrc_manual/publisher_v2/examples/hmrc_manual_links.json
- formats/hmrc_manual_section/publisher_v2/examples/hmrc_manual_section_links.json
We're currently migrating hmrc-manuals-api to a new tagging
architecture. As part of this, we want to ensure that organisations
data is published in the links hash. Updating the hmrc manual frontend
example to support testing of this change.
> Add organisations to hmrc manual examples

- dist/formats/case_study/publisher_v2/schema.json
- dist/formats/coming_soon/publisher_v2/schema.json
- dist/formats/contact/publisher_v2/schema.json
- dist/formats/email_alert_signup/publisher_v2/schema.json
- dist/formats/financial_release/publisher_v2/schema.json
- dist/formats/financial_releases_campaign/publisher_v2/schema.json
- dist/formats/financial_releases_geoblocker/publisher_v2/schema.json
- dist/formats/financial_releases_index/publisher_v2/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/hmrc_manual/publisher_v2/schema.json
- dist/formats/hmrc_manual_section/publisher_v2/schema.json
- dist/formats/mainstream_browse_page/publisher_v2/schema.json
- dist/formats/manual/publisher_v2/schema.json
- dist/formats/manual_section/publisher_v2/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/policy/publisher_v2/schema.json
- dist/formats/service_manual_guide/publisher_v2/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- dist/formats/take_part/publisher_v2/schema.json
- dist/formats/taxon/publisher_v2/schema.json
- dist/formats/topic/publisher_v2/schema.json
- dist/formats/travel_advice/publisher_v2/schema.json
- dist/formats/travel_advice_index/publisher_v2/schema.json
- dist/formats/unpublishing/publisher_v2/schema.json
- formats/v2_metadata.json
As Applications move to V2 they will start to the use the Publishing API
as a data store. When they do this, in order to persist `update_type`
between draftings, it will need to be stored as part of the metadata.
This commit adds it to the V2 metadata but doesn't make it required, as
the `update_type` can also be provided when calling the `publish`
command on the content item.
> Add update_type to V2 metadata schema

- README.md
The method of combining schemas has changed recently with the addition
of v2 publisher schemas. Update the README to reflect the changes.
> Update README to reflect schema combiner changes.

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/publisher/schema.json
- dist/formats/contact/publisher_v2/links.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact/frontend/examples/contact.json
- formats/contact/publisher/details.json
- formats/contact/publisher/links.json
- This was being sent by contacts-admin in both places prior to
https://trello.com/c/HEB3ukuP/263-remove-organisations-from-details-hash-for-contacts.
We only need it in the one place - the links hash - as that's the
convention now. It works as it is - contacts currently uses
organisations from the links hash, but we should tidy up here.
The build is failing on contacts-admin because of https://github.com/alphagov/contacts-admin/pull/224 not being on master yet. Once that's merged and the build here is rerun, this _should_ go green.
Edit: That PR is merged, so this has indeed gone green. :green_heart:
> Contacts: Put `organisation` in the links hash, not the details hash

- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/publisher/schema.json
- dist/formats/hmrc_manual_section/publisher_v2/schema.json
- formats/hmrc_manual_section/frontend/examples/vatgpb1000.json
- formats/hmrc_manual_section/publisher/details.json
The hmrc-manuals-api is being updated to publish organisation data in the
links hash rather than the details hash, as per current convention for
documents across GOVUK. This change drops details>organisations as a
required attribute. Cleanup of details>organisations in the examples
will follow after further updates to the hmrc-manuals-api.
> Remove details>organisations from required attributes in hmrc manuals

- dist/formats/financial_releases_success/frontend/schema.json
- dist/formats/financial_releases_success/publisher/schema.json
- dist/formats/financial_releases_success/publisher_v2/links.json
- dist/formats/financial_releases_success/publisher_v2/schema.json
- formats/financial_releases_geoblocker/frontend/examples/financial_releases_not_permitted.json
- formats/financial_releases_success/frontend/examples/financial_releases_success.json
- formats/financial_releases_success/publisher/details.json
Success page renders when email address successfully submitted to register interest in campaign
Error page renders when any country other than the UK selected on geoblocker page
> Add content-schemas for financial-release sucess and error pages

- dist/formats/statistics_announcement/frontend/schema.json
- dist/formats/statistics_announcement/publisher/schema.json
- dist/formats/statistics_announcement/publisher_v2/links.json
- formats/statistics_announcement/frontend/examples/cancelled_official_statistics.json
- formats/statistics_announcement/frontend/examples/national_statistics.json
- formats/statistics_announcement/frontend/examples/official_statistics.json
- formats/statistics_announcement/frontend/examples/release_date_changed.json
- formats/statistics_announcement/publisher/links.json
This preserves consistency as statistic announcements relate to topics
rather than policy areas.
> Rename `StatisticAnnouncement#policy_areas` to `topics`

- dist/formats/statistics_announcement/frontend/schema.json
- dist/formats/statistics_announcement/publisher/schema.json
- dist/formats/statistics_announcement/publisher_v2/links.json
- formats/statistics_announcement/frontend/examples/cancelled_official_statistics.json
- formats/statistics_announcement/frontend/examples/national_statistics.json
- formats/statistics_announcement/frontend/examples/official_statistics.json
- formats/statistics_announcement/frontend/examples/release_date_changed.json
- formats/statistics_announcement/publisher/links.json
Statistics announcement pages currently link to a list of associated 'Topics'. This should remain the case but to preserve consistency in the backend and in light of the ongoing work around renaming `SpecialistSector`, `Topic` and `PolicyArea` the use of `policy_area` in the schema would seem to be the best approach.
> Rename `topics` to `policy_areas` in `statistics_announcement` schema

- Rakefile
- lib/tasks/validate.rake
I made a mistake whilst modifying a schema. It was combined successfully and
all the tests passed. but it was only when I added an example that the schema
was validated and I realised the problem. The error was not descriptive and it took time for me to realise the problem was actually in the schema, not the example. Let's shorten the feedback loop and
make it an explicit step.
> Validate schemas explicitly

- Gemfile
- Gemfile.lock
Bump to version 0.0.4, so that dummy content store only shows front-end examples.
https://github.com/alphagov/govuk-dummy_content_store/pull/4
> Bump dummy content store

- dist/formats/manual/frontend/schema.json
- dist/formats/manual/publisher/schema.json
- dist/formats/manual/publisher_v2/links.json
- formats/manual/publisher/links.json
In order to port Manuals to V2, sections need to be supplied as part of
the `links` hash. This commit updates the schema to allow that to
happen.
> Add sections to Manual links

- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/publisher/schema.json
- dist/formats/manual_section/publisher_v2/links.json
- formats/manual_section/publisher/links.json
In order to port Manual Sections to V2, the relationship to the `manual`
needs to be added to the schema. This commit adds it to the `links`
hash.
> Add Manuals to Manual Section links

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- formats/placeholder/frontend/examples/battle-of-the-somme-centenary-commemorations.json
- formats/placeholder/frontend/examples/ebola-virus-government-response.json
- formats/placeholder/publisher/details.json
We can't migrate topical events yet, because they are complex.
Topical event about pages can be migrated, but they need the end_date of the
topical event they are a part of in order to render the page.
The examples provide the topical events for the examples of topical event about
pages.
> Add fields for topical event placeholders

- formats/travel_advice/frontend/examples/alt-country.json
This is a feature in the travel advice format that FCO publishers don’t appear to be using at the moment. However they could begin using it and it would render a block on the front-end, so an appropriate example should be included.
cc @dsingleton
> Include alert_status in travel advice example

- formats/financial_release/publisher_v2/examples/financial_release.json
- formats/financial_releases_campaign/publisher_v2/examples/financial_releases_campaign.json
- formats/financial_releases_geoblocker/publisher_v2/examples/financial_releases_campaign_geoblocker.json
- formats/financial_releases_index/publisher_v2/examples/financial_releases_index.json
- formats/financial_releases_index/publisher_v2/examples/financial_releases_index_links.json
- formats/financial_releases_success/publisher_v2/examples/financial_releases_success.json
Adds publisher v2 examples for email-campaign formats.
Part of [this story](https://trello.com/c/QOevhBRK/114-114-refactor-content-store-specs)
> Add publisher v2 examples for email-campaign

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- dist/formats/service_manual_guide/publisher_v2/links.json
- dist/formats/service_manual_guide/publisher_v2/schema.json
- formats/service_manual_guide/frontend/examples/basic_with_related_discussions.json
- formats/service_manual_guide/frontend/examples/service_manual_guide_community.json
- formats/service_manual_guide/publisher/details.json
- formats/service_manual_guide/publisher/links.json
- formats/service_manual_guide/publisher_v2/examples/service_manual_guide.json
- formats/service_manual_guide/publisher_v2/examples/service_manual_guide_links.json
The pages which represent communities who curate guides now exist. Before we had a fixed href and title for the reference from the guide to the relevant community but now we can use content_ids.
We keep the content_owner defintion while they still exist in the content store but they are no longer required. Once all items have been republished we can lose the definition.
This is a reincarnation of https://github.com/alphagov/govuk-content-schemas/pull/219
> Move content_owner to links for service_manual_guide

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/email_alert_signup/publisher_v2/schema.json
- formats/email_alert_signup/publisher/details.json
Relates to https://trello.com/c/oqGCU2XP/525-add-email-signup-links-to-travel-advice-on-frontend
> Add countries to the list of valid email_alert_types

- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/policy/publisher/details.json
An internal name for admin interfaces. Includes parent.
> Add "internal_name" to policy details.

- formats/html_publication/frontend/examples/published.json
- formats/html_publication/frontend/examples/updated.json
These examples had duplicate `schema` and `document_type` fields
> Remove duplicate fields

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- dist/formats/service_manual_guide/publisher_v2/schema.json
- dist/formats/service_manual_topic/frontend/schema.json
- dist/formats/service_manual_topic/publisher/schema.json
- dist/formats/service_manual_topic/publisher_v2/schema.json
- formats/service_manual_guide/publisher/details.json
- formats/service_manual_topic/publisher/details.json
Withdrawn pages simply have an extra withdraw reason displayed at the
top.
> Add withdrawn_notice{explanation, withdrawn_at} to service manual guides and topics

- formats/html_publication/frontend/examples/arabic_translation.json
Whitehall Publisher doesn't track the relationships between an HTML
publication and its translation, and there isn't any navigation
for users to travel between these translations.
/cc @benlovell
> Remove available translation block from HTML pub example

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/email_alert_signup/publisher_v2/schema.json
- formats/email_alert_signup/frontend/examples/policy_email_alert_signup.json
- formats/email_alert_signup/frontend/examples/travel_advice_country_email_alert_signup.json
- formats/email_alert_signup/frontend/examples/travel_advice_index_email_alert_signup.json
- formats/email_alert_signup/publisher/details.json
- formats/email_alert_signup/publisher_v2/examples/email_alert_signup.json
**We will merge the pull requests ourselves in the Publishing Platform team when everyone's happy.**
https://trello.com/c/oqGCU2XP/525-add-email-signup-links-to-travel-advice-on-frontend
We've been migrating travel advice over to use the new email-alert-frontend workflow rather than the old pagewatch workflow.
Whilst doing this work, we noticed that policy publisher passes through subscriber list information as implicit links on the signup content item (which should really be reserved for more general associations with other content items). After talking with @tijmenb and @mobaig in Finding Things we concluded that the details hash is the best place for that information.
Therefore, this work consists of four parts:
1) An update to travel advice publisher to create the new email alert …
> Update schemas to use the new subscriber_list details format

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- formats/html_publication/frontend/examples/published.json
- formats/placeholder/publisher/details.json
Whitehall is being updated to stop publishing crests with the `custom` and `no-identity` values, and instead will publish `null`.
This change updates the placeholder format to be compatible, and also one of the html_publication examples to conform.
This will fix an issue in `government-frontend`, which is displaying the "Environment Agency" crest incorrectly.
**Depends on this related PR**: https://github.com/alphagov/whitehall/pull/2527
Relevant Trello ticket:
https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large
> Update placeholder format logo.crest property.

- dist/formats/service_manual_topic/frontend/schema.json
- dist/formats/service_manual_topic/publisher/schema.json
- dist/formats/service_manual_topic/publisher_v2/links.json
- formats/service_manual_topic/frontend/examples/service_manual_topic.json
- formats/service_manual_topic/publisher/links.json
- formats/service_manual_topic/publisher_v2/examples/service_manual_topic_links.json
The goal is to list the communities related to the guides included in a topic in the sidebar of a service manual topic page. We are calling them content_owners because that is the pattern set out by service-manual-guide.
https://trello.com/c/rZlsL4Am/152-add-communities-sidebar-to-the-topic-pages
> Add content_owners to service-manual-topic format

- formats/service_manual_guide/frontend/examples/with_change_history.json
It didn't include the new optional reason_for_change in change history.
> Update frontend example for service manual guide

- README.md
I was caught off-guard by the fact that the main rake task decorates the schemas defined in `formats/` with additional fields.
I wrote this bit of documentation based on my current understanding. Any suggestions on how to improve it are welcome.
> Write documentation for magic fields.

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/finder/frontend/examples/utaac-decisions.json
- formats/specialist_document/frontend/examples/utaac-decision.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher/document_types.json
The Upper Tribunal Administrative Appeals Chamber (UTAAC) publishes decisions that describe the outcome of a tribunal case.
Tribunal decision finders are used by public, professionals and the tribunals themselves to search for past decisions.
Published decisions form a part of case law and are used for research purposes and to prepare for current or future cases.
> Add administrative appeals tribunal decisions schema and examples

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- formats/detailed_guide/frontend/examples/detailed_guide.json
- formats/detailed_guide/publisher/details.json
- formats/detailed_guide/publisher/links.json
This defines the detailed guide links and details.
Only one basic example is defined so far. Suggestions (or better yet, `slug`s) are welcome with examples of other guides which feature particular edge cases that we have not covered.
Relevant Trello ticket:
https://trello.com/c/HyUyYqDu/314-6-detailed-guides-migration-content-schema-and-example-large
cc @binaryberry @tijmenb @mgrassotti
> Add `detailed_guide` definition and example.

- dist/formats/travel_advice/frontend/schema.json
- dist/formats/travel_advice/publisher/schema.json
- dist/formats/travel_advice/publisher_v2/schema.json
- dist/formats/travel_advice_index/frontend/schema.json
- dist/formats/travel_advice_index/publisher/schema.json
- dist/formats/travel_advice_index/publisher_v2/schema.json
- formats/travel_advice/frontend/examples/alt-country.json
- formats/travel_advice/frontend/examples/full-country.json
- formats/travel_advice/frontend/examples/no-parts.json
- formats/travel_advice/publisher/details.json
- formats/travel_advice/publisher_v2/examples/travel_advice.json
- formats/travel_advice_index/frontend/examples/index.json
- formats/travel_advice_index/publisher/details.json
- formats/travel_advice_index/publisher_v2/examples/travel_advice_index.json
https://trello.com/c/Io2JYTFv/27-ensure-request-id-is-available-to-multipage-frontend-and-frontend-apps
In order to trace the `request_id` thoroughly for travel advice content updates we will need to persist it and render it. The [request id will come from the load balancer](https://github.com/alphagov/govuk-puppet/pull/4320/commits/fdfbc827bf6d39e32dc4227c95fd01633b1ed582) and be [added to worker jobs](https://github.com/alphagov/travel-advice-publisher/pull/139/commits/e31ed8a3f56920fe973346547f08698d5cf300af), it will also flow through the publishing pipeline and be present in the page source of rendered content.
> Add request_id to travel advice formats

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- dist/formats/service_manual_guide/publisher_v2/schema.json
- formats/service_manual_guide/frontend/examples/point_page.json
- formats/service_manual_guide/publisher/details.json
- formats/service_manual_guide/publisher_v2/examples/point_page.json
We are extending service_manual_guide to also handle the "points page" in the service manual. A points page represents one of the points in the service standard. The design of the points page requires a lede just after the title. Because these lede / standfirst sections are fairly common across GOV.UK we think it is acceptable to give this to the other two pages that use this format, the guide page and the guide community page.
> Add summary to service_manual_guide

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/case_study/publisher_v2/links.json
- formats/case_study/frontend/examples/archived.json
- formats/case_study/frontend/examples/case_study.json
- formats/case_study/publisher/links.json
- formats/case_study/publisher_v2/examples/case_study_links.json
The format has been removed, and all data deleted.
Government frontend no longer consumes these: 
https://github.com/alphagov/government-frontend/commit/9b35ecefe0e086fc687e311797152bd7be478f7c
Whitehall no longer publishes:
https://github.com/alphagov/whitehall/pull/2246/commits/fb66f4240d1e5f72267cf3a15cb0ef7223b269ea
Part of:
https://trello.com/c/AtYGioxe/321-worldwide-priorities-deleting-the-format-medium
Do we need these schemas to help us delete the existing data from content-store?
> Remove worldwide priorities from schemas

- dist/formats/service_manual_topic/frontend/schema.json
- dist/formats/service_manual_topic/publisher/schema.json
- dist/formats/service_manual_topic/publisher_v2/schema.json
- formats/service_manual_topic/frontend/examples/service_manual_topic.json
- formats/service_manual_topic/frontend/examples/service_manual_topic_collapsed.json
- formats/service_manual_topic/publisher/details.json
- formats/service_manual_topic/publisher_v2/examples/service_manual_topic.json
The service_manual_topic has multiple sections which are normally collapsed. Sometimes there aren't enough sections or items within a section to justify collapsing and it appears there aren't a set of rules that can be applied which will let the frontend decide for itself. Instead we are adding this boolean which the publisher will set so a pair of human eyes can decide whether it should be collapsed or expanded.
If the attribute is false or missing then the default behaviour will be that it is expanded.
> Service manual topic expanded by default

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- formats/detailed_guide/publisher/links.json
This field is used by whitehall when rendering attachments. When an
attachment isn't accessible, a link to an alternative format provider is
displayed to the user.
Since we publish the fully rendered body through the content store,
including the aforementioned accessibility notice, this link isn't
necessary or useful.
> Remove alternative_format_provider_organisation detailed guide link.

- formats/publication/frontend/examples/political_publication.json
- formats/publication/frontend/examples/publication.json
- formats/publication/frontend/examples/withdrawn_publication.json
All publications use the schema or format “publication”, but have a required publication type – we can use `document_type` for this, as specified in RFC 41:
https://gov-uk.atlassian.net/wiki/pages/viewpage.action?spaceKey=GOVUK&title=RFC+41%3A+Separate+document+type+from+format
> We will deprecate the current format field, and replace it with two new fields:
> schema_name - determines which file in govuk-content-schemas is used to validate the item.
> document_type - used for frontend display and for filtering in publishing apps “
(Although, in the case of publications, all document types look exactly the same – the only difference being the context string used in their title component. Semantics basically.)
> Use document_type for "publication type"

- dist/formats/publication/frontend/schema.json
- dist/formats/publication/publisher/schema.json
- dist/formats/publication/publisher_v2/schema.json
- formats/publication/frontend/examples/publication.json
- formats/publication/frontend/examples/statistics_publication.json
- formats/publication/publisher/details.json
* Add national applicability to publications
* Include examples of topical events and ministers in links, allowing frontend to test against these
* Include statistics example, which includes national statistics document type (for testing logos) and related statistical data sets
> Add national applicability to publications, add further publication examples

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/frontend/examples/aaib-reports.json
- formats/specialist_document/frontend/examples/asylum-support-decision.json
- formats/specialist_document/frontend/examples/cma-cases.json
- formats/specialist_document/frontend/examples/countryside-stewardship-grants.json
- formats/specialist_document/frontend/examples/drug-device-alerts.json
- formats/specialist_document/frontend/examples/drug-safety-update.json
- formats/specialist_document/frontend/examples/employment-appeal-tribunal-decision.json
- formats/specialist_document/frontend/examples/employment-tribunal-decision.json
- formats/specialist_document/frontend/examples/european-structural-investment-funds.json
- formats/specialist_document/frontend/examples/international-development-funding.json
- formats/specialist_document/frontend/examples/maib-reports.json
- formats/specialist_document/frontend/examples/raib-reports.json
- formats/specialist_document/frontend/examples/tax-tribunal-decision.json
- formats/specialist_document/frontend/examples/utaac-decision.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher_v2/examples/specialist_document.json
- Add max_cache_time for specialist-document format (this is the same level as Travel Advice Publisher as agreed with infrastructure.);
- [Trello Card](https://trello.com/c/WGlWkWT5/70-reduce-cache-on-specialist-publisher-medium)
> Add max_cache_time field to specialist-document format

- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/publisher/schema.json
- dist/formats/html_publication/publisher_v2/links.json
- formats/html_publication/publisher/links.json
These are provided by `base_links`, this is duplication – if one of these was changed (either base or the one in links) it might have unexpected results.
> Remove organisations and parent from HTML publications `links.json`

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/case_study/publisher_v2/links.json
- dist/formats/case_study/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/publication/publisher/schema.json
- dist/formats/publication/publisher_v2/links.json
- formats/case_study/publisher/details.json
- formats/case_study/publisher/links.json
- formats/detailed_guide/publisher/details.json
- formats/publication/publisher/links.json
Currently, there are three types of organisations stored in the publishing-api database:
- lead organisations
- organisations
- supporting organisations
Where: organisations = lead organisations + supporting organisations
GOV.UK publishing apps do not send to the publishing-api the same organisation types consistently. We are going to modify all applications to send at least the organisations content ids in the links hash and the "emphasised_organisations" in the details hash. 
Frontend applications will then decide what and how to display the organisations by reading the details and links hashes of a piece of content. 
The `emphasised_organisations` in details hash will allow frontend applications to decide the order in which to display organisations. (emphasised_organisations will go …
> Add `emphasised_organisations` to details hash

- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/policy/publisher/details.json
This uses `lead_organisations` in the same way as Whitehall content.
Follow up to https://github.com/alphagov/govuk-content-schemas/pull/306.
> Add `emphasised_organisations` to policy format

- dist/formats/fatality_notice/frontend/schema.json
- dist/formats/fatality_notice/publisher/schema.json
- dist/formats/fatality_notice/publisher_v2/links.json
- dist/formats/fatality_notice/publisher_v2/schema.json
- formats/fatality_notice/frontend/examples/fatality_notice.json
- formats/fatality_notice/publisher/details.json
- formats/fatality_notice/publisher/links.json
Details:
* Body is required
* First public at is required
* Fatality Notices can be Political and uses history mode
Links:
* Fields of operation are required with at least one item,
small dataset so mostly going to be one.
* Format uses policy areas which is provided by base links
* Organisations are not required and are provided by base links
Whitehall has 'Roll call info' on the fatality notice model
but this is used by fields of operations pages
and not in the format itself.
The example used here is fake due to the sensitive nature of the copy.
Note that Withdraw notices feature is omitted intentionally, will update with a separate PR.
Paired with @fofr 🙊 
Live example:
https://www.gov.uk/government/fatalities/flight-lieutenants-alan-scott-and-geraint-roberts-have-died
Associated …
> Add fatality notice format

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/case_study/publisher_v2/links.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/publisher/schema.json
- dist/formats/publication/publisher_v2/links.json
- formats/case_study/publisher/links.json
- formats/detailed_guide/publisher/links.json
- formats/publication/publisher/links.json
We're getting rid of lead and supporting organisations.
This commit is to make sure that they're optional in our schemas.
Another piece of work to completely get rid of them will come as soon as publishing applications will have been updated to stop publishing those types of organisation.
ticket: https://trello.com/c/us3MI1n9/602-fix-organisation-tagging
> Make lead_organisations optional

- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/publisher/schema.json
- dist/formats/document_collection/publisher_v2/links.json
- dist/formats/document_collection/publisher_v2/schema.json
- formats/document_collection/frontend/examples/document_collection.json
- formats/document_collection/frontend/examples/document_collection_with_body.json
- formats/document_collection/publisher/details.json
- formats/document_collection/publisher/links.json
- formats/publication/frontend/examples/political_publication.json
Details:
* Body is optional for collections
* First public at is required like other editioned content
* A document collection must have an ordered list of groups
* Each group must have a title and an ordered list of documents, the group may have some body copy
* Collections can be political
* Collections can be withdrawn
* Include tags – these are not really used except for emails, see #292 for why they weren't removed from other formats
Links:
* Add documents GUID list, make this a required field
* Whitehall marks "policy areas" as being required in the editor, but content schemas say this is "largely deprecated", so it has been intentionally left out. (Policy areas are included by base links)
* Add topical events
* Lead organisations are also required, we've changed the pattern for …
> Add document_collection schema

- formats/document_collection/frontend/examples/document_collection.json
Any format can be withdrawn and the withdrawn_notice is now a top level property. It's duplicated in the details hash for now to continue to support frontend expectations but it should also be present in examples metadata.
> Add toplevel withdrawn notice to document collection example

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- dist/formats/service_manual_guide/publisher_v2/schema.json
- formats/service_manual_guide/frontend/examples/service_manual_guide.json
- formats/service_manual_guide/frontend/examples/service_manual_guide_community.json
- formats/service_manual_guide/frontend/examples/with_change_history.json
- formats/service_manual_guide/publisher/details.json
- formats/service_manual_guide/publisher_v2/examples/service_manual_guide.json
- formats/service_manual_guide/publisher_v2/examples/with_change_history.json
Removes `related_discussion` which is no longer used and `content_owner` which has been moved to the links.
Related frontend PR: https://github.com/alphagov/service-manual-frontend/pull/20
> Remove unused fields for service manual guide

- deploy.sh
This is needed so content store can validate its
output against the frontend schemas.
> Add content store servers to deploy.

- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- dist/formats/service_manual_guide/publisher_v2/links.json
- formats/service_manual_guide/frontend/examples/service_manual_guide.json
- formats/service_manual_guide/frontend/examples/service_manual_guide_community.json
- formats/service_manual_guide/frontend/examples/with_change_history.json
- formats/service_manual_guide/publisher/links.json
- formats/service_manual_guide/publisher_v2/examples/service_manual_guide_links.json
'topics' is already a reserved field and is being renamed to 'service_manual_topics'.
> Rename service manual links topics

- README.md
- dist/formats/contact/frontend/schema.json
- dist/formats/contact/publisher/schema.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact/publisher/details.json
- formats/contact/publisher_v2/examples/whitehall-contact.json
- formats/contact/publisher_v2/metadata.json
- lib/tasks/combine_schemas.rake
- spec/tasks/combine_schema_spec.rb
https://trello.com/c/JxKRVn6c/731-export-whitehall-contacts-to-publishing-api-medium
Whitehall contacts are pretty similar to those from the contacts app, a couple of fields are needed to accommodate Whitehall contacts data.
The significant change here is to allow formats to provide custom metadata, this feels a bit strange as metadata should be common across all formats, however the publishing API allows pathless content for specific formats and I've attempted to provide a mechanism for this here. Perhaps there's a better solution?
The description field is no a longer required field, [this is enforced by the contacts-admin application](https://github.com/alphagov/contacts-admin/blob/master/app/models/contact.rb#L28) as it's not necessary for Whitehall.
> Adapt contacts to whitehall model

- Gemfile
- Gemfile.lock
In order to use the new fall back to live feature.
> Update the dummy-content-store gem version

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/publisher/schema.json
- dist/formats/finder_email_signup/publisher_v2/links.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup/frontend/examples/cma-cases-email-signup.json
- formats/finder_email_signup/frontend/examples/raib-report-email-signup.json
- formats/finder_email_signup/publisher/details.json
- formats/finder_email_signup/publisher/links.json
- formats/finder_email_signup/publisher_v2/examples/finder_email_signup.json
- formats/finder_email_signup/publisher_v2/examples/finder_email_signup_links.json
We've retroactively added a schema for finder_email_signup,
which are published via a rake task on specialist-publisher
[Trello Card](https://trello.com/c/HnpJ2PQf/147-create-missing-schema-for-finder-email-signup-medium)
> Add finder_email_signup_schema

- README.md
- docs/adding-a-new-format.md
- docs/changing-a-format.md
- docs/deployment.md
Move the information in to one file, and explicitly state that deployments can
be done as soon as changes are available to deploy.
Trello: https://trello.com/c/0ybQOynQ/733-process-for-deploying-schemas-to-production
> Add more documentation on deployment

- formats/detailed_guide/frontend/examples/translated_detailed_guide.json
Needed by government-frontend to run an integration test on whether the available translations are successfully displayed.
> Add translated detailed guide format example

- dist/message_queue.json
- formats/message_queue_base.json
- lib/govuk_content_schemas/message_queue_schema_generator.rb
- lib/tasks/combine_schemas.rake
- spec/lib/message_queue_schema_generator_spec.rb
- spec/support/schema_builder_helpers.rb
- spec/tasks/combine_schema_spec.rb
Trello ticket: https://trello.com/c/teMFb0iD/734-content-schemas-for-content-on-message-queue
The publishing api sends JSON documents out on a "message queue". These JSON
documents include a representation of a content item. This new schema aims to
describe these JSON documents, as they are generated currently by the
publishing api.
The schema should accept any current output of the publishing api, but is
incomplete in many areas (e.g. loose validation for expanded_links), and so is
not very useful for consumers of the message queue in terms of documentation of
what can be expected.
Originally I did set out to make a schema per format as is done for the
publisher and frontend schemas, but ran in to issues with the behavior of the
schema combiner, particularly with regard to the mutual …
> Add a message queue schema

- dist/formats/mainstream_browse_page/frontend/schema.json
- dist/formats/mainstream_browse_page/publisher/schema.json
- dist/formats/mainstream_browse_page/publisher_v2/schema.json
- formats/mainstream_browse_page/frontend/examples/top_level_page.json
- formats/mainstream_browse_page/frontend/examples/top_level_page_with_child_pages_in_curated_order.json
- formats/mainstream_browse_page/publisher/details.json
content-store does not retain the order of the items that are sent in the links
hash, therefore in order to allow custom 2nd level browse pages ordering we
have to read the links order from the details hash.
paired on it with @rubenarakelyan
> Add second_level_ordering to MainsteamBrowsePage

- dist/formats/gone/publisher_v2/schema.json
- dist/formats/redirect/publisher/schema.json
- formats/gone/publisher_v2/schema.json
- formats/redirect/publisher/schema.json
There are a couple of apps still sending `format` to the publishing-api. We've created PRs for these to send `document_type` and `schema_name` but these can't be merged until those attributes are allowed everywhere.
After those PRs are merged `format` will be removed here, and `document_type` & `schema_name` will become required.
Part of: https://github.com/alphagov/govuk-content-schemas/pull/348
> Allow document_type & schema_name for gone

- dist/formats/gone/publisher/schema.json
- formats/gone/publisher/schema.json
This format is a deprecated V1 format, but it still needs to be updated so that the examples will be valid with the new fields.
Follow up to: https://github.com/alphagov/govuk-content-schemas/pull/349
Needed for: https://github.com/alphagov/govuk-content-schemas/pull/351 to pass.
Part of: https://github.com/alphagov/govuk-content-schemas/pull/348
> Allow document_type & schema_name in old `gone`

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/publisher/schema.json
- dist/formats/taxon/publisher_v2/links.json
- formats/taxon/frontend/examples/taxon.json
- formats/taxon/publisher/links.json
We would like to allow taxons to have multiple taxon parents associated. Rather than changing the existing `parent` link (which is used for the breadcrumbs and only allows one association), we created a new link type called `taxon_parents`. This should allow a number of parents on any given taxon.
More details here: https://trello.com/c/nImPlcNS/19-allow-taxons-to-have-multiple-parents
> Add taxon parents link to taxon

- formats/service_manual_topic/frontend/examples/service_manual_topic_without_sections.json
Some topics exist that have exactly one group (section) which has neither a name nor a description. We need to test that as a special case in the front-end, so add an example we can use.
> Add an example of a topic that does not use sections

- deploy.sh
The content store validates presented content against the relevant frontend schema regardless of whether it's a draft or live content store. So copy schemas to the draft stores too.
> Deploy schemas to draft content store

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- dist/message_queue.json
- formats/specialist_document/publisher/details.json
When adding an attachment to a document, it sends the
document to the Publishing API with the attachment's
metadata. If the user hasn't chosen an update_type for
the document, we intend to set it to 'minor' and set
this 'temporary_update_type' field to true. We can then
present a choice of update types to the user rather
than pre-selecting 'minor' for them.
Relates to:
https://trello.com/c/oxxALgmy/187-changes-to-update-type-for-raib-reports
> Add 'temporary_update_type' to specialist documents

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/publisher/schema.json
- dist/formats/taxon/publisher_v2/links.json
- formats/taxon/frontend/examples/taxon.json
- formats/taxon/publisher/links.json
This gives a bit more insight as to what this field is. It is intended to
have links to multiple parents of a taxon that are taxon themselves.
This change is a follow-up from comments on https://github.com/alphagov/collections-publisher/pull/210
> Renaming `taxon_parents` to `parent_taxons`

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- dist/message_queue.json
- formats/finder/frontend/examples/raib-reports.json
- formats/specialist_document/publisher/details.json
This has been requested by RAIB
Trello: https://trello.com/c/e4i1jjw1/31-add-new-raib-report-type
> Add safety digests as a RAIB report type

- dist/formats/special_route/publisher_v2/schema.json
- formats/special_route/publisher_v2/schema.json
Currently this schema only accepts format; some applications have been
migrated to use schema_name/document_type. For now, support both,
without requiring either of them ; when no apps are sending format this
can be removed and the other two added to the required fields.
> Add schema_name and document_type to special_route

- dist/formats/service_manual_service_standard/frontend/schema.json
- dist/formats/service_manual_service_standard/publisher/schema.json
- dist/formats/service_manual_service_standard/publisher_v2/links.json
- dist/formats/service_manual_service_standard/publisher_v2/schema.json
- dist/message_queue.json
- formats/service_manual_service_standard/frontend/examples/service_manual_service_standard.json
- formats/service_manual_service_standard/publisher/details.json
- formats/service_manual_service_standard/publisher/links.json
- formats/service_manual_service_standard/publisher_v2/examples/service_manual_service_standard.json
This PR updates the `service_manual_service_standard` schema and examples to use link expansion.
Currently it doesn't seem possible to have a frontend example of a parent/child relationship which has been link-expanded that matches it's frontend schema.
It seems the definitions of each link type are overwritten for the frontend schemas so that they are "#/definitions/frontend_links". https://github.com/alphagov/govuk-content-schemas/blob/b283419dc1f43d69396e88fdd559ea2f4ce1889b/lib/govuk_content_schemas/frontend_schema_generator.rb#L81
The "#/definitions/frontend_links" definition mostly matches an expanded link but falls down when it gets into the links of the expanded link where it expects every link type to be a "#/definitions/guid_list".
Here are a couple of heavily redacted examples …
> Use link expansion for the Service Standard

- formats/service_manual_guide/publisher_v2/examples/point_page.json
- formats/service_manual_guide/publisher_v2/examples/service_manual_guide.json
- formats/service_manual_topic/publisher_v2/examples/service_manual_topic.json
Service manual guides and topics are rendered by service-manual-frontend, not government-frontend.
> Correct rendering_app in examples for service manual guides and topics

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- dist/message_queue.json
- formats/specialist_document/frontend/examples/aaib-reports.json
- formats/specialist_document/frontend/examples/asylum-support-decision.json
- formats/specialist_document/frontend/examples/countryside-stewardship-grants.json
- formats/specialist_document/frontend/examples/drug-device-alerts.json
- formats/specialist_document/frontend/examples/drug-safety-update.json
- formats/specialist_document/frontend/examples/employment-appeal-tribunal-decision.json
- formats/specialist_document/frontend/examples/employment-tribunal-decision.json
- formats/specialist_document/frontend/examples/european-structural-investment-funds.json
- formats/specialist_document/frontend/examples/international-development-funding.json
- formats/specialist_document/frontend/examples/maib-reports.json
- formats/specialist_document/frontend/examples/raib-reports.json
- formats/specialist_document/frontend/examples/tax-tribunal-decision.json
- formats/specialist_document/frontend/examples/utaac-decision.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher_v2/examples/dfid_research_output.json
- formats/specialist_document/publisher_v2/examples/specialist_document.json
https://trello.com/c/Y0ncSoTO/258-clean-up-remove-document-type-from-pub-api-metadata-payload
Remove duplicate `document_type` property from the `specialist_document` schema metadata.
To do this we have to [be explicit in the enums for the `tribunal_decision_category` property](https://github.com/alphagov/govuk-content-schemas/commit/8212a1e3551017fd3c3dbb0bf52b399f38869f56#diff-1a705374a0f9ac97b29928d07d04b0bfR182) to satisfy [the `oneOf` clause for document specific metadata](https://github.com/alphagov/govuk-content-schemas/blob/master/formats/specialist_document/publisher/details.json#L41).
Needs https://github.com/alphagov/specialist-publisher-rebuild/pull/891 to build correctly.
https://github.com/alphagov/specialist-publisher/pull/737 added for completeness.
> Remove document type from specialist publisher metadata

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/publisher/schema.json
- dist/formats/taxon/publisher_v2/schema.json
- dist/message_queue.json
- formats/taxon/publisher/details.json
Also includes minor amendment to description field explanation - a taxon
internal name may not necessarily include the parent.
> Add notes_for_editors to taxon details hash

- dist/formats/contact/publisher_v2/schema.json
- formats/contact/publisher_v2/metadata.json
It doesn't make sense for it to be required, and meanwhile it's causing validation errors.
> Make rendering_app optional for contacts

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/publisher/schema.json
- dist/formats/email_alert_signup/publisher_v2/schema.json
- dist/formats/service_manual_guide/frontend/schema.json
- dist/formats/service_manual_guide/publisher/schema.json
- dist/formats/service_manual_guide/publisher_v2/schema.json
- dist/message_queue.json
- formats/email_alert_signup/publisher/details.json
- formats/service_manual_guide/frontend/examples/service_manual_guide.json
- formats/service_manual_guide/publisher/details.json
The email-alert-api uses the links hash within subscriber_lists as a matcher, examining new documents that get published for matching `links` and `document` types and sending emails to relevant lists.
The schema currently limits the contents of the links hash to only permit countries, which means that only links to `countries` can be subscribed to.
We are building email alerts into the service manual, allowing users to subscribe to service manual topics. Therefore we need to create email_alert_signups based on documents that link to `service_manual_topics`, so we need to allow for this in the schema.
Rather than adding `service_manual_topics` as another 'special case' this instead allows exactly one property with a alphabetical, underscored key to be provided as long as the value is an …
> Allow email alert signups to work with links other than countries

- dist/formats/service_manual_topic/frontend/schema.json
- dist/formats/service_manual_topic/publisher/schema.json
- dist/formats/service_manual_topic/publisher_v2/links.json
- formats/service_manual_topic/frontend/examples/service_manual_topic.json
- formats/service_manual_topic/publisher/links.json
- formats/service_manual_topic/publisher_v2/examples/service_manual_topic_links.json
Within the service manual we're making it possible for users to sign up for email alerts with particular service manual topics.
To do this we're creating an email_alert_signup for each topic, and associating it with the topic.
> Service manual topics now link to email alert signups

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/policy/publisher_v2/schema.json
- dist/message_queue.json
- formats/finder/frontend/examples/drug-device-alerts.json
- formats/finder/frontend/examples/drug-safety-update.json
- formats/finder/publisher/details.json
- formats/policy/frontend/examples/policy_area.json
- formats/policy/frontend/examples/policy_programme.json
- formats/policy/frontend/examples/policy_with_inapplicable_nations.json
- formats/policy/publisher/details.json
- formats/policy/publisher_v2/examples/policy.json
`details.signup_link` is a piece of technical debt from the time we didn't have the links hash, or didn't use it properly. Policy Publisher and Finder Publisher shouldn't be sending this.
> Remove "signup_link"

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/message_queue.json
- formats/placeholder/frontend/examples/battle-of-the-somme-centenary-commemorations.json
- formats/placeholder/frontend/examples/organisation.json
- formats/placeholder/publisher/details.json
The final objective is storing and retrieving them from the content-store.
Ticket: https://trello.com/c/rDKC4sLm/133-send-related-external-links-to-pub-api-from-publisher
Part of: https://trello.com/c/mOeDK914/107-epic-related-links-and-panopticon
> Add external related links to placeholders

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/publisher/details.json
This commit changes the validation of the specialist document "metadata" hash.
The fix is quite interesting, because I think we've been misunderstanding a part of the JSON Schema spec -- or at least I was.
Currently, the schema mandates that `details.metadata` in a specialist document conform to one of ~15 subschemas, each conforming to one of the specialist document types.
By using the `oneOf` keyword, we require that *exactly one* of the subschemas validates. In practice, it's perfectly possible for the metadata of an AAIB Report to be also valid for the metadata of a RAIB report.
The`anyOf` keyword actually does what we want: it will make sure that the metadata is valid against at least one schema.
The TIL is: you almost never want `oneOf`, unless you're doing something to enforce …
> Validate metadata of specialist documents correctly

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- formats/detailed_guide/frontend/examples/related_mainstream_detailed_guide.json
- formats/detailed_guide/publisher/links.json
Previously the `links` entry for related mainstream was called `related_mainstream` while the `details` entry was called `related_mainstream_content`. 
This PR names them consistently `related_mainstream_content`.
> Make DetailedGuide consistent

- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- formats/detailed_guide/frontend/examples/related_mainstream_detailed_guide.json
- formats/detailed_guide/publisher/links.json
`related_mainstream` has now been removed from the apps that depended upon it.
https://github.com/alphagov/government-frontend/pull/185
https://github.com/alphagov/whitehall/pull/2769
It was previously deprecated and can now be removed in favour of `related_mainstream_content`.
> Remove deprecated detailed guide links

- formats/finder/frontend/examples/international-development-funding.json
The country is now known as Democratic Republic of the Congo. We cannot change the slug at this point as Finding Things will need to [republish everything for it](https://github.com/alphagov/rummager/pull/700#discussion_r80919413).
> Rename Democratic Republic of Congo

- Rakefile
- bin/convert_finder_schemas
- lib/govuk_content_schemas/finder_schema_converter.rb
- lib/govuk_content_schemas/frontend_schema_generator.rb
- lib/govuk_content_schemas/schema_combiner.rb
- lib/govuk_content_schemas/utils.rb
- lib/tasks/combine_schemas.rake
- lib/tasks/validate.rake
- spec/lib/finder_schema_converter_spec.rb
- spec/lib/frontend_schema_generator_spec.rb
- spec/lib/schema_combiner_spec.rb
- spec/spec_helper.rb
- spec/support/rake.rb
- spec/support/schema_builder_helpers.rb
- spec/tasks/combine_schema_spec.rb
- spec/tasks/validate_uniqueness_of_frontend_example_base_paths_spec.rb
This applies all `govuk_lint_ruby` fixes and goes through and makes usage of double quotes consistent.
> Fixes for coding standards

- dist/formats/redirect/publisher_v2/schema.json
- formats/redirect/publisher_v2/examples/govuk-campaign-redirect.json
- formats/redirect/publisher_v2/schema.json
This PR relates to:
* alphagov/short-url-manager#62
* alphagov/publishing-api#531
This PR needs merging first:
* alphagov/govuk_schemas_gem#16
The content designers need to be able to configure short URLs for gov.uk campaigns. For example, it needs to be possible to set up a redirect from `https://www.gov.uk/campaign-slug` to `https://my-campaign-title.campaign.gov.uk`.
This PR updates the `redirect` schema to allow gov.uk campaign URLs to be the destination of redirects. The `govuk_campaign_url` regex should match any HTTPS URL where the host is a subdomain of `campaign.gov.uk`.
Demo: http://regexr.com/3eblr
```
https://               # gov.uk campaigns must be served over https
(
[a-zA-Z0-9]          # Each subdomain must start with an alphanumeric character...
(
[a-zA-Z0-9-]{0,61} # …
```
> Allow redirects to gov.uk campaign URLs

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/frontend/examples/asylum-support-decision.json
- formats/specialist_document/publisher/details.json
The asylum content schema has been amended to allow the category and
sub-category fields to support multiple options.
Associated commits in specialist-publisher-rebuild and rummager
> Amend MOJ asylum content finder

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/frontend/examples/asylum-support-decision.json
- formats/specialist_document/publisher/details.json
Reverts alphagov/govuk-content-schemas#403 as this wasn't quite ready to be merged yet (depends on https://github.com/alphagov/specialist-publisher-rebuild/pull/911)
> Revert "Amend MOJ asylum content finder"

- dist/formats/service_manual_service_standard/frontend/schema.json
- dist/formats/service_manual_service_standard/publisher/schema.json
- dist/formats/service_manual_service_standard/publisher_v2/links.json
- formats/service_manual_service_standard/publisher/links.json
The frontend schema generator now adds children to the frontend schemas only, which is a better representation of how children are used.
> Remove children from the service standard's links in publisher schemas

- formats/detailed_guide/frontend/examples/england-2014-to-2020-european-structural-and-investment-funds.json
Uses the `image` field in the details hash. Government Frontend will
render this in the top right of the page. Only one Detailed Guide uses
this feature.
> Add an example Detailed Guide with an ESIF logo

- formats/service_manual_topic/frontend/examples/service_manual_topic.json
Service manual topics will usually have the service manual homepage as a parent, so include it in the example.
The exception to this is when the topic should not be included on the list of topics on the homepage. A current use case for this is the ‘communities’ topic, which is linked separately.
> Add parent to service manual topic example

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder/publisher/details.json
We are moving the rendering app of the people page from whitehall to finder-frontend. In doing so, we are writing a JSON file to represent the new finder page. In that schema, we have to describe how are we going to filter the data for the finder page.
In rummager, we need to use the `format` so that the finder page gets populated with people (this is because the `document_type` of a person is an `edition` and the format is `person`).
Here is an example query: https://www.gov.uk/api/search.json?filter_format=person
This PR make is possible to filter data by format in finders.
Trello: https://trello.com/c/reCVyzpg/259-migrate-the-people-page-to-a-finder
> Allow format filtering on finder publisher schemas

- formats/document_collection/frontend/examples/document_collection.json
Adds missing links `topics`, `policies` and `topical_events` to `DocumentCollection` example.
mobbed by: @andrewgarner, @bevanloon, @binaryberry, @gpeng, @MatMoore, @mgrassotti, @tvararu
> Update document collection schema

- docs/deployment.md
The behaviour around schema validation has now changed to reject content
with validation failures.
> Remove incorrect note about Publishing API

- formats/document_collection/frontend/examples/document_collection_with_missing_links_documents.json
- formats/document_collection/frontend/examples/document_collection_with_no_documents.json
- formats/document_collection/frontend/examples/document_collection_with_single_missing_document.json
Add some examples to Document Collection frontend examples. This is needed so we can add  functionality to government-frontend to replicate existing functionality in Whitehall.
Mobbed on with @andrewgarner @bevanloon @gpeng @mgrassotti @Rosa-Fox
> Fix document collection scoping

- Rakefile
- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/publisher/schema.json
- dist/formats/document_collection/publisher_v2/links.json
- dist/formats/fatality_notice/frontend/schema.json
- dist/formats/fatality_notice/publisher/schema.json
- dist/formats/fatality_notice/publisher_v2/links.json
- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/publisher/schema.json
- dist/formats/finder_email_signup/publisher_v2/links.json
- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/publisher/schema.json
- dist/formats/html_publication/publisher_v2/links.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/publisher/schema.json
- dist/formats/policy/publisher_v2/links.json
- dist/formats/statistics_announcement/frontend/schema.json
- dist/formats/statistics_announcement/publisher/schema.json
- dist/formats/statistics_announcement/publisher_v2/links.json
- dist/formats/topical_event_about_page/frontend/schema.json
- dist/formats/topical_event_about_page/publisher/schema.json
- dist/formats/topical_event_about_page/publisher_v2/links.json
- formats/document_collection/publisher/links.json
- formats/fatality_notice/publisher/links.json
- formats/finder_email_signup/publisher/links.json
- formats/html_publication/publisher/links.json
- formats/policy/publisher/links.json
- formats/statistics_announcement/publisher/links.json
- formats/topical_event_about_page/publisher/links.json
- lib/tasks/validate.rake
Because we use "patch" to set links it's not possible to use `required` links. If we would, we'd never be able to validate payload to the publishing-api (like https://github.com/alphagov/publishing-api/pull/597).
cc @dougdroper
> Remove required items for links schemas 

- formats/document_collection/frontend/examples/document_collection_with_group_but_no_documents.json
- formats/document_collection/frontend/examples/document_collection_with_no_documents.json
When all linked documents are unpublished there will be no `documents` element in the `links`. This PR updates an existing example and adds a new one for the case where there are `content_id`s in the `details` groups but no `links#documents`
> Update document collection examples

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher/schema.json
- dist/formats/generic/publisher_v2/links.json
- dist/formats/generic/publisher_v2/schema.json
- formats/generic/frontend/examples/services_and_information.json
- formats/generic/publisher/details.json
- formats/generic/publisher/links.json
This commit adds a “generic” schema which includes nothing in the `details` or `links` hashes beyond what is defined in the base JSON documents.
The reason is to provide a schema for content items that do not need any information in the content-store to be rendered. (Rather than a `placeholder`, which implies that it needs but doesn't have data _yet_).
Previously, the `special_route` schema has been used for these types of pages, for example the “Find your local council” page ([code](https://github.com/alphagov/frontend/blob/e460d40b0095d6c07570aa14b884fcbdde65b7c6/lib/tasks/publishing_api.rake)). This is wrong, because `special_route` is a special kind of schema that doesn’t have a frontend representation. It was intended for the use of routing, never to be served from the content-store …
> Add generic schema

- formats/statistical_data_set/frontend/examples/statistical_data_set_with_block_attachments.json
[Trello](https://trello.com/c/3OZ36DPk/511-statistical-dataset-migration-basic-content-schema-examples-and-front-end-work-medium)
This adds an example that includes normal attachments as opposed to the
inline attachments that were included in previous examples.
Paired with @Rosa-Fox
> Add attachment Statistical Data Set example

- dist/formats/need/frontend/schema.json
- dist/formats/need/notification/schema.json
- dist/formats/need/publisher/schema.json
- dist/formats/need/publisher_v2/links.json
- dist/formats/need/publisher_v2/schema.json
- formats/need/frontend/examples/need.json
- formats/need/publisher/details.json
This is the first step of planned work to copy Needs to the
Publishing API, where they will be treated as content.
This provides the basic schema and example for Needs, and will need to be
enhanced with additional fields later on.
Paired with @issyl0 
[Trello](https://trello.com/c/Fp47fgeN/6-creating-content-schema-for-needs)
> Add need schema

- formats/statistical_data_set/frontend/examples/statistical_data_set_with_csv.json
CSV based block attachments are rendered differently to other file
formats. Instead of linking directly to the file in the `title` element,
CSV block attachments have two links within the `metadata` element;
one to "View online" and one to "Download CSV".
[Trello card ](https://trello.com/c/3OZ36DPk)
> Add Statistical Data Set example with .csv attachment

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/finder/frontend/examples/service-standard-reports.json
- formats/specialist_document/frontend/examples/service-standard-report.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher/document_types.json
Finding Things team is moving the Service Assessments & Self Certification documents from the [GDS Data blog](https://gdsdata.blog.gov.uk/all-service-assessments-and-self-certification/) into finders.
This commit adds examples of those schemas.
- Added example for finder-frontend
- Added example for specialist-frontend
Trello: https://trello.com/c/lFZnNhs4/349-create-a-service-assessment-finder
> Add schema & examples for Service Standard Reports

- Jenkinsfile
- jenkins.sh
Add Jenkins configuration file to enable pipeline builds on the Jenkins 2 CI server.
This file currently does NOT trigger any downstream builds of which depend on the content schemas. Triggers for those should be added to this file as the projects themselves are migrated to Jenkins 2.
**Once this is merged to master, we'll need to make a few manual config changes:**
Note that the Jenkins 1 build will still _run_, because we will leave the old Jenkins webhook in place. This means that the Jenkins 1 will continue to trigger all of the dependent builds until we've migrated each of them to Jenkins 2.
I think the process for updating a dependent project will then be:
1. Add a Jenkinsfile to the dependent project, but leave the old jenkins.sh in place. This will ensure that the build can …
> Add Jenkinsfile

- dist/formats/need/frontend/schema.json
- dist/formats/need/notification/schema.json
- dist/formats/need/publisher/schema.json
- dist/formats/need/publisher_v2/schema.json
- formats/need/publisher/details.json
This adds the remaining fields to the Needs content schemas, to allow to publish all Needs from the Need-API to the Publishing-API.
Relates to [this Trello card](https://trello.com/c/jlXiAdmQ/7-add-needs-to-publishing-api)
> Complete need content schema

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/publisher/details.json
The service standard reports need to have the date of when the assessment was held.
We are adding it to the metadata field to allow the editors to fill this field on Specialist Publisher and allow our visitors to read it in the document page.
Trello:
https://trello.com/c/ADPnDXsE/385-add-assessment-date-to-service-standard-specialist-document
> Add assesment_date to Service Standard Report

- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/links.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- formats/generic_with_external_related_links/frontend/examples/local_transaction.json
- formats/generic_with_external_related_links/publisher/details.json
- formats/generic_with_external_related_links/publisher/links.json
Created new `generic_with_external_related_links` schema for all the mainstream formats
used by Publisher, Smart Answers and Frontend. This is only temporary for the
purposes of removing the use of the Placeholder format. During migration we
will be breaking each format out into their own schemas and removing the
`generic_with_external_related_links` schema.
[Trello card](https://trello.com/c/sZyeX2Ul/570-preparatory-work-fix-content-item-routes-for-publisher-formats-3)
> Add generic with external related links schema

- dist/formats/speech/frontend/schema.json
- dist/formats/speech/notification/schema.json
- dist/formats/speech/publisher/schema.json
- dist/formats/speech/publisher_v2/links.json
- dist/formats/speech/publisher_v2/schema.json
- formats/speech/frontend/examples/speech-authored-article.json
- formats/speech/frontend/examples/speech-speaker-without-profile.json
- formats/speech/frontend/examples/speech-transcript.json
- formats/speech/frontend/examples/speech-written-statement-parliament.json
- formats/speech/frontend/examples/speech.json
- formats/speech/publisher/details.json
- formats/speech/publisher/links.json
* Add details and links schema for speeches
* Add examples for draft transcript, transcript, written to parliament and authored article types of speech
* Add example where speaker doesn't have a GOV.UK page (eg The Queen)
There are no known features missing from the schema.
The images are pulled from the profile of the assigned speaker. For now the frontend expects this to come from the `image` property in the details. It may in future make more sense for it to come via an image property in the links hash of the speaker – as that's the dependency.
Story: https://trello.com/c/TWsLTRzc/547-10-speech-migration-mvp-content-schema-examples-and-front-end-work
> Add speeches schema and examples

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/finder/frontend/examples/cma-cases.json
- formats/specialist_document/publisher/details.json
This has been requested by the CMA.
Trello: https://trello.com/c/60QIKF6z/393-cma-case-finder-adding-1-extra-case-type-3-extra-outcomes
> Add CMA case type and outcomes for competition disqualifications

- formats/speech/frontend/examples/speech-translated.json
Include an arabic right to left example for speeches.
Based on:
https://www.gov.uk/government/speeches/this-resolution-marks-the-beginning-of-the-end-of-the-libyan-chemical-weapons-programme.ar
Part of https://trello.com/c/TWsLTRzc/547-speech-migration-1-mvp-content-schema-examples-and-front-end-work
> Add right-to-left translated speech example

- lib/tasks/combine_schemas.rake
- lib/tasks/validate.rake
It’s not clear what’s going on when you run rake to validate and generate the schemas, so:
- Provide some output to explain what’s going on rather than exiting with no output on a successful run.
- Add descriptions to some of the important rake tasks so that they’re listed when you run rake -T
```
$ bundle exec rake
Validating source schemas... ✔︎
Combining (generating) schemas... ✔︎
Validating generated schemas... ✔︎
Checking that all frontend examples have unique base paths... ✔︎
Validating links... ✔︎
Validating examples... ✔︎
```
```
$ bundle exec rake -T
rake clean                                                      # Remove any temporary products
rake clobber                                                    # Remove any generated file
rake combine_schemas …
```
> Make schema generation and validation less obtuse

- dist/formats/service_manual_service_toolkit/frontend/schema.json
- dist/formats/service_manual_service_toolkit/notification/schema.json
- dist/formats/service_manual_service_toolkit/publisher/schema.json
- dist/formats/service_manual_service_toolkit/publisher_v2/links.json
- dist/formats/service_manual_service_toolkit/publisher_v2/schema.json
- formats/service_manual_service_toolkit/frontend/examples/service_manual_service_toolkit.json
- formats/service_manual_service_toolkit/publisher/details.json
- formats/service_manual_service_toolkit/publisher/links.json
- formats/service_manual_service_toolkit/publisher_v2/examples/service_manual_service_toolkit.json
We're building a new page as part of the service manual called the "service toolkit", which is a list of links to government products that looks [like this](https://govuk-product-page-prototypes.herokuapp.com/govuk-service-manual/index).
This adds a schema called `service_manual_service_toolkit` which will support that page.
https://trello.com/c/GHY41UJi/546-create-service-toolkit-page
> Add service toolkit format

- .dockerignore
This just ignores the most standard stuff for docker. In theory for this
repo it could probably ignore everything except `dist/*` but that seems
a bit drastic at this point.
> Basic .dockerignore file

- dist/formats/world_location_news_article/publisher/schema.json
- dist/formats/world_location_news_article/publisher_v2/links.json
The schema.json and links.json files were not up-to-date, probably because a merged PR overwrote some changes from an earlier PR.
The correct schema have been generated by running 'bundle exec rake'.
> Update generated files to fix CI build

- formats/finder_email_signup/frontend/examples/cma-cases-email-signup.json
- formats/finder_email_signup/publisher_v2/examples/finder_email_signup.json
When a new email alert subscription is created, a short name is generated describing the subscription. If enough subscription items are chosen by the user, the short name becomes longer than 255 characters, which is the GovDelivery limit for this field.
This commit tweaks the text for the finder content item examples to reflect changes made to the CMA case finder to keep the short text under 255 characters.
Trello: https://trello.com/c/KTHRa4a0/422-fix-email-alert-api-errors-when-the-email-alert-short-name-is-longer-than-255-characters
> Tweak example text for the CMA finder content item

- dist/formats/need/frontend/schema.json
- dist/formats/need/notification/schema.json
- dist/formats/need/publisher/schema.json
- dist/formats/need/publisher_v2/schema.json
- formats/need/publisher/details.json
Maslow needs to display the need_id so it must be stored in the Publishing API.
This adds it to the details - another option would have been to store it in the
need_ids array, which is in the base schema, but that's used for tagging
content items to needs, so not relevant for storing the need_id of needs
themselves.
https://trello.com/c/jlXiAdmQ/7-add-needs-to-publishing-api
> Add need id to Need details

- Jenkinsfile
Trigger the builds of several content-tagger and whitehall, to test the production version of those against the latest changes to the content schema.
This is still not the full list of dependent projects - this is just the subset which have been recently configured in puppet to handle builds of 'deployed-to-production' correctly in alphagov/govuk-puppet#5335. Other downstream builds will be migrated from Jenkins 1 once they have also
been updated in Puppet.
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration
> Configure more dependent CI builds in Jenkins 2

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup/frontend/examples/cma-cases-email-signup.json
- formats/finder_email_signup/frontend/examples/raib-report-email-signup.json
- formats/finder_email_signup/publisher/details.json
- formats/finder_email_signup/publisher_v2/examples/finder_email_signup.json
This commit adds the ability to define a separate email alert list title text which will be used when the normally generated string is too long (> 255 characters). It will be appended with a string of the form “x items”, where “x” is the number of selected topics and “items” is either the singular or plural string defined as `email_filter_name`.
Also reverts https://github.com/alphagov/govuk-content-schemas/pull/482 since this is a more comprehensive solution.
Trello: https://trello.com/c/KTHRa4a0/422-fix-email-alert-api-errors-when-the-email-alert-short-name-is-longer-than-255-characters
> Add more text options for email alerts

- Jenkinsfile
Trigger builds of email-alert-service and email-alert-frontend, to test the production version of those against the latest changes to the content schema.
> Configure dependent CI builds for email applications in Jenkins 2

- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/notification/schema.json
- dist/formats/news_article/publisher/schema.json
- dist/formats/news_article/publisher_v2/links.json
- dist/formats/news_article/publisher_v2/schema.json
- dist/formats/speech/frontend/schema.json
- dist/formats/speech/notification/schema.json
- dist/formats/speech/publisher/schema.json
- dist/formats/speech/publisher_v2/schema.json
- dist/formats/world_location_news_article/frontend/schema.json
- dist/formats/world_location_news_article/notification/schema.json
- dist/formats/world_location_news_article/publisher/schema.json
- formats/news_article/frontend/examples/news_article.json
- formats/news_article/frontend/examples/news_article_government_response.json
- formats/news_article/frontend/examples/news_article_history_mode.json
- formats/news_article/frontend/examples/news_article_news_story_translated_arabic.json
- formats/news_article/frontend/examples/news_article_press_release.json
- formats/news_article/publisher/details.json
- formats/news_article/publisher/links.json
- formats/speech/publisher/details.json
- formats/world_location_news_article/publisher/details.json
* Add schema for news article
* Add examples for news story, translated news story, press release, government response and history mode
* Remove withdrawal notice from speeches and world location news articles - new formats that haven't yet been republished, they shouldn't have withdrawal notice in details as it's provided by default
Part of:
https://trello.com/c/Jse0oAvr/575-news-article-migration-1-mvp-content-schema-examples-and-front-end-work
Goes with:
https://github.com/alphagov/government-frontend/pull/232
> Add news article schema and examples

- formats/statistics_announcement/frontend/examples/cancelled_official_statistics.json
- formats/statistics_announcement/frontend/examples/national_statistics.json
- formats/statistics_announcement/frontend/examples/official_statistics.json
- formats/statistics_announcement/frontend/examples/release_date_changed.json
The document type for these examples was updated:
https://github.com/alphagov/whitehall/pull/2783
I needed an official statistics announcement example to test:
https://github.com/alphagov/government-frontend/pull/226
> Use new document type for official and national stats announcement examples

- dist/formats/news_article/publisher/schema.json
- dist/formats/news_article/publisher_v2/schema.json
The generated schemas were out-of-sync with the source files.
I've generated up-to-date schemas using `bundle exec rake clean build`.
I suspect this was just due to the order in which #483 and #488 were merged. @fofr and @danielroseman - could you check that this fix is correct?
> Check in the up-to-date generated schemas

- Jenkinsfile
As far as I can tell, Rummager doesn't actually depend directly on the content schemas, so it doesn't need to be built to test changes to this project.
> Remove rummager from triggered CI builds

- Jenkinsfile
Prevent the expensive cross-project schema tests from running if the schemas are out of date. The build was already being (correctly) marked as a failure, but it should also stop immediately.
This should hopefully ease some of the queues on the CI server, because builds will fail fast before they kick off all the long-running downstream builds.
> Stop the Jenkins build immediately if schemas are out of date

- dist/formats/need/frontend/schema.json
- dist/formats/need/notification/schema.json
- dist/formats/need/publisher/schema.json
- dist/formats/need/publisher_v2/schema.json
- formats/need/publisher/details.json
When using these fields, Maslow currently expects to save them as
numbers, not strings.
> Change yearly_* fields to be numerical

- Jenkinsfile
Trello: https://trello.com/c/UCcCp13D/576-move-publisher-to-new-ci-infrastructure-1
In the context of moving Publisher to the new CI, we want to not rely anymore on Jenkins 1 also for schema tests.
The current PR adds Publisher to the dependentApplications list to kick off a build of it to test the schema.
> Add Publisher to the dependent applications

- Jenkinsfile
We've updated the service manual to Jenkins 2, and set up content schema
tests per the ops manual. This adds `service-manual-publisher` and
`service-manual-frontend` to the list of dependent applications in the
Jenkins config, to ensure their tests are run when the schemas change.
Relevant PRs:
- alphagov/service-manual-frontend#100
- alphagov/service-manual-publisher#379
- alphagov/govuk-puppet#5392
See also https://github.gds/gds/opsmanual/blob/master/infrastructure/testing/application-testing.md#content-schema-tests
> Add service manual to Jenkins dependent applications

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/finder/frontend/examples/business-finance-support-schemes.json
- formats/specialist_document/frontend/examples/business-finance-support-scheme.json
- formats/specialist_document/publisher/details.json
- formats/specialist_document/publisher/document_types.json
This commit adds schemas and examples for the migrated business finance support schemes.
Trello: https://trello.com/c/UHsavPI5/485-create-a-new-specialist-document-type-for-business-support-scheme
> Add schema for business support schemes

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- formats/corporate_information_page/frontend/examples/corporate_information_page_translated_custom_logo.json
- formats/html_publication/frontend/examples/published.json
- formats/html_publication/frontend/examples/updated.json
- formats/placeholder/frontend/examples/organisation-custom-logo.json
- formats/placeholder/publisher/details.json
Goes with:
* https://github.com/alphagov/government-frontend/pull/246
* https://github.com/alphagov/static/pull/894
Part of https://trello.com/c/HtSGDoRb/594-add-organisation-logos-that-are-images-to-content-item-2
Organisations such as Land Registry, HM Prison Service, Environment Agency and Radioactive Waste Management have custom logo images.
* Use image definition to add images to organisation logos
* Include Land Registry example
* Update examples in other formats that use org logos
> Add custom logo image to organisation logos

- dist/formats/answer/frontend/schema.json
- dist/formats/answer/notification/schema.json
- dist/formats/answer/publisher/schema.json
- dist/formats/answer/publisher_v2/schema.json
- dist/formats/help_page/frontend/schema.json
- dist/formats/help_page/notification/schema.json
- dist/formats/help_page/publisher/schema.json
- dist/formats/help_page/publisher_v2/schema.json
- formats/answer/publisher/details.json
- formats/help_page/publisher/details.json
Currently Publisher does not validate the presence of content within in the body field for the Help Page and Answer formats. This means that we get an error for nil fields.
This PR now allows nil values to be sent in the body field for both the above formats.
> Remove required body field

- dist/formats/guide/frontend/schema.json
- dist/formats/guide/notification/schema.json
- dist/formats/guide/publisher/schema.json
- dist/formats/guide/publisher_v2/links.json
- dist/formats/guide/publisher_v2/schema.json
This was necessary as new definitions were added in [cc2986](https://github.com/alphagov/govuk-content-schemas/commit/cc2986a12b8eac18d3218d9d9a62ae8b7d85046c)
> Regenerate Guide schemas

- Jenkinsfile
govuk-content-schemas is invoked by many different apps.  Throttling causes other builds to fail and/or long queues.
see https://trello.com/c/qdS8doM1
> Disable throttling

- dist/formats/service_manual_service_standard/frontend/schema.json
- dist/formats/service_manual_service_standard/notification/schema.json
- dist/formats/service_manual_service_standard/publisher/schema.json
- dist/formats/service_manual_service_standard/publisher_v2/schema.json
- formats/service_manual_service_standard/frontend/examples/service_manual_service_standard.json
- formats/service_manual_service_standard/publisher/details.json
- formats/service_manual_service_standard/publisher_v2/examples/service_manual_service_standard.json
We're adding a link to a poster of the service standard to the service
standard page in the service manual. This adds a `poster_url` field to
the `service_manual_service_standard` format to allow us to manage this
via service-manual-publisher.
> Add `poster_url` to service standard format

- formats/travel_advice/frontend/examples/alt-country.json
- formats/travel_advice/frontend/examples/full-country.json
Ensure that examples are accurate before using them for tests in government-frontend.
I've also confirmed that a `no-parts` travel advice could feasibly published, although all countries currently have at least 5 parts.
Part of https://trello.com/c/L5Nd0AdH/137-3-render-travel-advice-in-government-frontend-l
> Update travel advice examples based on live content

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/publisher/schema.json
- dist/formats/case_study/publisher_v2/links.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/publisher/schema.json
- dist/formats/detailed_guide/publisher_v2/links.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/publisher/schema.json
- dist/formats/publication/publisher_v2/links.json
- formats/case_study/frontend/examples/archived.json
- formats/case_study/frontend/examples/case_study.json
- formats/case_study/publisher/links.json
- formats/case_study/publisher_v2/examples/case_study_links.json
- formats/detailed_guide/frontend/examples/england-2014-to-2020-european-structural-and-investment-funds.json
- formats/detailed_guide/publisher/links.json
- formats/publication/frontend/examples/political_publication.json
- formats/publication/publisher/links.json
We are using `related_policies` and `policies` to refer to the same thing. This PR deprecates `related_policies` in favour of `policies` for consistency and to remove the redundant `related` as these are links and are `related` implicitly.
> Consistently use policies links

- formats/guide/frontend/examples/guide.json
- formats/guide/frontend/examples/no-part-guide.json
- formats/guide/frontend/examples/single-page-guide.json
The previous guide frontend example was missing some tagged fields.
For testing purposes, we've added a few more examples with varying numbers of parts.
> Improved example Guide documents

- dist/formats/gone/frontend/schema.json
- dist/formats/gone/publisher/schema.json
- dist/formats/gone/publisher_v2/schema.json
- dist/formats/redirect/publisher/schema.json
- formats/gone/frontend/schema.json
- formats/gone/publisher/schema.json
- formats/gone/publisher_v2/schema.json
- formats/redirect/publisher/schema.json
`format` has been deprecated and is replaced by `document_type` and `schema_name`.
> Remove format fields

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document/frontend/examples/business-finance-support-scheme.json
- formats/specialist_document/publisher/details.json
This commit removes some more business finance support scheme fields, the contents of which will be incorporated into the body of the document.
Since no content items are using this schema yet, the fields can be changed without backwards-compatibility concerns.
Trello: https://trello.com/c/UHsavPI5/485-create-a-new-specialist-document-type-for-business-support-scheme
> Refine business finance support scheme fields

- Jenkinsfile
Test the publishing API against any changes to the content schemas.
> Add publishing-api to downstream builds

- dist/formats/topic/frontend/schema.json
- dist/formats/topic/publisher/schema.json
- dist/formats/topic/publisher_v2/links.json
- formats/topic/publisher/links.json
- formats/topic/publisher_v2/examples/topic_links.json
These `children` links are reverse links which are added by the publishing API, so they should not be defined in the publisher schema. Publishing apps should rely on the publishing API to add topic `children` links for them.
> Remove `children` links from `topics` publisher schema

- formats/specialist_document/frontend/examples/business-finance-support-scheme.json
This commit fixes the business finance support scheme example with HTML in the body instead of Govspeak, and a small typographical fix to the `will_continue_on` field.
> Fix the business finance support scheme example

- formats/specialist_document/frontend/examples/countryside-stewardship-grants.json
The example had an impossible public updated at date – it was before more recent updates.
It should match the most recent change note in the change history, ie a list of public updates.
This was missed in #513
> Correct public_updated_at date in specialist document example

- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/publisher/schema.json
- dist/formats/document_collection/publisher_v2/links.json
- formats/document_collection/publisher/links.json
The Whitehall format Document Collection has `related_policies`. Update schema to reflect this.
> Add related policies to document collection links

- Jenkinsfile
Looks to me like the [short-url-manager JenkinsFile](https://github.com/alphagov/short-url-manager/blob/master/Jenkinsfile) is already setup to be run from here. I think this is all we do and we can remove the ci.dev schema_branches job for short-url-manager.
> Add short-url-manager to `dependentApplications`

- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/notification/schema.json
- dist/formats/html_publication/publisher/schema.json
- dist/formats/html_publication/publisher_v2/schema.json
- formats/html_publication/frontend/examples/print_with_meta_data.json
- formats/html_publication/publisher/details.json
For: https://trello.com/c/88zaXS8J/47-create-print-styles-for-official-documents
This will add two more fields to be sent along to Publishing API from Whitehall. These two fields will be included in the print version of HTML Publications which are edited on whitehall, but will be displayed by frontend.
You can still see a draft of the HTML Publication on Whitehall, but the frontend app actually needs to display this information.
These schemas will signal to frontend to use two extra fields (that will be displayed in the print version of the HTML Publication). 
They are: `isbn` and `print_meta_data_contact_address`. Both fields are optional.
`isbn` - Identifies the Web ISBN to be displayed when printing an HTML Publication
`print_meta_data_contact_address` - Identifies the address of the …
> [DO NOT MERGE] Updates schema to html publications

- dist/formats/licence/frontend/schema.json
- dist/formats/licence/notification/schema.json
- dist/formats/licence/publisher/schema.json
- dist/formats/licence/publisher_v2/links.json
- dist/formats/licence/publisher_v2/schema.json
- formats/licence/frontend/examples/licence_with_continuation_link.json
- formats/licence/frontend/examples/licence_without_continuation_link.json
- formats/licence/publisher/details.json
We add two examples for licences, one with continuation link which will link off to an external site and one without continuation link which will make a request to the Licensify API for extra licence details.
> Licence format schema

- dist/formats/travel_advice_index/frontend/schema.json
- dist/formats/travel_advice_index/notification/schema.json
- dist/formats/travel_advice_index/publisher/schema.json
- dist/formats/travel_advice_index/publisher_v2/schema.json
- formats/travel_advice_index/publisher/details.json
This is no longer being sent by travel-advice-publisher or expected by frontend.
> Remove deprecated countries hash from travel index.

- Jenkinsfile
This app is no longer used.
cc @fofr
> Remove contacts-frontend from downstream builds

- dist/formats/publication/publisher_v2/schema.json
- formats/publication/publisher/edition_links.json
https://trello.com/c/RWL7ppZ6/637-use-draft-links-for-publications
Adds edition links for the publications format.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/567 specifically changes in `formats/base_edition_links.json`
> Add edition links to publications

- Jenkinsfile
This will allow two govuk-content-schema tests to run at the same time.
> Don't throttle tests

- dist/formats/html_publication/publisher_v2/schema.json
- formats/html_publication/publisher/edition_links.json
https://trello.com/c/RWL7ppZ6/637-use-draft-links-for-publications
Edition links for Html Publications are needed to complete the parent/children
link resolution which effectively ties a draft publication to an html attachment.
We need to present the parent of the html publication so that the links on the parent publication are resolved.
> Add edition links to html publications

- dist/formats/placeholder/publisher_v2/schema.json
- formats/placeholder/publisher/edition_links.json
Organisations are a placeholder format on Whitehall. To render an
Organisation on Whitehall there is currently use of the Publishing API
linkable endpoint, this has proven nicht gut causing some errors in
production.
This allows placeholder documents to have edition links to
featured_policies so we can start working around this problem.
It seemed a shame that all placeholder items may have to deal with this,
but this already seems to be the case with link set links, so doesn't
appear to be a new precedent.
> Include featured policies in placeholder edition links

- dist/formats/taxon/publisher_v2/links.json
- dist/formats/taxon/publisher_v2/schema.json
- formats/taxon/publisher/edition_links.json
Content tagger currently has to make separate API calls to write the content and creating the links. Since we now have draft links, we'll be able to do this in one call (and have workflow).
https://trello.com/c/8YH5l9kF
> Allow `parent_taxons` in the edition links for taxons

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/publisher_v2/links.json
- dist/formats/fatality_notice/frontend/schema.json
- dist/formats/fatality_notice/publisher_v2/links.json
- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/publisher_v2/links.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/publisher_v2/links.json
- dist/formats/speech/frontend/schema.json
- dist/formats/speech/publisher_v2/links.json
- formats/consultation/publisher/links.json
- formats/fatality_notice/publisher/links.json
- formats/news_article/publisher/links.json
- formats/publication/publisher/links.json
- formats/speech/publisher/links.json
Adds `people` and `roles` to `links.json` for the following formats:
* Consultation
* Fatality Notice
* News Article
* Publication
* Speech
In order to send emails, Email Alert Api relies on the presence of links in data that the Publishing Api sends to the rabbit queues. Whitehall in turn needs to present these links to the Publishing Api. Roles and People are currently required but missing. This will allow Email Alert Api to take over from Govuk Delivery and ultimately allow us to retire Govuk Delivery.
There will be a corresponding PR in Whitehall to present these links to the Publishing Api (currently a work in progress on this branch https://github.com/alphagov/whitehall/tree/add-links-for-email-to-migrated-formats).
[Trello](https://trello.com/c/WizHAZBT)
> Add links for email to migrated formats

- dist/formats/publication/publisher_v2/schema.json
- formats/publication/publisher/edition_links.json
Whitehall is now sending edition level roles and people links for the `Publication` format. These were in the document level links and consequently Whitehall was failing.
> Fix publication links

- Jenkinsfile
Run schema tests against government-frontend.
Requires https://github.com/alphagov/govuk-puppet/pull/5654 to be deployed for the tests to pass.
> Add government-fronted dependent application

- Jenkinsfile
This application uses the shared Jenkinsfile, so it reports its status independently. We don't have to wait for this to finish in the main jenkins run.
> Don't wait for manuals-frontend to finish

- Jenkinsfile
The info-frontend project depends on the schemas, so it should be built when the schemas change.
> Add info-frontend to downstream builds

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/publisher_v2/links.json
- dist/formats/consultation/publisher_v2/schema.json
- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/publisher_v2/links.json
- dist/formats/speech/frontend/schema.json
- dist/formats/speech/publisher_v2/links.json
- formats/consultation/publisher/edition_links.json
- formats/consultation/publisher/links.json
- formats/news_article/publisher/links.json
- formats/speech/publisher/links.json
`policies` links have been renamed to `related_policies` to avoid conflicts with `reverse_links` added by publishing api (specifically `working_groups` -> `policies`).
This PR removes remaining deprecated links now that the formats involved no longer send them.
> Remove policies links

- dist/formats/redirect/publisher_v2/schema.json
- formats/redirect/publisher_v2/examples/govuk-subdomain-redirect.json
- formats/redirect/publisher_v2/schema.json
This is part of Content Tools' 2-week blitz.
* https://trello.com/c/WEZyguEc/14-2-update-govuk-content-schema
* https://trello.com/c/jmxMgLWf/21-make-it-so-that-gds-content-designers-can-implement-redirects-reliably
This is part of work towards allowing content designers to create
redirects without developer intervention or use of the router-data
redirect system.
Broadens the definition that allows for “external” redirects from GOV.UK
to the .campaign.gov.uk sub-domain to now allow redirects to any
.gov.uk sub-domain.
Retains the example for campaigns to ensure existing functionality
is preserved while we add a new example for another GOV.UK subdomain.
> Update redirect to allow any .gov.uk subdomain

- dist/formats/local_transaction/frontend/schema.json
- dist/formats/local_transaction/notification/schema.json
- dist/formats/local_transaction/publisher_v2/schema.json
- formats/local_transaction/frontend/examples/local_transaction.json
- formats/local_transaction/publisher/details.json
All local transactions will be assigned to a lgil_code by default. The term
"override" is therefore misleading and we should rename this variable.
This leaves lgil_override as a deprecated field until local transactions have been
republished.
https://trello.com/c/RnJC1d7a/5-assign-lgil-codes-to-all-local-transactions
> Assign lgil codes

- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/notification/schema.json
- dist/formats/html_publication/publisher_v2/schema.json
- formats/html_publication/frontend/examples/print_with_meta_data.json
- formats/html_publication/publisher/details.json
[Trello card](https://trello.com/c/OEZIdXTE/135-separate-file-attachment-form-and-html-attachment-form)
Depends on: 
https://github.com/alphagov/whitehall/pull/3170
https://github.com/alphagov/government-frontend/pull/325
It was pointed out that the "ISBN (web version)" field is showing up not only in the HTML Attachments form, but also in the File Attachments form. Additionally, this was becoming confusing to people because they were entering the Print ISBN in that field. 
NB: HTML Attachments are called HTML Publications in this project, but are still called "attachments" in whitehall. 
This updates the schema to separate the ISBN field into "Print ISBN" and "Web ISBN".
The HTML attachment will show both Print and Web ISBN, when printed.
The File attachment will not need to display the …
> [DO NOT MERGE] Updates schema for html publications

- dist/formats/homepage/frontend/schema.json
- dist/formats/homepage/notification/schema.json
- dist/formats/homepage/publisher_v2/links.json
- dist/formats/homepage/publisher_v2/schema.json
- formats/homepage/publisher/details.json
- formats/homepage/publisher/links.json
- formats/homepage/publisher_v2/examples/homepage.json
- formats/homepage/publisher_v2/examples/service_manual_homepage.json
A slightly more generically named Homepage schema to replace the `service_manual_homepage` and the gov.uk Homepage which is currently a `special_route`
> Add homepage schema

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/notification/schema.json
- dist/formats/taxon/publisher_v2/schema.json
- formats/taxon/frontend/examples/taxon.json
- formats/taxon/publisher/details.json
For Taxons that are ready to come out of development but shouldn't be viewable by the general public yet. Use the `visible_to_departmental_editors` flag to make the `draft` taxon appear in the `Draft Taxonomies` section of the new tagging interface. 
Note that this is only relevant for taxons at the root of their taxonomy tree.
[Trello](https://trello.com/c/3xt6aNdb/73-make-certain-taxons-visible-as-drafts-to-whitehall-editors)
> Add Visiblity property to taxon schema

- dist/formats/corporate_information_page/publisher_v2/schema.json
- formats/corporate_information_page/publisher/edition_links.json
Corporate information pages have `parent` and `organisation` links that are not currently being sent with first draft versions. This is causing 500s in preview as the organisation brand cannot be determined.
This commit adds edition level links to allow them to be sent with the drafts.
> Support edition links for corporate information pages

- Gemfile.lock
This puts a RUBY_VERSION and updates BUNDLED_WITH to the correct version
as per our puppet infrastructure. Having these left out means useful
scripts in the development VM won't run on this repo because of
uncommitted local changes.
> Re-bundle with new ruby and bundler

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/publisher_v2/schema.json
- formats/taxon/frontend/examples/taxon_with_associated_taxons.json
- formats/taxon/publisher/edition_links.json
This PR adds a new link type to the taxon schema `associated_taxons`
This link type will be used to link one taxon to one or more other taxons in such a way that the other taxon's children will be included as children of the taxon that declares the links.
e.g.
* `usa` taxon has `child_taxons` of `[travelling-in-the-usa]`
* `travelling-in-the-usa` has `associated_taxons` of `[travelling-abroad]` and `child_taxons` of `[usa-travel-advice]`
* `travelling-abroad` has `child_taxons` of `[driving-abroad, getting-married-abroad]`
The taxon page for `usa` would display a 'Travelling in the USA' heading containing the combined children 'USA travel advice', 'Driving abroad' and 'Getting married abroad'.
[Trello](https://trello.com/c/xegbo9qO/205-add-new-link-type-for-link-between-generic-and-specifi …
> Add associated taxons

- dist/formats/world_location/frontend/schema.json
- dist/formats/world_location/notification/schema.json
- dist/formats/world_location/publisher_v2/links.json
- dist/formats/world_location/publisher_v2/schema.json
- formats/world_location/publisher/details.json
- formats/world_location/publisher/edition_links.json
- formats/world_location/publisher/links.json
- lib/schema_generator/publisher_content_schema_generator.rb
WorldLocations are no longer going to be rendered by Whitehall (with the exception of the international delegation type) as they are going to be replaced by taxons. They do still need to be linkable by other content though as other things depend on this assocation e.g. email alerts.
They are currently sent as placeholders to the publishing API. This commit creates a new schema for them (which is just a placeholder copy with the name changed) and then removes the requirement for a base path from  that schema.
[Trello](https://trello.com/c/6tio72jl/221-split-world-locations-from-international-delegations-in-whitehall)
> Add world location schema

- formats/special_route/frontend/examples/special_route.json
This commit adds an example of the `special_route` format. This format isn't rendered but rendering apps do need to handle it now that content-store will fall through to the first prefix route that it finds
if a specific content item is not found.
e.g. `/government/i-dont-exist` will return the `/government` `special_route` item.
Having this example will allow us to test for this and handle it properly.
> Add special_route example

- dist/formats/vanish/notification/schema.json
- dist/formats/vanish/publisher_v2/schema.json
- formats/vanish/notification/schema.json
- formats/vanish/publisher_v2/schema.json
The vanish schema will only be used for sending unpublishing messages to
the notification queue.
[Trello card](https://trello.com/c/5a7bQyHI/963-notify-downstream-services-search-indexing-when-documents-are-unpublished-3)
> Add vanish schema

- dist/formats/gone/notification/schema.json
- dist/formats/redirect/notification/schema.json
- dist/formats/vanish/notification/schema.json
- formats/gone/notification/schema.json
- formats/redirect/notification/schema.json
- formats/vanish/notification/schema.json
This field had already been added to the notification base, which added
it to most notification schemas. But it was missing from the unpublishing
schemas: gone, redirect and vanish.
Adding a payload_version to those schemas will allow the version to be
passed from the publishing API to rummager.
https://trello.com/c/LatZVRg8/213-make-versioning-work-for-all-publishing-events
Mobbed with @binaryberry, @Rosa-Fox, @MatMoore and @suzannehamilton.
> Add payload_version field to unpublishing notification schemas

- formats/finder/frontend/examples/drug-device-alerts.json
- formats/specialist_document/frontend/examples/drug-device-alerts.json
For: https://trello.com/c/HbnBgaJd/208-rename-filter-title-in-mhra-finder
The real finder has the title of this field changed to "Medical
speciality" to match the words used by the audience of these alerts
so we make the same change in the schemas for consistency.
This matches up with the changes in https://github.com/alphagov/specialist-publisher/pull/1051
> Change display title of medical_specialism finder in examples

- formats/finder/frontend/examples/drug-device-alerts.json
- formats/specialist_document/frontend/examples/drug-device-alerts.json
For: https://trello.com/c/HbnBgaJd/208-rename-filter-title-in-mhra-finder
We got it wrong in the previous commit
(b529cb1b60d9447812c85d8ec1ccda44c84c92fc - #643) it should be specialty, not
speciality.  Specialty is the medical term and medicine is the domain for
this finder, so that's the word we should use.
> Change the display title of medical_specialism

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/notification/schema.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact/frontend/examples/contact.json
- formats/contact/publisher/details.json
- formats/contact/publisher_v2/examples/whitehall-contact.json
The contact_groups properties are used in search:
- The title is included in the indexable content for a contact, so that users can find the contact if their search term includes the name of the contact group.
- The slug is used by the search filter in the [HMRC contacts finder](https://www.gov.uk/government/organisations/hm-revenue-customs/contact)
The contacts admin app currently sends these fields directly to rummager, but we are currently changing this process so that all data in the search index comes from the publishing API, which means these fields need to be in the schemas.
https://trello.com/c/KX2WILnc/332-add-contactgroups-to-publishing-api
Once we've republished all the contacts, we'll come back and make this contact_groups a required field.
> Add contact_groups field to contacts

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/notification/schema.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact/frontend/examples/contact_with_email_and_no_other_contacts.json
- formats/contact/frontend/examples/contact_with_webchat.json
- formats/contact/frontend/examples/contact_with_welsh.json
- formats/contact/publisher/details.json
Now that Contacts Admin sends the contacts_group field to the publishing API and all the contacts have been republished, this field should always be present even if it's an empty array.
Making this a required field will simplify the rummager code which depends on it.
https://trello.com/c/KX2WILnc/332-add-contactgroups-to-publishing-api
Paired with @Rosa-Fox 
The build will fail until we've deployed the latest version of publishing API.
>  Make contact_groups a required field for contacts

- dist/formats/guide/frontend/schema.json
- dist/formats/guide/notification/schema.json
- dist/formats/guide/publisher_v2/schema.json
- dist/formats/transaction/frontend/schema.json
- dist/formats/transaction/notification/schema.json
- dist/formats/transaction/publisher_v2/schema.json
- examples/guide/frontend/guide-with-cross-domain-tracking.json
- examples/guide/publisher_v2/guide.json
- formats/guide.jsonnet
- formats/shared/definitions/department_analytics_profile.jsonnet
- formats/transaction.jsonnet
We want to add cross domain tracking to guides since people use these as an entry point to some services.
This feature involves including a department's Google Analytics Profile ID, this allows us to send them the session for the guide so they get a more complete picture of how their service is working end to end.
As part of https://trello.com/c/fxddq3se/30-3-extend-cross-domain-tracking-to-guide-type
> Add cross domain tracking support to guides

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- lib/govuk_content_schemas/allowed_document_types.yml
This commit adds the placeholder_task_list, that should allow us to run the BETA
version of the task list pages that we are preparing.
Trello:
https://trello.com/c/WOhDbn9e/208-publish-route-for-the-task-list-page
> Add document type 'task_list' into allowed document types

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- lib/govuk_content_schemas/allowed_document_types.yml
For: https://trello.com/c/RRJOTFQo/252-remove-business-support-code-that-still-exist-in-publisher
This is part 4 of the work for this card to remove business support documents - this PR removes `business_support` from the schemas. Part 1 does the redirects (see: alphagov/publisher#648), part 2 removed the code from publisher (see: alphagov/publisher#649), and part 3 removes the old redirects from router-data (see: alphagov/router-data#5).
There aren't any examples or a specific schema for `business_support`; they're all `generic_with_external_related_links` with document_type of `business_support`.
> Remove business_support as allowed document type

- Jenkinsfile
Rummager currently tests against the schemas for payload messages from the publishing api.
> Add Rummager to downstream builds

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
For [Trello](https://trello.com/c/PeyfXTmT/112-ability-to-add-industry-tag-life-sciences-to-a-business-finance-support-scheme-upload-form)
A user has discovered a bug in Specialist Publisher where an error occurs upon saving a document which is tagged with the "Life Sciences" industry (see [Zendesk ticket](https://govuk.zendesk.com/agent/tickets/2418667)).  
It turns out that "Life Sciences" was not present as a permitted industry in the `specialist_document` schema, so this PR adds `life-sciences` to the list of allowed industries.
> Add Life Sciences industry to specialist_document schema

- Jenkinsfile
Schema changes are currently not running specs against the feedback application, which resulted in a failed test when first running the feedback application.
> Include feedback as dependent application for schema changes

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- lib/govuk_content_schemas/allowed_document_types.yml
For: https://trello.com/c/ufw2S0ZX/265-create-publishing-api-redirect-for-business-finance-support-finder
We've unpublished the old custom finder that lived at
/business-finance-support-finder with a redirect to the new standard
finder that lives at /business-finance-support.  No other documents use
this document_type so we are safe to remove it.
> Remove business_support_finder as an allowed document_type

- Gemfile
- Gemfile.lock
- Procfile
- README.md
- app.rb
- docs/running-frontend-against-examples.md
- preview_app/index.erb
- spec/integration/preview_app_spec.rb
- startup.sh
This integrates the dummy content store (https://github.com/alphagov/govuk-dummy_content_store).
Differences between this and the gem:
- It's no longer a gem so we don't have to release a new version for each change and bump the version. This makes it easier for the app on Heroku to keep up to date (the app is deployed from this repo to make sure that the schemas used by the app are always up to date).
- By using Sinatra we can drop a lot of the code needed to render responses and render the ERB template. This version is hundreds of lines smaller.
- Instead of proxying the content store, this app redirects to the live content store. This removes complexity and is more robust.
- Makes sure that items returned have the correct base_path. Applications like government-frontend sometimes look …
> Integrate dummy content store

- docs/adding-a-new-schema.md
We add a missing step to the "Adding a new schema" docs, which is to remember to
add the new format to `allowed_document_types.yml`.
> Update add a new schema docs

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/service_sign_in/frontend/schema.json
- dist/formats/service_sign_in/notification/schema.json
- dist/formats/service_sign_in/publisher_v2/links.json
- dist/formats/service_sign_in/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- examples/service_sign_in/frontend/service_sign_in.json
- formats/service_sign_in.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
For [Trello](https://trello.com/c/VO0HVhk8/240-create-schema-for-interstitial-pages-in-govuk-content-schemas)
Paired with @leenagupte 
We are creating a new journey for users on transaction pages in order to better support multiple login options for a service.  After clicking on the "Start now" button on a transaction page, we intend for users to land on a page that presents the multiple login options (e.g. Government Gateway, GOV.UK Verify) in a radio button format so they can make the right choice for them.  One of the options will be "Create new account", and we felt that since this page is so closely linked to the radio button page and would be very unlikely to exist on it own, we can house these pages under one format - `service_sign_in`.  As such, we create a new schema for this …
> Add service_sign_in schema

- examples/service_sign_in/frontend/service_sign_in.json
Trello card: https://trello.com/c/zsPE3IXV
The service_sign_in format will use the `parent` link to set which start page to link back to in the `Back` button on the choose-sign-in page.
> Add a parent link to service_sign_in example

- examples/service_sign_in/frontend/service_sign_in.json
Since these descriptions are expected to be govspeak, a single line like this
would be given a wrapper paragraph.
This updates to add this wrapper, so that when it's passed to the [govspeak](http://govuk-static.herokuapp.com/component-guide/govspeak)
component, proper spacing and styling is applied
> Makes sure the description a govspeak output

- dist/formats/calendar/frontend/schema.json
- dist/formats/calendar/notification/schema.json
https://github.com/alphagov/govuk-content-schemas/pull/677 and https://github.com/alphagov/govuk-content-schemas/pull/678 were merged around the same time, so the calendars schema didn't have all the changes. This is causing subsequent PRs like https://github.com/alphagov/govuk-content-schemas/pull/680 to fail.
This situation can be prevented by requiring branches to be up to date before merging (there's a GitHub setting for that), but it's so rare that I don't think it's worth the hassle.
> Fix generated schema for calendar

- app.rb
- spec/integration/preview_app_spec.rb
If a content example is given a suffix, then we assume it's a prefixed route.
This allows pages like 'examples/guide/guide/key-stage-1-and-2' to succeed.
Unblocks https://trello.com/c/zsPE3IXV/248-3-pull-data-into-the-choose-sign-in-options-page
> Allow prefixed routes to work in examples

- examples/case_study/frontend/archived.json
- examples/case_study/frontend/case_study.json
- examples/case_study/frontend/translated.json
- examples/news_article/frontend/news_article.json
- examples/news_article/frontend/news_article_government_response.json
- examples/news_article/frontend/news_article_history_mode.json
- examples/news_article/frontend/news_article_news_story_translated_arabic.json
- examples/news_article/frontend/news_article_press_release.json
- examples/news_article/frontend/world_news_story_news_article.json
- examples/speech/frontend/speech-authored-article.json
- examples/speech/frontend/speech-oral-statement-parliament.json
- examples/speech/frontend/speech-speaker-without-profile.json
- examples/speech/frontend/speech-speaking-notes.json
- examples/speech/frontend/speech-transcript.json
- examples/speech/frontend/speech-translated.json
- examples/speech/frontend/speech-written-statement-parliament.json
- examples/speech/frontend/speech.json
https://trello.com/c/q0PNOZkj/117-move-formats-with-images-to-universal-layout
Moving 'Part of' links to the navigation sidebar means [some
integration tests on government-frontend will require the sidebar
to render](https://github.com/alphagov/government-frontend/pull/580/commits/bff4b8c805ae3f5eb376bd70cd7d4e9b45eff9b5), so add the `document_type` to the relevant
schema examples used in the first batch of redesigned formats as
the [related navigation relies on this attribute to include the links](https://github.com/alphagov/govuk_navigation_helpers/blob/master/lib/govuk_navigation_helpers/content_item.rb#L161).
More to follow as we redesign more formats.
> Add some more document_type attributes to frontend examples

- dist/formats/service_sign_in/frontend/schema.json
- dist/formats/service_sign_in/notification/schema.json
- dist/formats/service_sign_in/publisher_v2/schema.json
- examples/service_sign_in/frontend/service_sign_in.json
- examples/service_sign_in/frontend/view_driving_licence.json
- examples/service_sign_in/frontend/welsh.json
- formats/service_sign_in.jsonnet
- Adds in a VDL example so we can test examples that do not need the :or option
- Adds a welsh version so we can test i18n and our routing works with different slugs
- Updates default example to be more complete
- Makes `create_new_account` an optional field, as there are services such as VDL that don't require it ([Trello card](https://trello.com/c/ydt46bDm/276-make-the-create-new-account-page-optional-in-the-schema))
Tested against government-frontend with
- http://government-frontend.dev.gov.uk/examples/service_sign_in/service_sign_in/choose-sign-in
- http://government-frontend.dev.gov.uk/examples/service_sign_in/welsh/dewiswch-lofnodi
- http://government-frontend.dev.gov.uk/examples/service_sign_in/view_driving_licence/choose-sign-in
> Update service sign in examples

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
- formats/specialist_document.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
This specialist document type was added in https://github.com/alphagov/manuals-publisher/pull/480 as an MVP. Unfortunately no documents were ever published.
It's unused, so it's probably best to remove it to avoid unnecessary maintenance and avoid confusion.
The code was removed from specialist publisher in https://github.com/alphagov/specialist-publisher/pull/1072.
https://trello.com/c/Jm6K9Tpx
> Remove Vehicle Recalls and Faults Alerts schema

- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- formats/placeholder.jsonnet
DIT has a different crest to the single identity, so add this to the schema to allow it to be used.
Trello: https://trello.com/c/0uP5xe70/450-update-logo-on-uk-export-finance-about-us-page
> Add DIT crest type

- Jenkinsfile
The search-admin app now publishes external content ("recommended links") to the publishing API and depends on the content schemas.
https://trello.com/c/rDurYmt8/525-send-external-links-from-search-admin-to-the-publishing-api
> Add search-admin to downstream builds

- examples/consultation/frontend/closed_consultation.json
- examples/consultation/frontend/consultation_outcome.json
- examples/consultation/frontend/consultation_outcome_with_feedback.json
- examples/consultation/frontend/open_consultation.json
- examples/consultation/frontend/open_consultation_with_participation.json
- examples/consultation/frontend/unopened_consultation.json
Moving 'Part Of' links to the related navigation sidebar means some integration tests will require the sidebar to render.
The logic behind the sidebar relies on the presence of the document_type attribute, so we need to add this to our examples.
> Add document type attribute for consultations

- Jenkinsfile
For: https://trello.com/c/QtpGwa2A/288-improve-feedback-on-github-for-changes-to-govuk-content-schemas
This means both these apps can report to github themselves and we don't have to wait for them
explicitly in our Jenkinsfile anymore.
These are the last two, but I've left the wait version of the `dependentApplications` loop just in case we need to add some apps that don't use the standard jenkinsfile and don't talk to github themselves.  But I could be convinced to delete this if pressed as I don't really think we want to encourage it.
See: alphagov/service-manual-frontend#127, alphagov/whitehall#3640 and previous work in #661
> Service Manual Frontend & Whitehall now use the standard buildProject

- dist/formats/homepage/frontend/schema.json
- dist/formats/homepage/notification/schema.json
- dist/formats/homepage/publisher_v2/links.json
- formats/homepage.jsonnet
Trello: https://trello.com/c/g41T515W/314-clean-up-use-of-the-roottaxons-link-on-the-homepage-content-item
This has been replaced by a reversible link type introduced in [1].
Consumers that were using the 'root_taxons' links have been updated and
are now using the 'level_one_taxons' link type.
[1] https://github.com/alphagov/govuk-content-schemas/commit/ce97b51b6d61d72eef49e54ae79c2546c1494f04
> Remove root taxons link type

- examples/finder/frontend/countryside-stewardship-grants.json
- examples/specialist_document/frontend/countryside-stewardship-grants.json
This label is about to change, so this updates the examples as well. We won't be changing the `value` since that will require data migrations.
https://www.gov.uk/countryside-stewardship-grants
Trello: https://trello.com/c/zrAiZbCo
> Update label for the Countryside Stewardship grants

- examples/detailed_guide/frontend/detailed_guide.json
- examples/detailed_guide/frontend/national_applicability_detailed_guide.json
- examples/detailed_guide/frontend/political_detailed_guide.json
- examples/detailed_guide/frontend/related_mainstream_detailed_guide.json
Part of https://trello.com/c/uScvU8q2/189-add-detailedguide-to-universal-layout
Required by https://github.com/alphagov/government-frontend/pull/706
> Add document_type to detailed guide examples

- examples/consultation/frontend/open_consultation.json
Missed in https://github.com/alphagov/govuk-content-schemas/pull/712
> Add missing government_document_supertype

- dist/formats/redirect/frontend/schema.json
- examples/redirect/frontend/redirect.json
- lib/schema_generator/frontend_schema_generator.rb
See: https://github.com/alphagov/gds-api-adapters/pull/805 for context
Currently it's possible to have a redirect make its way to a frontend
application (for example when a route is in the process of changing to a
redirect at the time of a request). Frontend apps don't have any means
to deal with these redirects as they are not provided with the content
item.
Since this field is only useful on redirects it's only enabled on
documents with that schema name. It is also an optional field as any
existing published redirects won't have it.
> Allow redirects

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
According to Step by Step navigation component guide,
an object with type of "list" can also have a style of "optional".
This commit adds that validation.
Reference: https://government-frontend.herokuapp.com/component-guide/task_list
> Fix step by step nav schema

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- examples/step_by_step_nav/frontend/learn_to_drive_a_car.json
- examples/step_by_step_nav/publisher_v2/learn_to_drive_a_car.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
We need to be able to display a title and introduction to a step by step navigation.  These may be different to the page title and the description (which is used as the meta description and in search).  
The introduction may also be in markdown as we've already identified that this will need to have
several paragraphs for future step by step navigation journeys.
We'll make this `required` in a future PR
https://trello.com/c/3pQPJDmj/440-allow-collections-to-render-task-lists-from-the-publishing-api
> Add fields to step by step navigation

- examples/answer/frontend/answer-with-step-navs.json
- examples/guide/frontend/guide-with-step-navs.json
- examples/manual/frontend/manual-with-step-navs.json
- examples/simple_smart_answer/frontend/simple-smart-answer-with-step-navs.json
- examples/transaction/frontend/transaction-with-step-navs.json
I didn't want to edit the existing samples because step by step navigation takes precedence over a lot of other things when it exists. I could see edits to existing ones breaking unrelated tests.
These are the document types that are in our current step by step navigation. They're in frontend, government-frontend and manuals-frontend.
> Add examples of documents with step nav links

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
- formats/shared/definitions/finder.jsonnet
This commit adds `signup_link` to the finder content schema. This element is used by finder-frontend to override the normal email signup link if required.
> Add signup link to finder schema

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/notification/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
https://trello.com/c/ACZBT7Dk/120-build-a-way-to-publish-the-new-finder
Finders will soon accept a `hidden` facet type. So make sure this type is declared in the facet type enum.
> Add hidden facet type for finders

- Jenkinsfile
Rather than the release branch, as the tag is more specific, and
better represents what has been deployed in Jenkins and the Release
app.
> Deploy the release tag to integration

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/notification/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
Prerequisite of https://trello.com/c/ACZBT7Dk/120-build-a-way-to-publish-the-new-finder
and related to https://github.com/alphagov/finder-frontend/pull/443
An optional property `filter_key` can be used to [alias a key to a facet search filter](https://github.com/alphagov/finder-frontend/pull/443/commits/a7355c42a68e0f0de2f5b929a15020d420783609#diff-bfcfe8d4326f22af7b796495a237e0e3R43) for finders,
this allows URL parameters to differ from the underlying search details.
> Add filter key to finder facets

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
Part of https://trello.com/c/ACZBT7Dk/120-build-a-way-to-publish-the-new-finder
We don't want the advanced search finder at `/search/advanced` to be indexed in search, giving it a document type of `search` will circumvent indexing.
See https://github.com/alphagov/rummager/pull/1196 for details of the finder.
> Add search as finder document type

- examples/travel_advice/frontend/no-parts.json
- examples/travel_advice/publisher_v2/travel_advice.json
- examples/travel_advice_index/frontend/index.json
- examples/travel_advice_index/publisher_v2/travel_advice_index.json
This commit changes the `email_signup_link` field in the relevant examples to point to a more realistic location.
Trello: https://trello.com/c/VK18GrmW/736-clean-up-all-remaining-govdelivery-references-across-all-repos
> Change email_signup_link in examples

- dist/formats/corporate_information_page/publisher_v2/schema.json
- formats/corporate_information_page.jsonnet
Trello: https://trello.com/c/dwniZAC4/71-investigate-change-note-lag-bug-in-emails
Currently these have an incorrect history and the alerts for them are
coming out incorrect. I've decided to go with the deprecated
change_history appraoch rather than using change_note since Whitehall
already does all of it's change_history through `change_history` and
this seems less likely to cause surprises than introducing a
`change_note` field.
> Add change_history to Corporate Information Pages

- dist/formats/completed_transaction/frontend/schema.json
- dist/formats/completed_transaction/notification/schema.json
- dist/formats/completed_transaction/publisher_v2/schema.json
- formats/completed_transaction.jsonnet
A new promotion option `MOT reminder` needs to be added to the `completed_transaction` schema, and is required before updates in `Publisher` can be made.
Part of work required for Trello card: [Request for new option in Completed Transaction 'promotion' slot](https://trello.com/c/fQQYxNIK/70-request-for-new-option-in-completed-transaction-promotion-slot)
> Add new option to completed_transaction schema

- dist/formats/person/frontend/schema.json
- dist/formats/person/notification/schema.json
- dist/formats/person/publisher_v2/links.json
- dist/formats/person/publisher_v2/schema.json
- formats/person.jsonnet
This creates a person schema. It's pretty empty and only has the image in it. In future iterations this will probably be expanded.
Part of a spike for the porg pages team so that we can see how difficult it is to migrate the organisation pages.
https://trello.com/c/xebVLRcp
> Create person schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- examples/organisation/frontend/organisation.json
- formats/organisation.jsonnet
This commit tweaks the organisation schema with the following changes:
* Change `services` to `service` for the homepage priority types to match the name in whitehall
* Remove `image` from social media links since this is determined in CSS from the service name
Trello: https://trello.com/c/IftdS5pN/25-get-whitehall-to-publish-organisation-data-to-the-content-store
> Tweak organisation schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
This commit makes the `brand` and `updated_at` (for closed status) fields optional since they won’t always be used.
Trello: https://trello.com/c/IftdS5pN/25-get-whitehall-to-publish-organisation-data-to-the-content-store
> More tweaks to the organisation schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
This commit adds `payment_type` and `attends_cabinet_type` fields to the organisation schema. These fields contain strings if the relevant people are unpaid/paid as part of another role, and if they are non-Cabinet members who attend Cabinet.
Trello: https://trello.com/c/IftdS5pN/25-get-whitehall-to-publish-organisation-data-to-the-content-store
> Add payment_type and attends_cabinet_type to organisation schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
This commit allows `name_prefix` and `role_href` for people and `public_updated_at` and `document_type` for featured documents be `null`, since these fields are not always expected to be populated. It also moves the person definition into a shared file since all person definitions for organisations are identical.
Trello: https://trello.com/c/IftdS5pN/25-get-whitehall-to-publish-organisation-data-to-the-content-store
> Make certain organisation fields nullable

- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/links.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- formats/organisations_homepage.jsonnet
This commit adds new link types for organisations grouped by their type. This enables index pages and similar content that requires all organisations of a certain type.
Trello: https://trello.com/c/kMgJ1gqF/56-link-to-all-organisations-from-the-organisation-list-content-item
> Add organisation links by type

- dist/formats/person/frontend/schema.json
- dist/formats/person/notification/schema.json
- dist/formats/person/publisher_v2/schema.json
- formats/person.jsonnet
We are moving Organisations away from Whitehall, in this commit we would like to expand the Person schema so we can start sending information to Publishing API.
There might be more fields to be added in the future, such as person role.
Trello: https://trello.com/c/32LO2xT8/30-work-out-what-information-we-need-to-publish-to-the-content-store-for-people-and-fix-the-schema-for-it
> Update Person Schema

- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/links.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- examples/organisations_homepage/frontend/organisations_homepage.json
- formats/organisations_homepage.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
This commit moves the links to all organisations on the organisations homepage to the details hash, in order to be able to make them much smaller.
Trello: https://trello.com/c/kMgJ1gqF/56-link-to-all-organisations-from-the-organisation-list-content-item
> Move organisations homepage links to details

- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/role.jsonnet
This commit amends the role schema by removing some non-required fields and fixing the enum options for role payment types.
> Amend role schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- dist/formats/person/frontend/schema.json
- dist/formats/person/notification/schema.json
- dist/formats/person/publisher_v2/schema.json
- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/organisation.jsonnet
- formats/person.jsonnet
- formats/role.jsonnet
This commit adds links from people -> roles, roles -> people, roles -> organisations and organisations -> roles.
Trello: https://trello.com/c/UDOsklt8/71-link-people-to-roles-in-publishing-api and https://trello.com/c/rhJHzjPP/72-link-roles-to-organisations
> Add links between people, roles and organisations

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
This commit adds FoI contacts and sub organisations (high profile groups) to organisations for rendering.
Trello: https://trello.com/c/Fnixoocj/128-add-more-data-to-the-organisations-content-item
> Add FoI contacts and sub organisations to organisations

- dist/formats/manual/frontend/schema.json
- dist/formats/manual/notification/schema.json
- dist/formats/manual/publisher_v2/links.json
- formats/manual.jsonnet
Manuals was importing `base_edition_links` instead of `base_links`, which isn't right. This was discovered when trying to set a primary_publishing_organisation for manuals.
> Fix manuals schema import of links

- dist/formats/role_appointment/frontend/schema.json
- dist/formats/role_appointment/notification/schema.json
- dist/formats/role_appointment/publisher_v2/schema.json
- formats/role_appointment.jsonnet
This commit makes `rendering_app` optional for role appointments since they won’t be rendered.
> Make rendering_app optional for role appointments

- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- formats/shared/definitions/_whitehall.jsonnet
We need more information in `summary_organisations`.
The reason behind this is that we need to maintain the `/api/organisations` current endpoint, this endpoint is managed by Whitehall::Api and since organisations are being extracted from Whitehall we are moving this functionality to be rendered by collections app.
The main objective is to keep the endpoint exactly as it is but being fetched from content-store.
Without this change, the alternative is to find each content_item (organisation) by base_path and retrieve the necessary information, although this would cause several more requests. We think this is the best approach.
Trello: https://trello.com/c/p7ywlbk1/130-migrate-organisations-api
> Expand Whitehall summary_organisations

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- formats/organisation.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
This commit adds a new field to the organisation schema for an optional acronym, and amends the definition for an acronym in the organisations_homepage schema to match.
Trello: https://trello.com/c/lTOLkzUo/148-org-show-page-issues
> Add acronym for organisations

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/specialist_document.jsonnet
https://trello.com/c/Hf90xZZq/219-drop-down-for-organisations-in-eu-exit-statutory-instrument-specialist-publisher-document-type
Adds edition links for `primary_publishing_organisation` and `organisations`
see https://github.com/alphagov/govuk-content-schemas/pull/778
> Add organisations edition links

- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- examples/organisations_homepage/frontend/organisations_homepage.json
- formats/shared/definitions/_whitehall.jsonnet
This commit amends the definition of `summary_organisations` to add some more required fields and to make all nested organisation fields consistent.
Trello: https://trello.com/c/p7ywlbk1/130-migrate-organisations-api
> Amend definition of summary_organisations

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- examples/organisation/frontend/organisation.json
- formats/organisation.jsonnet
This commit adds promotional features to organisations, which are used by some organisations to add extra sections to their homepages.
Trello: https://trello.com/c/zzD0d2N5/196-add-promotional-features-to-organisation-content-items
> Add promotional features to organisations

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
This commit adds a new URL field to the organisation status. This will be used for non-live organisations to point to their current or new website.
> Add URL to organisation status

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/notification/schema.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact.jsonnet
This commit fixes the contact schema to match reality:
* `rendering_app` is made optional since contacts are not normally rendered as standalone items
* `contact_groups` is made optional since whitehall doesn’t support them
* `description` is allowed to be null since it’s optional in whitehall
> Fix contact schema

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/notification/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
We want to use this for the new organisation finder as it's more likely to be accurate than specifying all the document types.
https://trello.com/c/fSv9RhjE/199-migrate-latest-pages-from-organisations
> Allow email document supertype in finders

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
This commit adds the `secondary_corporate_information_pages` field to the organisation schema. This field is a string containing sentences and links to corporate information pages that are not included in `ordered_corporate_information_pages`.
> Add secondary_corporate_information_pages

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- examples/step_by_step_nav/frontend/step_by_step_nav.json
- examples/step_by_step_nav/publisher_v2/step_by_step_nav.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
They're always populated by the publisher and are required for rendering in the
view.
This was causing an intermittent failure on Collections tests because one of the examples didn't have the title.
> Make title and intro mandatory for step by steps

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
This commit adds a new field to the organisation schema for the number of important board members. This field determines how many board members will have their photos displayed on the organisation’s home page.
Trello: https://trello.com/c/bQTgWtGh/43-img-missing
> Add field for number of important board members

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/notification/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
This lets us create finders using [content purpose supergroups](https://github.com/alphagov/govuk_document_types/blob/5d572a6439c20593d448c83cfc68e21e82d49b91/data/supertypes.yml#L486-L572)!
We need this in this instance so we can match up the latest content for orgs
page with what is in the atom feeds and in the "latest content from" section
on the org pages themselves.
> Add content purpose supergroup to finder schema

- examples/specialist_document/frontend/eu-withdrawal-act-2018-statutory-instruments.json
https://trello.com/c/tTKHE3Bx/280-add-a-link-from-statutory-instrument-content-pages-back-to-statutory-instrument-finder
This is required by tests in government-frontend. See https://github.com/alphagov/government-frontend/pull/955
> Add a statutory instrument frontend example

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/notification/schema.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact.jsonnet
This commit adds a new optional field to contacts for webchat information. This was previously hardcoded in government-frontend.
Trello: https://trello.com/c/kcGo8LWv/331-webchats-changes-to-dynamic-text
> Add webchat more info field for contacts

- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/notification/schema.json
- dist/formats/news_article/publisher_v2/links.json
- dist/formats/news_article/publisher_v2/schema.json
- formats/news_article.jsonnet
https://trello.com/c/4sTwhdPN/87-make-associations-available-to-select-when-creating-a-document-l
The new Content Publisher app will take the approach of using edition
links wherever possible, the key advantage being that edition links are
part of the published content and can therefore be scheduled/versioned.
Initially we would like to support a subset of the current links, such
as world_locations and organisations; other kinds of links, such as
roles and people, are technically more challenging and will come later.
Note this should have no effect on current publishing tools, as existing
linkset links will be used if edition links do not exist for a document.
> Duplicate news article links as edition links

- dist/formats/guide/frontend/schema.json
- dist/formats/guide/notification/schema.json
- dist/formats/guide/publisher_v2/schema.json
- examples/guide/frontend/guide-with-step-navs.json
- formats/guide.jsonnet
- will be used to control the display of contents list and other guide elements where the guide is inside a step by step navigation
Trello card: https://trello.com/c/RNsA7E4Q/763-hide-chapter-navigation-on-mainstream-guides
Supercedes #802.
> Add property to hide chapter navigation in guides

- dist/formats/statistical_data_set/publisher_v2/schema.json
- formats/statistical_data_set.jsonnet
The new Content Publisher app will take the approach of using edition
links wherever possible, the key advantage being that edition links are
part of the published content and can therefore be scheduled/versioned.
Note this should have no effect on current publishing tools, as existing
linkset links will be used if edition links do not exist for a document.
> Duplicate stat data set links as edition links

- examples/guide/frontend/guide-with-step-navs-and-hide-navigation.json
- examples/guide/frontend/guide-with-step-navs.json
- examples/guide/frontend/single-page-guide-with-step-navs-and-hide-navigation.json
We need some more examples in order to be able to test the new guide property, `hide_chapter_navigation`.
- remove `hide_chapter_navigation` from `guide-with-step-navs` and add a new example for this, `guide-with-step-navs-and-hide-navigation`
- add example of a single page guide with step navs and `hide_chapter_navigation`
> Add more examples to test hide_chapter_navigation

- examples/guide/frontend/no-part-guide-with-step-navs-and-hide-navigation.json
This adds an example guide that has no parts, is in a step by step navigation, and has `hide_chapter_navigation` set to true, for testing purposes.
In practice this should never happen but I believe it was related to an intermittent error with the 'random but valid items do not error' test in government-frontend.
Trello card: https://trello.com/c/RNsA7E4Q/763-hide-chapter-navigation-on-mainstream-guides
> Adding a corner case example guide

- dist/formats/news_article/publisher_v2/schema.json
- dist/formats/statistical_data_set/publisher_v2/schema.json
- formats/news_article.jsonnet
- formats/statistical_data_set.jsonnet
https://trello.com/c/b5RLbDyJ/118-users-can-add-a-primary-organisation
We originally added this to support editions links for the new Content
Publisher, but we've since decided not to support this particular
edition link for the forseeable future.
> Remove original org for news/dataset editions

- dist/formats/service_sign_in/frontend/schema.json
- dist/formats/service_sign_in/notification/schema.json
- dist/formats/service_sign_in/publisher_v2/schema.json
- examples/service_sign_in/frontend/service_sign_in.json
- formats/service_sign_in.jsonnet
https://trello.com/c/CbTYssq1/478-enable-cross-domain-tracking-for-cysp-govuk-sign-in-pages
Adds the fields `tracking_code` and `tracking_name` to the service sign in `choose_sign_in` options hash, these can be passed to forms which track radio buttons across domains.
See https://github.com/alphagov/govuk_publishing_components/pull/539 and https://github.com/alphagov/government-frontend/pull/1102 for full implementation
> Add tracking code to service sign in format

- examples/travel_advice_index/frontend/index.json
As per https://github.com/alphagov/frontend/pull/1643 we allow the frontend to support both the old style and new style of `details` multi-level links.
I've done this for only one child travel advice to ensure that it copes with both kinds of formats, once that's all deployed, we can change all of them.
> Update the travel advice index example to support new style links

- examples/travel_advice_index/frontend/index.json
In https://github.com/alphagov/govuk-content-schemas/pull/819 we updated one example, but now that the change has been deployed we can update all of them.
We can see from https://www.gov.uk/api/content/foreign-travel-advice that the links now follow that format.
> Update all country links to use details fields

- examples/travel_advice_index/frontend/index.json
This one was missed in the previous PR https://github.com/alphagov/govuk-content-schemas/pull/820 and it's making https://github.com/alphagov/frontend/pull/1644 fail.
> In #819 we updated one example, but now that the change has been deployed we can update all of them.
> We can see from https://www.gov.uk/api/content/foreign-travel-advice that the links now follow that format.
> Remove extra fields from organisation link details again

- dist/formats/service_sign_in/frontend/schema.json
- dist/formats/service_sign_in/notification/schema.json
- dist/formats/service_sign_in/publisher_v2/schema.json
- examples/service_sign_in/frontend/service_sign_in.json
- formats/service_sign_in.jsonnet
Adds an optional tracking domain attribute to service sign in format. This will allow a per page cross domain tracking configuration rather than relying on the urls in the various options.
> Add tracking domain to service sign in

- Jenkinsfile
https://ci.integration.publishing.service.gov.uk/job/govuk-content-schemas/job/master/811/console
Miniportile is used to retrieve jsonnet from github.
The progress reporter in miniportile can't handle a nil content-length response which github sends with `content-encoding: Chunked`.
There's a fix https://github.com/flavorjones/mini_portile/pull/86
which needs approval for release but we don't know when this will happen.
I've compiled and installed the system libraries on our CI agents to support this temporary measure.
> Add env var to force use of system jsonnet libraries

- Jenkinsfile
The Content Performance Manager processes content, so enable running
it's tests on schema changes, which will hopefully help spot when the
CPM needs updating for schema changes.
> Add the CPM to dependentApplications

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- examples/organisation/frontend/attorney_general.json
- examples/organisation/frontend/charity_commission.json
- examples/organisation/frontend/court.json
- examples/organisation/frontend/number_10.json
- examples/organisation/frontend/tribunal.json
- examples/organisation/frontend/wales_office.json
- lib/schema_generator/format.rb
This adds examples for:
- courts and tribunals pages which are served from under "/courts-tribunals/"
- examples for specific org pages (served from under "/government/organisations/") which enable us to reduce the code in the tests for org pages
Org pages link to several things that don't have base_paths, such as organisation contacts and foi contacts.  The new examples fail the tests unless we can generate linked items without base paths which only currently happens for linked items that are `world_locations`
In theory there is no restriction on which content types are linked, so this check feels a bit like a false safety net because a content item without a base path could be added to any link section.  In practice, this doesn't seem to happen.
I tried removing the requirement for a …
> Remove base_path requirement for some links (and add org examples)

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/notification/schema.json
- dist/formats/contact/frontend/schema.json
- dist/formats/contact/notification/schema.json
- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/notification/schema.json
- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/speech/frontend/schema.json
- dist/formats/speech/notification/schema.json
- dist/formats/world_location_news_article/frontend/schema.json
- dist/formats/world_location_news_article/notification/schema.json
- formats/shared/definitions/frontend_links.jsonnet
As described in https://github.com/alphagov/govuk_publishing_components/pull/595#discussion_r229322211, https://github.com/alphagov/govuk-content-schemas/pull/818 made the `base_path` optional in the `links` for certain schemas. However, those same schemas will still need a `base_path` if they're in nested links.
> Make base_path optional for nested links

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/notification/schema.json
- dist/formats/policy/publisher_v2/schema.json
- examples/finder/frontend/finder.json
- formats/finder.jsonnet
- formats/shared/definitions/finder.jsonnet
This allow sort options to be specified for a finder on a case by case basis.
Required for https://trello.com/c/B8oMuUhi
> Add finder sort property

- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/notification/schema.json
- dist/formats/news_article/publisher_v2/schema.json
- formats/news_article.jsonnet
https://trello.com/c/msxsnIdE/415-stop-sending-political-government-fields-to-publishing-api
Currently each news article must specify whether t is political and
irrespective have an associated government. The logic to do this in
Whitehall is complex and was implemented in a rush when there was a
change of government; we don't want to do this in Content Publisher.
Rather than send junk or inaccurate data to the Publishing API, it seems
we can avoid specifying these fields without causing issues downstream.
* https://github.com/alphagov/finder-frontend/blob/master/app/views/finders/_results.mustache
* https://github.com/alphagov/government-frontend/blob/7942c6f20dfac7f99c572b9a20e3c4fb7463c8c4/app/presenters/content_item/political.rb
* …
> Stop requiring government/political for news

- examples/specialist_document/frontend/aaib-reports.json
- examples/specialist_document/frontend/asylum-support-decision.json
- examples/specialist_document/frontend/cma-cases.json
- examples/specialist_document/frontend/countryside-stewardship-grants.json
- examples/specialist_document/frontend/drug-device-alerts.json
- examples/specialist_document/frontend/drug-safety-update.json
- examples/specialist_document/frontend/employment-tribunal-decision.json
- examples/specialist_document/frontend/eu-withdrawal-act-2018-statutory-instruments.json
- examples/specialist_document/frontend/european-structural-investment-funds.json
- examples/specialist_document/frontend/export-health-certificates.json
- examples/specialist_document/frontend/international-development-funding.json
- examples/specialist_document/frontend/maib-reports.json
- examples/specialist_document/frontend/raib-reports.json
- examples/specialist_document/frontend/residential-property-tribunal-decision.json
- examples/specialist_document/frontend/tax-tribunal-decision.json
- examples/specialist_document/frontend/utaac-decision.json
We are aiming to reduce the number of fields included in link expansion so that the payload size is smaller, and we are only including the ones we actually need. This commit updates the content schema examples for the `specialist_document`s affected to make sure apps won't break.
Related PR: https://github.com/alphagov/publishing-api/pull/1380
Trello card: https://trello.com/c/HHBxFrJr/612-do-not-expand-unnecessary-links-for-finder
> Remove extra fields from finder link details hash

- dist/formats/contact/frontend/schema.json
- dist/formats/contact/notification/schema.json
- dist/formats/contact/publisher_v2/schema.json
- formats/contact.jsonnet
We can't rely on this as a required field at the moment as Whitehall
currently has 448 (see below) items with a street address and no
postal code. There is not any validation to require the post code.
Most unfortunate is that often the region, locality and postal code are
bunged into the street address field.
```
irb(main):001:0> Contact.find_each.select { |c| c.postal_code.empty? && c.street_address.present? }.count
=> 448
```
>  Remove postal code from required contact fields

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/policy/frontend/schema.json
- dist/formats/policy/notification/schema.json
- dist/formats/policy/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
Adds to the permitted base filters for finders.
This allows us to filter arbitrary documents associated to a particular finder.
See: https://github.com/alphagov/rummager/pull/1330
> Amend finder filters

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
This PR adds a new field to the finder format to allow for a flag. The flag determines whether the filter description at the top of a filtered finder displays a constructed sentence of all the selected filters, or a generic description.
> Add flag for finder generic description

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Adding a missing region.
Trello card: https://trello.com/c/d8vArNoY/354-add-south-west-region-to-finance-and-support-for-your-business-finder
> Add 'South West' to business finance support finder

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- examples/organisation/frontend/organisation.json
- formats/organisation.jsonnet
For https://trello.com/c/3aDALgY4/416-we-should-expose-default-organisation-images-to-the-publishing-api
> Add default_news_image field to organisation schema

- dist/formats/transaction/frontend/schema.json
- dist/formats/transaction/notification/schema.json
- dist/formats/transaction/publisher_v2/schema.json
- examples/transaction/frontend/transaction-with-variants.json
- formats/transaction.jsonnet
This commit adds a `variant` field to the `transaction` schema. Each `variant` has a number of fields related to those of the parent content item, as well as a `slug`. When a variant of a transaction is accessed via `/name-of-transaction/slug-of-variant`, the fields that are defined for the variant are rendered in preference to those of the parent content item.
RFC: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-097-verify-specific-start-pages.md
> Add variants for transactions

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
This allows us to set one or more taxonomy topics as a base filter.  The `all` prefix means that they would potentially then be used in an `AND` style query with another taxonomy topic.
We only need it for one topic at the moment, but it'd be tricky to expand later so we'll start with allowing more than one.
I sorted the list of filters in the first commit, as it's getting longer than it was.  A-Z is hopefully easier to read.  It doesn't change the generated output.
I don't see the need for this in the reject list yet.
> Add "all" part of taxonomy tree to filters

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
This will be used to perform an OR operation between facets of a finder, compared to the current default of an AND.
[Trello Card](https://trello.com/c/HoWR8kQM/150-or-between-and-in-facets-in-the-finder)
> Add 'operator_between_facets' field

- Gemfile.lock
- Jenkinsfile
We've had issues installing jsonnet gem for a while due to problems with mini_portile: https://github.com/flavorjones/mini_portile/pull/86 which we patched with https://github.com/alphagov/govuk-content-schemas/pull/824
This updates the gems so we have the new mini_portile 2.4 with the fix and can undo our patch.
> Fix the jsonnet mini_portile install issue

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
- formats/shared/definitions/finder.jsonnet
Say you have a business in the agriculture sector, and you export to
the EU.  If "sector" and "exporting" are facets, then the current AND
combining works:
sector && exporting
If you also employ EU citizens, and that's a new facet, then you get
this situation:
sector && exporting && employing
Which is unlikely to return what you want.  Why would a document be
tagged to all three?
What you actually want is something like this:
sector && (exporting || employing)
This PR adds a field to each facet to say how to combine it.  The
field is optional.
This replaces PR #847 with a more generic solution.
---
[Trello card](https://trello.com/c/HoWR8kQM/150-or-between-and-in-facets-in-the-finder)
> Add a "combine_mode" to finder facets

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
We need to use them in citizen finders
https://trello.com/c/UDfCG0jA/184-add-foreign-travel-advice-index-to-going-abroad-finder
> Add content store document types to finder filters

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
These are required for the checkbox facet (aka Show only Brexit) and the
cascading drop down (aka the taxons selector) to work.
https://trello.com/c/oE1sdBdt/278-add-ability-to-publish-news-and-communications-finder-from-rummager
> Add finder properties required for new facets

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
https://trello.com/c/HZHHKXc8/311-make-it-possible-to-publish-news-and-communications-email-alert-content-item-from-rummager
This adds the details.filter attribute, so one can set default filters on an email signup, like on finders.
It also makes facet options optional, enabling us to set dynamic facets which don't have options hard coded into the email signup content item. One example of this is a people filter which is often changing.
> Allow finder email signup extensions

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
https://trello.com/c/ylw7DDQa/329-enable-email-alert-api-to-reject-a-content-purpose-supergroup
This enables use to reject a content purpose supergroup on email signup
pages. This is similar to the finder content items.
Blocks https://github.com/alphagov/rummager/pull/1422
> Add reject.content_purpose_supergroup to email_signup

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- examples/finder/frontend/statistics.json
- formats/shared/definitions/finder.jsonnet
- formats/shared/definitions/label_value_pair.jsonnet
Update schemas to include recent finder frontend changes. Specifically:
- add `option_lookup` for mapping keys to values that can be used to associate `allowed_values` with multiple values
- add `default` option for `label_value_pair`, so that radio facets can have a default option
- add `hide_facet_tag` key radio facets, where we don't want it to have a facet tag when an option is chosen. This is because radios have to have a default value, so removing it (via the facet tag) is confusing, because it can't be removed, only set to the default state.
Partly related to: https://github.com/alphagov/finder-frontend/pull/922
Trello card: https://trello.com/c/pNXeZLrW/403-introduce-subset-of-supergroup-facet-behaviour-on-stats-finder-m
> Add recent finder-frontend schema changes

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/links.json
- formats/finder.jsonnet
https://trello.com/c/ZTNhqTpb/282-finders-get-facet-definition-from-publishing-api
Allows an expanded `facet_group` to be linked to a finder. This should replace static facet definitions in `details["facets"]`.
> Link facet group to finder

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder_email_signup/publisher_v2/finder_email_signup_multi_facet.json
- formats/finder_email_signup.jsonnet
Similar to the finder facet option_lookup field,
this enables one to carry the same behaviour
(associating a single displayed value with multiple
values behind the scenes) from a finder to the email
signup page.
This will enable publication of the policy and consultations email signup page.
Related to https://github.com/alphagov/finder-frontend/pull/936.
https://trello.com/c/tIXZB4LG/482-make-post-review-changes-to-policy-papers-and-consultations-finder
> Add option lookup to finder email signup

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/export-health-certificates.json
- formats/shared/definitions/_specialist_document.jsonnet
Adds 'Sweden' as a destination country because it was missing from the export health certificate (EHC) finder.
[Trello card](https://trello.com/c/dZIPRphR/826-add-sweden-and-remove-northern-ireland-exception-copy-from-the-exports-form-finder)
> Add Sweden to the export health certificate (EHC) finder

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/export-health-certificates.json
- formats/shared/definitions/_specialist_document.jsonnet
Add 'Great Britain' as a destination country because it was missing from the export health certificate (EHC) finder.
[Trello card](https://trello.com/c/dZIPRphR/826-add-sweden-and-remove-northern-ireland-exception-copy-from-the-exports-form-finder)
> Add ‘Great Britain’ to the export health certificate (EHC) finder

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- examples/finder/frontend/all_content.json
- formats/finder.jsonnet
- formats/shared/definitions/finder.jsonnet
Specifically adds the `hide_facets_by_default` attribute, which is required for https://github.com/alphagov/finder-frontend/pull/960
Trello card: https://trello.com/c/Fy8KPoWV/501-all-content-show-hide-facets
> Add all content finder schema

- dist/formats/facet/frontend/schema.json
- dist/formats/facet/notification/schema.json
- dist/formats/facet/publisher_v2/schema.json
- formats/facet.jsonnet
https://trello.com/c/ZTNhqTpb/282-finders-get-facet-definition-from-publishing-api
The finder content item definition can be linked to the facet group this expands to include the facets so make sure facets are of the expected `content_id` type which means they will filter based on links to `facet_value` content items.
See https://github.com/alphagov/finder-frontend/pull/944/commits/f8e8f4320e37c408a7ffe4533a5491d34f8b6dce for proposed finder implementation
> Add content id facet type

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
This will enable us to send an array of values to the email-alert-api, while only displaying one value on the email signup page checkboxes.
An example use case:
```
{
"facet_id": "content_store_document_type",
"facet_name": "Document types",
"facet_choices": [
{
"key": "statistics_published",
"filter_values": ["statistics", "national_statistics", "statistical_data_set", "official_statistics"],
"radio_button_name": "Statistics (published)",
"topic_name": "Statistics (published)",
"prechecked": false
},
{
"key": "research",
"filter_values": ["dfid_research_output", "independent_report", "research"],
"radio_button_name": "Research",
"topic_name": "Research",
"prechecked": false
}
]
},
```
https://trello.com/c/qBt4q04L/548-prevent-users-from-subscribing-to-email-alerts-of-upcoming-statistics
> Email signup filter values

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
We want to allow filtering email subs by topic.
This corresponds with a Citizen Readiness finder: alphagov/rummager@87fc52b
Initially we're setting this up to just allow signups to a particular topic, but in future we want to allow combinations of eg brexit AND education
> Allow email subs with taxonomy filters

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
We are replacing `appear_in_find_eu_exit_guidance_business_finder` with `facet_groups` to 
query for things appearing in the EU exit business readiness finder,
The schema is preventing us from doing that.
Trello: https://trello.com/c/Sd7omEFH/263-mapping-rummager-request-response-in-finder-frontend
> Allow facet groups as filter in finder

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/finder.jsonnet
We have some finders that we don't want to appear in external searches because they support other content rather than being useful in isolation.
Rather than hard coding the configuration in finder-frontend, it would be useful to be able to configure it finder by finder.
(This isn't used by any frontend code at the moment)
> Add ability to no-index a finder

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- examples/finder/frontend/statistics.json
- formats/shared/definitions/finder.jsonnet
A new research_and_statistics facet was introduced to Finder Frontend.
trello: https://trello.com/c/mkf4eUXF/593-bug-stats-finder-displaying-wrong-number-of-published-stats-docs
trello: https://trello.com/c/QpM8Vhwv/590-bug-stats-finder-is-only-displaying-a-few-upcoming-stats-docs
github: https://github.com/alphagov/finder-frontend/pull/1053
> Add research_and_statistics type to finder schema

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder/frontend/news-and-communications.json
- examples/finder_email_signup/frontend/news-and-communications-email-signup.json
- formats/finder_email_signup.jsonnet
- formats/shared/definitions/finder.jsonnet
Trello: https://trello.com/c/hG5slHr3/667-exclude-specialist-doc-types-from-news-n-comms-finder
github: https://github.com/alphagov/search-api/pull/1521
> Add content_purpose_subgroup to filter options in finder schema

- examples/homepage/publisher_v2/service_manual_homepage.json
- examples/service_manual_guide/frontend/point_page.json
- examples/service_manual_homepage/frontend/service_manual_homepage.json
- examples/service_manual_homepage/publisher_v2/service_manual_homepage.json
- examples/service_manual_service_standard/frontend/service_manual_service_standard.json
- examples/service_manual_service_standard/publisher_v2/service_manual_service_standard.json
- examples/service_manual_service_toolkit/frontend/service_manual_service_toolkit.json
- examples/service_manual_service_toolkit/publisher_v2/service_manual_service_toolkit.json
- examples/service_manual_topic/frontend/service_manual_topic.json
The Digital Service Standard is being renamed to the Government Service Standard. The number of points in the standard will also be reduced from 18 to 14.
Whilst these are only examples, changing these allows us to be consistent in the tests in service manual frontend and service manual publisher, which rely on these example schemas.
> [DO NOT MERGE] Rename Service Standard

- examples/taxon/frontend/taxon_in_alpha_phase.json
- examples/taxon/frontend/taxon_with_associated_taxons.json
- examples/taxon/frontend/taxon_with_child_taxons.json
Trello: https://trello.com/c/uR7v1Rri
Adds `phase` property to the existing taxon examples and new example that’s in the alpha phase.
This makes the taxon examples more consistent with what it is generated in the content-store.
> Add taxon examples with phases

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- formats/organisation.jsonnet
https://trello.com/c/OcuVomSb/820-determine-the-alternative-format-email-address-for-an-attachment
This adds a new field to store an email that specifies how a user can
request an alternative format from the organisation e.g. for an
attachment.
> Add alternative format email for orgs

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
Adds an additional possible rejection filter to the finder schema, so we can block results with particular links. This is being done as part of [this ticket](https://trello.com/c/qAwjASRS/176-remove-the-search-page-from-search-results-searchception-s)
> Link reject finders

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
This [Specialist Publisher PR](https://github.com/alphagov/specialist-publisher/pull/1431) adds some additional fields to the Service Standard Reports stage facet
[trello](https://trello.com/c/FjYzSTIh/1008-add-new-facet-options-to-service-standard-reports-finder)
> Add new fields to service standard reports

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- examples/finder/frontend/official-documents-finder.json
- formats/shared/definitions/finder.jsonnet
Adds `has_official_documents` to the list of fields that a finder can filter on.
See trello card [724](https://trello.com/c/6xFJqfAw/724-spin-up-finder-for-content-that-has-official-doc-status-s)
> Adds official_documents filter to finder schema

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
This parameter will be added to email-alert-api
and a finder-frontend will need to pass it to
the api selectively.
Existing finders will want to continue using
'and' (which can be represented either with
a blank string or omitting the parameter)
while the business finder will want to use
'or' joining
Trello: https://trello.com/c/vLZ7zTdR/132-add-parameter-to-finder-frontend-to-make-email-alert-api-know-this-finder-is-special
> Add combine_mode to email alert signup

- dist/formats/corporate_information_page/frontend/schema.json
- dist/formats/corporate_information_page/notification/schema.json
- dist/formats/corporate_information_page/publisher_v2/schema.json
- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- formats/corporate_information_page.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
https://trello.com/c/Wb01UcFK/1046-add-accessibility-statement-to-list-of-corporate-information-for-organisations-whitehall-publisher
> Add accessibility statement as corporate information page type

- examples/guide/frontend/guide.json
This PR updates the `guide` example to add `suggested_ordered_related_items`. This is used as part of tests within `government-frontend` to ensure `ordered_related_items` is not overwritten with `suggested_ordered_related_items` if existing `ordered_related_items` exist.
> Update guide example to add suggested_ordered_related_items

- dist/formats/completed_transaction/frontend/schema.json
- dist/formats/completed_transaction/notification/schema.json
- dist/formats/completed_transaction/publisher_v2/schema.json
- examples/completed_transaction/frontend/completed_transaction_with_organ_donor_promotion.json
- formats/completed_transaction.jsonnet
The content of this promotion page will be changing to include two URLs, an opt in and an opt out URL.
This adds new optional `opt_in_url` and `opt_out_url` fields to the promotion.
Once all the content items for this schema have been moved over to use these URLs, we can mandate that they are required and remove `url` from the required list.
I've implemented this by adding support for custom list of `requires` depending on the promotion category. See https://stackoverflow.com/a/38781027 for more information.
[Trello Card](https://trello.com/c/HFsNGxTy/1088-investigate-organ-donation-promos-on-done-pages)
> Add opt in and opt out URL for organ donor promotion

- Jenkinsfile
All the repositories now work the same, so there's no need to keep
this configuration option.
> Remove the redundant wait configuration for downstream jobs

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Attempting to create a document which applies to all countries fails
with errors about Jamaica, Lebanon, and the Ivory Coast.  Jamaica and
Lebanon are failing because they should be lowercase (fixed in
specialist-publisher), Ivory Coast is failing because it's missing
from the schema.
---
[Trello card](https://trello.com/c/3CyH4j89/892-specialist-publisher-schema-validation-errors)
>  Add ivory-coast to allowed countries for UK MCABs

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- dist/formats/organisations_homepage/frontend/schema.json
- dist/formats/organisations_homepage/notification/schema.json
- dist/formats/organisations_homepage/publisher_v2/schema.json
- formats/organisation.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
**What**
Any organisation that has a tribunal type is labelled 'tribunal non-departmental public body'.
However, many organisations are tribunal bodies but are departmental public bodies (such as HMCTS). There is only one type tag available (non-DPB), so we should rename this type as 'Tribunal' to cover both types of organisations.
**Why**
Not all organisations fit into the current type tagging. The current tag is very specific - we should make it easier for publishers by changing the type name to a more generic 'Tribunal'.
https://trello.com/c/KHXlOF6V/1191-change-organisation-type-tribunal-non-departmental-public-body-to-tribunal
> Add tribunal organisation type

- Jenkinsfile
As rummager was renamed to the search-api quite a while ago.
> Switch rummager -> search-api in dependant applications

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- examples/step_by_step_nav/frontend/step_by_step_nav.json
- examples/step_by_step_nav/publisher_v2/step_by_step_nav.json
- formats/shared/definitions/_step_by_step_nav.jsonnet
This is being removed as it was confusing users so should be removed from schemas
Pr to remove "optional" from Collections publisher
https://github.com/alphagov/collections-publisher/pull/787
Trello card
https://trello.com/c/P1mSis5e/97-hide-optional-vs-essential-question-when-editing-step
> Remove the "optional" option from Step by Step pages

- dist/formats/completed_transaction/frontend/schema.json
- dist/formats/completed_transaction/notification/schema.json
- dist/formats/completed_transaction/publisher_v2/schema.json
- formats/completed_transaction.jsonnet
- The government has a goal to reach zero carbon emissions by 2050, and
electric cars are part of that.
- Content designers can now select "electric vehicles" as their promo of
choice.
- These schemas need to be updates to include 'electric_vehicle' as a
valid option.
https://trello.com/c/FmE5xU1p/1478-3-add-new-bespoke-message-to-specific-completed-transaction-pages
> Done pages have a new 'electric vehicle' promo choice

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- formats/role.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
This is a type of Role in Whitehall so we need to support it in the Publishing Platform: https://github.com/alphagov/whitehall/blob/master/app/models/chief_scientific_advisor_role.rb
If not, client will see errors like this:
```
[{"schema":{"scheme":null,"user":null,"password":null,"host":null,"port":null,"path":"e29a5603-3a91-513e-9973-e93805f4ea89","query":null,"fragment":null},"fragment":"#/document_type","message":"The property '#/document_type' value \"chief_scientific_advisor_role\" did not match one of the following values: ambassador_role, board_member_role, chief_professional_officer_role, chief_scientific_officer_role, deputy_head_of_mission_role, governor_role, high_commissioner_role, military_role, ministerial_role, special_representative_role, traffic_commissioner_role, …
```
> Add chief_scientific_advisor_role

- dist/formats/role_appointment/frontend/schema.json
- dist/formats/role_appointment/notification/schema.json
- dist/formats/role_appointment/publisher_v2/schema.json
- formats/role_appointment.jsonnet
This adds two new fields to role appointments to support the new reverse links. This came out of comments on https://github.com/alphagov/publishing-api/pull/1645.
This will be set to true if the role appointment is "current". Another way of finding this out is to look at whether then `ended_on` field is set, but I thought it would be good to pull this out as denormalised data to simplify the logic of the frontends.
This is a new field on role appointments which can be used to order appointments with the same `started_on` date by "importance".
This is used to order the appointments in some places on the frontend, notably the title which gets shown above the name of the person.
An alternative to putting this into the role appointment would be a field in the person, but that adds a …
> Add more fields to role appointments

- dist/formats/person/frontend/schema.json
- dist/formats/person/notification/schema.json
- dist/formats/person/publisher_v2/schema.json
- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/person.jsonnet
- formats/role.jsonnet
All the people and roles have been republished from Whitehall now so the links no longer exist. Instead we can use the reverse links put in my the Publishing API.
See alphagov/publishing-api#1645 for more information.
[Trello Card](https://trello.com/c/roHfuPUV/1549-8-use-reverse-links-for-role-appointments)
> Remove old role appointment links

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
This updated the finder email signup schema to enable users to subscribe to email alerts for updates made across a document type.
Content store document type will typically be used as a default email filter by specialist finders in the case that the user has selected no specific email filter facets.
Related to https://github.com/alphagov/specialist-publisher/pull/1540
https://trello.com/c/OPAcIhIF/1193-cannot-sign-up-to-email-alerts-when-no-facets-are-selected
> Add document_type property to finder email signup schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- examples/organisation/frontend/organisation.json
- formats/organisation.jsonnet
We want to present organisations political status from Whitehall to Publishing
API so we can use this information in Content Publisher. It is currently
hardcoded in the YAML file and requires manual updates.
[Trello card](https://trello.com/c/zHm2B8VX/1242-present-organisation-political-status-from-whitehall-to-publishing-api)
> Add political status to organisations schema

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- examples/organisation/frontend/organisation.json
- formats/organisation.jsonnet
Renamed due to 'political' already in use and an overloaded term.
[Trello card](https://trello.com/c/zHm2B8VX/1242-present-organisation-political-status-from-whitehall-to-publishing-api)
> Rename political to organisation_political

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/notification/schema.json
- dist/formats/consultation/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/notification/schema.json
- dist/formats/document_collection/publisher_v2/schema.json
- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/notification/schema.json
- dist/formats/news_article/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- dist/formats/speech/frontend/schema.json
- dist/formats/speech/notification/schema.json
- dist/formats/speech/publisher_v2/schema.json
- dist/formats/statistical_data_set/frontend/schema.json
- dist/formats/statistical_data_set/notification/schema.json
- dist/formats/statistical_data_set/publisher_v2/schema.json
- dist/formats/world_location_news_article/frontend/schema.json
- dist/formats/world_location_news_article/notification/schema.json
- dist/formats/world_location_news_article/publisher_v2/schema.json
- formats/shared/definitions/_whitehall.jsonnet
Since https://github.com/alphagov/govuk-content-schemas/pull/936 we are switching the GOV.UK stack to use links to share government information rather than the details attribute.
With the preference for this the government information in the details will slowly slip out of date and thus should not be used.
> Deprecate government in details body

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Trello: https://govuk.zendesk.com/agent/tickets/3867807
Related to: https://github.com/alphagov/specialist-publisher/pull/1546
Adds a new Tennant Fees Act category and sub-categories to the residential property finder
> Add new Tenant Fees Act category

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder_email_signup/frontend/cma-cases-email-signup.json
- examples/finder_email_signup/frontend/news-and-communications-email-signup.json
- examples/finder_email_signup/frontend/raib-report-email-signup.json
- examples/finder_email_signup/publisher_v2/finder_email_signup.json
- formats/finder_email_signup.jsonnet
These fields are no longer be used by finder-frontend or specialist publisher so can be removed from the schemas.
This PR depended on these PRs being merged and deployed (done):
- https://github.com/alphagov/specialist-publisher/pull/1555
- https://github.com/alphagov/finder-frontend/pull/1831
https://trello.com/c/otcTG22f/1246-email-alert-signup-tech-debt
> Remove finder email signup keys

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder_email_signup/frontend/cma-cases-email-signup.json
- examples/finder_email_signup/publisher_v2/finder_email_signup.json
- formats/finder_email_signup.jsonnet
The required boolean on email facets will enable us to
specify in the content item whether a facet must have a
value. This is useful for CMA cases and Research and Statistics
finder email signup content items.
https://trello.com/c/NS1ZPbBF/1249
> Add required field to email signup facets

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder_email_signup/frontend/cma-cases-email-signup.json
- formats/finder_email_signup.jsonnet
Related to https://github.com/alphagov/specialist-publisher/pull/1563
We want to permit format as a default filter in email signups.
https://trello.com/c/yLsG8ecR/1292-fix-specialist-publisher-email-signups
> Add format to permitted filter fields

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/notification/schema.json
- dist/formats/case_study/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/notification/schema.json
- dist/formats/document_collection/publisher_v2/schema.json
- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/notification/schema.json
- dist/formats/html_publication/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- formats/case_study.jsonnet
- formats/detailed_guide.jsonnet
- formats/document_collection.jsonnet
- formats/html_publication.jsonnet
- formats/publication.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
Adds the possibility to add a notice to Whitehall content explaining where updated content is.
The links can be external or internal. A title has to be provided for each link.
https://trello.com/c/0URepvoe/270-update-whitehall-content-schema-to-include-a-no-deal-notice
> Add brexit no deal notice

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- examples/finder/frontend/all_content.json
- formats/finder.jsonnet
- formats/shared/definitions/finder.jsonnet
As of alphagov/search-api@1ce164d this field will no longer be used.
Should be merged and deployed after alphagov/search-api#1920 has gone out.
https://trello.com/c/PtSyQ5hi/1285-show-facets-by-default
> Remove hide facets by default field

- dist/formats/finder/frontend/schema.json
- dist/formats/finder/notification/schema.json
- dist/formats/finder/publisher_v2/schema.json
- formats/shared/definitions/finder.jsonnet
Trello: https://trello.com/c/qBM5QLID/482-business-finder-tech-debt
`appear_in_find_eu_exit_guidance_business_finder` is old technical debt surfaced [as part of removing the business finder](https://github.com/alphagov/search-api/pull/1967).
>It looks like the appear_in_find_eu_exit_guidance_business_finder checkbox approach was >replaced the facet_groups approach:
>
>    alphagov/finder-frontend@6f484a6
>    https://github.com/alphagov/search-api/pull/1535/files
>
>The finder content schema needs to have appear_in_find_eu_exit_guidance_business_finder removed too: https://github.com/alphagov/govuk-content-schemas/blob/master/formats/shared/definitions/finder.jsonnet#L51.
Removes `appear_in_find_eu_exit_guidance_business_finder` from:
- Finder Frontend schema json
- Finder Notification …
> Remove appear_in_find_eu_exit_guidance_business_finder

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/notification/schema.json
- dist/formats/consultation/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- formats/consultation.jsonnet
- formats/publication.jsonnet
Two problems with the way it was done before:
1. The `multiple_content_types` schema means that all of the things are *different representations of the same content*, and so content-store only returns the *first* `text/html` found.  And not the full list as I'd assumed.
2. Consultations have a few more types of documents which need to be attachments-ised.
Immediate solution to (1) is to wrap the featured attachments in an array, so we have an array of arrays.  Long term solution to (1) (which may not be feasible) would be to make the semantics really clear, by changing it to a hash, where keys are content types and values are representations.
[Trello card](https://trello.com/c/ZTfLGWYT/1387-get-whitehall-sending-attachments-featuredattachments-data-to-publishing-api)
> Get featured attachments working properly

- dist/formats/consultation/frontend/schema.json
- dist/formats/consultation/notification/schema.json
- dist/formats/consultation/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/notification/schema.json
- dist/formats/document_collection/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- dist/formats/speech/frontend/schema.json
- dist/formats/speech/notification/schema.json
- dist/formats/speech/publisher_v2/schema.json
- dist/formats/statistical_data_set/frontend/schema.json
- dist/formats/statistical_data_set/notification/schema.json
- dist/formats/statistical_data_set/publisher_v2/schema.json
- formats/consultation.jsonnet
- formats/detailed_guide.jsonnet
- formats/document_collection.jsonnet
- formats/publication.jsonnet
- formats/speech.jsonnet
- formats/statistical_data_set.jsonnet
Usage of government in a details hash is deprecated following the change
of #943, because
of this it shouldn't be required for any document types. This removes
all the required options.
> Remove required government attributes

- dist/formats/world_location_news_article/frontend/schema.json
- dist/formats/world_location_news_article/notification/schema.json
- dist/formats/world_location_news_article/publisher_v2/schema.json
- formats/world_location_news_article.jsonnet
The links to governments are now used for associating content with
governments.
> Remove government from required world location news article list

- dist/formats/corporate_information_page/frontend/schema.json
- dist/formats/corporate_information_page/notification/schema.json
- dist/formats/corporate_information_page/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/news_article/frontend/schema.json
- dist/formats/news_article/notification/schema.json
- dist/formats/news_article/publisher_v2/schema.json
- dist/formats/working_group/frontend/schema.json
- dist/formats/working_group/notification/schema.json
- dist/formats/working_group/publisher_v2/schema.json
- dist/formats/world_location_news_article/frontend/schema.json
- dist/formats/world_location_news_article/notification/schema.json
- dist/formats/world_location_news_article/publisher_v2/schema.json
- formats/corporate_information_page.jsonnet
- formats/detailed_guide.jsonnet
- formats/news_article.jsonnet
- formats/working_group.jsonnet
- formats/world_location_news_article.jsonnet
Prior to this being merged https://github.com/alphagov/whitehall/pull/5448 will have to be merged and deployed to production.
Previously all of these documents were set to use the publication attachment schemas, however none of these documents make use of publication specific fields or types. Thus this reduces the options that can apply at a schema level for them.
@barrucadu I've opened this up and marked it as a draft prior to you get your input on this. I'm wondering if there was a reason these document types were set as publication attachment assets in the first place that I've missed and/or if there are consequences to this change? might it break any Whitehall document types.
> Set Whitehall document attachments to be file_attachment_asset

- dist/formats/ministers_index/frontend/schema.json
- dist/formats/ministers_index/notification/schema.json
- dist/formats/ministers_index/publisher_v2/links.json
- dist/formats/ministers_index/publisher_v2/schema.json
- formats/ministers_index.jsonnet
The ministers index is currently rendered by Whitehall. The aim is to get this out of Whitehall and into Collections, therefore, this schema creation will give us useful information.
Trello card: https://trello.com/c/J8HCsPIV/1823-5-add-a-content-schema-for-ministers-index-page
> Create ministers index schema

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- lib/govuk_content_schemas/allowed_document_types.yml
Adds a placeholder coronavirus_landing_page document type so that we can spike a possible publishing workflow for the coronavirus landing page. 
https://trello.com/c/0uZVAYYt/35-look-at-options-for-publishers-to-update-page
> Coronavirus document type

- examples/consultation/frontend/consultation_outcome_with_featured_attachments.json
- examples/publication/frontend/publication-with-featured-attachments.json
https://trello.com/c/wM9wqe9H/1587-support-featured-attachments-directly-on-govuk-frontend
Previously we relied on pre-rendered HTML for the attached 'documents'
of publications and consultations. This adds an example to support work
to directly render attachments based on metadata in the payload, and an
array of featured attachment IDs. See RFC 116 for more details.
https://github.com/alphagov/govuk-rfcs/blob/master/rfc-116-store-attachment-data-in-content-items.md
> Add new examples for direct attachment rendering

- corona_page_complex.jsonnet
- dist/formats/coronavirus_landing_page/frontend/schema.json
- dist/formats/coronavirus_landing_page/notification/schema.json
- dist/formats/coronavirus_landing_page/publisher_v2/links.json
- dist/formats/coronavirus_landing_page/publisher_v2/schema.json
- examples/coronavirus_landing_page/frontend/coronavirus_page.json
- formats/coronavirus_landing_page.jsonnet
Once this is merged I will update the the schema name of the [content item](https://www.integration.publishing.service.gov.uk/api/content/coronavirus) from `generic` to `coronavirus_landing_page`
> Define new coronavirus_landing_page schema

- lib/schema_generator/format.rb
These lint violations, introduced 3 years ago, are causing other apps to fail.
See: https://ci.integration.publishing.service.gov.uk/job/govspeak/job/bump-govuk-publishing-components-to-21.4/2/console
> Fix lint violations

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- lib/govuk_content_schemas/allowed_document_types.yml
This document type is not used and should now be removed.
Trello:
https://trello.com/c/ygOqmhWw/1921-remove-legacy-placeholderworkinggroup-code-data-from-govuks-codebase
> Remove placeholder_working_group

- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/role.jsonnet
If the role is ministerial we want to present the ministers index page.
Trello: https://trello.com/c/i1ffrXiZ/1913-5-link-ministers-to-the-government-ministers-content-item
> Add ministerial to roles

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
[Marine notices](https://specialist-publisher.integration.publishing.service.gov.uk/marine-notices) should apparently be allowed to have multiple vessel types and topics.  There's no content for this yet, so it's fine to change.
Reviewing while ignoring whitespace might help.
I'll remove the part that allows single tagging once this has been successfully built/deployed.  It's required to be there for now otherwise the specialist publisher build fails
Half of https://github.com/alphagov/specialist-publisher/pull/1636
> Allow multiple marine notice vessel types/topics

- Jenkinsfile
The app has been retired.
[Trello Card](https://trello.com/c/SKT4BnIQ/1953-retire-the-calendars-app-%F0%9F%8D%90)
> Remove calendars dependant app

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- examples/organisation/frontend/attorney_general.json
- examples/organisation/frontend/charity_commission.json
- examples/organisation/frontend/court.json
- examples/organisation/frontend/number_10.json
- examples/organisation/frontend/organisation.json
- examples/organisation/frontend/tribunal.json
- examples/organisation/frontend/wales_office.json
- formats/organisation.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
- lib/schema_generator/format.rb
We now have this information in the links rather than in the details hash so we don't need these in the schema anymore.
See https://github.com/alphagov/whitehall/pull/5575 for more details.
[Trello Card](https://trello.com/c/NRhnejWA/1942-5-send-links-to-people-instead-of-details-hash-in-the-organisations-in-whitehall)
> Remove details-based people links

- examples/service_manual_service_standard/frontend/service_manual_service_standard.json
- examples/service_manual_topic/frontend/service_manual_topic.json
- examples/service_manual_topic/publisher_v2/service_manual_topic_links.json
https://trello.com/c/KNWv9Dgx/258-deprecate-and-remove-legacy-email-signup-pages
This removes legacy email-signup links from service manual examples,
since these formats no longer include them [1].
[1]: https://github.com/alphagov/service-manual-publisher/pull/813
> Remove email-signup links for manual examples

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/finder/frontend/drug-safety-update.json
- examples/specialist_document/frontend/drug-safety-update.json
- formats/shared/definitions/_specialist_document.jsonnet
This refers to https://www.gov.uk/drug-safety-update which is edited by
MHRA (Medicines and Healthcare products Regulatory Agency) in
https://specialist-publisher.publishing.service.gov.uk/drug-safety-updates
This is needed because they are launching a major new, lengthy project
on medicines and pregnant women, so will have a lot more content in this
area going forward, and wish to allow users to group existing content on
these topics closely together.
The request to add these two Therapeutic Areas came through Zendesk:
https://govuk.zendesk.com/agent/tickets/4099517
Related PRs:
- https://github.com/alphagov/specialist-publisher/pull/1657
- https://github.com/alphagov/search-api/pull/2113
> Add Pregnancy and Breasfeeding Therapeutic Areas

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/ministers_index/frontend/schema.json
- dist/formats/ministers_index/notification/schema.json
- dist/formats/ministers_index/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- formats/ministers_index.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
I realised while writing tests for a new presenter in whitehall that the new
`ministers_index` schema had not been added to `allowed_types.yml`. This was
giving a `Factory not registered` error.
Presenter card for reference: https://trello.com/c/I92GWawi/2027-3-write-ministers-index-presenter
> Add ministers index to allowed types

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- formats/finder_email_signup.jsonnet
https://trello.com/c/Qr1IO25y/363-audit-all-email-signup-pages-to-understand-why-they-exist
Depends on: https://github.com/alphagov/search-api/pull/2152
This is no longer used [1].
[1]: https://github.com/alphagov/search-api/pull/2152
> Remove redundant "reject" field for finder signups

- dist/formats/finder_email_signup/frontend/schema.json
- dist/formats/finder_email_signup/notification/schema.json
- dist/formats/finder_email_signup/publisher_v2/schema.json
- examples/finder_email_signup/frontend/cma-cases-email-signup.json
- formats/finder_email_signup.jsonnet
https://trello.com/c/Qr1IO25y/363-audit-all-email-signup-pages-to-understand-why-they-exist
As part of uncovering the history of finder email signups,
I came across a number of fields that confused me because
they are no longer used. Although we could just mark them
as 'deprecated', I don't see any reason to avoid deleting
them altogether, which is what this PR does.
Please see the commits for more details.
> Remove redundant fields for finder email signup

- Jenkinsfile
`lintRuby` was removed in an earlier govuk-jenkinslib PR
(alphagov/govuk-jenkinslib#74)
and has been seperately added to the default rake task for this repo
(#998)
> Remove lintRuby jenkinsfile

- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/role.jsonnet
Add new `seniority` optional field to `details` in the role schema
Part of the work to migrate rendering of the government/ministers page
from whitehall to collections.
Detailed here: https://trello.com/c/T6u4LjxS/2062-3-add-sorting-information-to-ministers-content-item
and here: https://trello.com/c/loAlkIp7/1715-8-migrate-government-ministers-to-collections
> Add new seniority optional field to details in the role schema

- examples/publication/frontend/tagged_to_two_coronavirus_taxons.json
When Coronavirus content is tagged to more than one taxon, we chose only one to use as the 'superbreadcrumb'.
This example sets up some content tagged to two different coronavius taxons:
- b7f57213-4b16-446d-8ded-81955d782680 "Work and financial support during coronavirus"
- 65666cdf-b177-4d79-9687-b9c32805e450 "Support for businesses and self-employed people during coronavirus"
> Add example for 'tagged to two coronovirus taxons super breadcrumbs'

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
This is an alert type for medical safety alerts which MHRA would like to start using with 1cd19d5 to replace "Medical Device Alert".
[Trello Card](https://trello.com/c/gnHVgWtw/2131-add-national-patient-safety-alerts) &middot; [Zendesk Ticket](https://govuk.zendesk.com/agent/tickets/4210399)
> Add device-safety-information

- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/role.jsonnet
Part of the work to migrate rendering of the government/ministers page from
whitehall to collections.
https://trello.com/c/loAlkIp7/2063-8-migrate-government-ministers-to-collections
This change is needed as I have added a new field to the `details` in
`role_presenter`, this change adds that field to ensure tests on CI pass.
> Add whip organisation to role schema

- Gemfile
- Gemfile.lock
- Rakefile
- lib/schema_generator/definitions_resolver.rb
- lib/schema_generator/expanded_links.rb
- lib/schema_generator/format.rb
- lib/schema_generator/frontend_schema_generator.rb
- lib/schema_generator/notification_schema_generator.rb
- lib/schema_generator/publisher_content_schema_generator.rb
- lib/tasks/regenerate_schemas.rake
- lib/tasks/validate.rake
- spec/lib/schema_generator/schema_spec.rb
- spec/support/rake.rb
- spec/tasks/validate_uniqueness_of_frontend_example_base_paths_spec.rb
This PR contains the changes necessary for the app to run on Ruby 2.7.1.
The version of Ruby is left the same, since there is a script that can be run after all the apps have been updated to update the version all at once
- Tested locally with ruby 2.7.1 and 2.6.6
- Deprecation warning from jsonnet gem:
```
/ruby-2.7.1/gems/jsonnet-0.3.0/lib/jsonnet/vm.rb:35: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/ruby-2.7.1/gems/jsonnet-0.3.0/lib/jsonnet/vm.rb:87: warning: The called method `evaluate_file' is defined here
```
This is fixed in master but not the latest version
**Master:**
https://github.com/yugui/ruby-jsonnet/blob/master/lib/jsonnet/vm.rb#L35
https://github.com/yugui/ruby-jsonnet/blob/master/lib/jsonnet/vm.rb#L87 …
> Upgrade ruby 2.7

- examples/specialist_document/frontend/protected-food-drink-names.json
This is required by a test I'm adding to https://github.com/alphagov/government-frontend/blob/d529cf39099bdfbd36c32d7a8f1eba2e1d996aa4/test/presenters/specialist_document_presenter_test.rb
Trello card: https://trello.com/c/NKJYyZep/2157-3-update-protected-food-names-frontend-template
> Add protected-food-drink-names schema example

- dist/formats/take_part/frontend/schema.json
- dist/formats/take_part/notification/schema.json
- dist/formats/take_part/publisher_v2/schema.json
- formats/take_part.jsonnet
Depended on by: https://github.com/alphagov/whitehall/pull/5856
Take Part pages save an order in the model in Whitehall so that
they can be displayed in a specific order on the "Get Involved"
page. However this ordering was not being exported to Publishing
API, limiting our ability to migrate away from Whitehall.
Storing the ordering in Publishing API allows us to migrate the
frontend parts away from Whitehall, as this key information would
now be in a centralised place.
Trello: https://trello.com/c/aAW8oqCk/2174-5add-ordering-to-take-part-pages-in-schema
> Add 'ordering' to Take Part pages in schema

- dist/formats/email_alert_signup/frontend/schema.json
- dist/formats/email_alert_signup/notification/schema.json
- dist/formats/email_alert_signup/publisher_v2/schema.json
- formats/shared/definitions/email_alert.jsonnet
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
This is no longer used since [1]. We aim to delete this schema
entirely, by migrating its last remaining use (travel advice),
to use the generic content item signup functionality [2]. It's
therefore not worth pursuing the deletion of this specific field.
[1]: https://github.com/alphagov/email-alert-frontend/pull/918/files#diff-dcf8762f5933e092b429cc90d620101f6cad49658d9e65c1385ddb8c04bc0427L42
[2]: https://github.com/alphagov/email-alert-frontend/blob/0e1608e120ed32665c5aaabc224a226657783047/README.md#signup
> Mark email alert signup summary as deprecated

- dist/formats/step_by_step_nav/frontend/schema.json
- dist/formats/step_by_step_nav/notification/schema.json
- dist/formats/step_by_step_nav/publisher_v2/schema.json
- formats/step_by_step_nav.jsonnet
Site search can only ingest the title and description of a step by step at present. 
The body of a step by step is written in markdown-ish, which we can convert to html using kramdown or similar. By adding this html to the body field of the content item, we'll be able to search for them much more easily.
> Add body to step by steps

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/notification/schema.json
- dist/formats/case_study/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/notification/schema.json
- dist/formats/document_collection/publisher_v2/schema.json
- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/notification/schema.json
- dist/formats/html_publication/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- examples/case_study/frontend/case_study.json
- examples/detailed_guide/frontend/detailed_guide.json
- examples/document_collection/frontend/document_collection.json
- examples/publication/frontend/publication.json
- formats/case_study.jsonnet
- formats/detailed_guide.jsonnet
- formats/document_collection.jsonnet
- formats/html_publication.jsonnet
- formats/publication.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
Add a new field to the schema of:
- CaseStudy
- DetailedGuide
- DocumentCollection
- Publication
- HTML publication
- We are adding a button to Whitehall to allow publishers to display a new type of call out box on their transition related content. Here's the [PR](https://github.com/alphagov/whitehall/pull/5894) .
- Currently publishers can add a call out box for post transition content, this is called the `brexit_no_deal_notice` and is present on docs such as [this](https://www.gov.uk/api/content/guidance/driving-in-the-eu-from-1-january-2021). 
- A document will only ever have either a `brexit_no_deal_notice` or a `brexit_current_state_notice`. This is determined by a validation on the Whitehall database. 
---
https://trello.com/c/IwXzb5FM/589-design-whitehall-publisher-functionality-to- …
> Add brexit_current_state_notice

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
Adds further changes to the protected food names:
- Adds Canada to the country of origin options
- Removes Name protected by international treaty from the register field
Trello card: https://trello.com/c/F3HaBQBp/2258-2-further-changes-to-protected-food-drink-names-finder
> Further protected food changes

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
This is available as an option in specialist-publisher but it's missing from govuk-content-schemas: https://github.com/alphagov/specialist-publisher/blob/4000e6dec54bafd1b8af4516c3eed1abbb874a50/lib/documents/schemas/countryside_stewardship_grants.json#L43
This means that users can't create documents with that option. See https://govuk.zendesk.com/agent/tickets/4431297 for more details.
> Add air-quality as a land_use

- dist/formats/manual_section/frontend/schema.json
- dist/formats/manual_section/notification/schema.json
- dist/formats/manual_section/publisher_v2/schema.json
- examples/manual_section/frontend/what-is-content-design.json
- examples/manual_section/publisher_v2/manual_section.json
- formats/manual_section.jsonnet
A `visually_expanded` attribute has been added to manual_sections published by Manuals-Publisher.
[trello](https://trello.com/c/wgEKW9Ze/2398-5-allow-manuals-publisher-to-set-accordions-to-open)
> Add visually_expanded attribute to manual_sections

- dist/formats/smart_answer/frontend/schema.json
- dist/formats/smart_answer/notification/schema.json
- dist/formats/smart_answer/publisher_v2/links.json
- dist/formats/smart_answer/publisher_v2/schema.json
- formats/smart_answer.jsonnet
Previously, content items used to represent a Smart Answer were a transaction schema for the start page and a generic_with_external_related_links for the flow. This is because start pages were rendered by Frontend. However, we are changing Smart Answers to render the start pages and represent flows with a single content item. This adds schema to use for that content item.
> Add smart_answer schema

- Jenkinsfile
- docs/running-frontend-against-examples.md
- docs/why-contract-testing.md
The branch has been renamed from `master` to `main` for this repo, so we'll need to update the references to it.
> Update references to default branch

- dist/formats/case_study/frontend/schema.json
- dist/formats/case_study/notification/schema.json
- dist/formats/case_study/publisher_v2/schema.json
- dist/formats/detailed_guide/frontend/schema.json
- dist/formats/detailed_guide/notification/schema.json
- dist/formats/detailed_guide/publisher_v2/schema.json
- dist/formats/document_collection/frontend/schema.json
- dist/formats/document_collection/notification/schema.json
- dist/formats/document_collection/publisher_v2/schema.json
- dist/formats/html_publication/frontend/schema.json
- dist/formats/html_publication/notification/schema.json
- dist/formats/html_publication/publisher_v2/schema.json
- dist/formats/publication/frontend/schema.json
- dist/formats/publication/notification/schema.json
- dist/formats/publication/publisher_v2/schema.json
- examples/case_study/frontend/case_study.json
- examples/detailed_guide/frontend/detailed_guide.json
- examples/document_collection/frontend/document_collection.json
- examples/publication/frontend/publication.json
- formats/case_study.jsonnet
- formats/detailed_guide.jsonnet
- formats/document_collection.jsonnet
- formats/html_publication.jsonnet
- formats/publication.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
Reverts alphagov/govuk-content-schemas#1027
We are no longer adding the current state notice to any document types. The [Whitehall PR ](https://github.com/alphagov/whitehall/pull/5894) has been closed, so we should revert this PR.
> Revert "Add brexit_current_state_notice"

- dist/formats/taxon/frontend/schema.json
- dist/formats/taxon/notification/schema.json
- dist/formats/taxon/publisher_v2/schema.json
- formats/shared/definitions/taxonomy.jsonnet
- formats/taxon.jsonnet
We'd like to be able to customise the url of a taxon via an attribute stored in its content item. This will make it easier to curate the taxon's breadcrumbs as well as the taxon page's url. 
[Trello](https://trello.com/c/V2nmHHA6/1516-add-overrideurl-to-taxons)
[Related](https://github.com/alphagov/content-tagger/pull/1204)
> Add override url field to Taxon schema

- dist/formats/local_transaction/frontend/schema.json
- dist/formats/local_transaction/notification/schema.json
- dist/formats/local_transaction/publisher_v2/schema.json
- examples/local_transaction/frontend/local_transaction_with_devolved_administration_availability.json
- formats/local_transaction.jsonnet
This schema has been added as part of a task to enable publishers to specify devolved administration (DA) service availability for local transactions. 
In the Frontend application, by default, users will be shown a link to a local authority website when inputting a postcode for a local transaction.
In some cases, the service is handled by a devolved administration. In other cases the service is unavailable to devolved administrations.
Currently, the devolved administration availability cannot be set by publishers and the logic is defined in the Frontend application.
As part of the overall task, [functionality is being added to the Publisher application](https://github.com/alphagov/publisher/pull/1451) to allow this information to be set within the publishing tool.
Therefore, this schema …
> Add devolved_administration_availability to local_transaction schema

- dist/formats/get_involved/frontend/schema.json
- dist/formats/get_involved/notification/schema.json
- dist/formats/get_involved/publisher_v2/schema.json
- formats/get_involved.jsonnet
This PR allows us to patch-link Take Part pages to the Get Involved page
with intent of showing the needed data once the latter is moved to the
Government Frontend repo.
Trello: https://trello.com/c/7BjH9PyC/2083-8-migrate-government-get-involved-to-government-frontend
> Add TakePart pages to linkable contents

- dist/formats/travel_advice/frontend/schema.json
- dist/formats/travel_advice/notification/schema.json
- dist/formats/travel_advice/publisher_v2/links.json
- formats/travel_advice.jsonnet
We want updates to the Afghanistan travel advice page to generate emails to people who sign up for the [topical event](https://www.gov.uk/government/topical-events/afghanistan-uk-government-response)
We are therefore adding the topical_events links to the travel_advice schema, which will allow us to tag the page appropriately.
> Add topical_events links to travel advice pages

- dist/formats/redirect/frontend/schema.json
- dist/formats/redirect/notification/schema.json
- dist/formats/redirect/publisher_v2/schema.json
- formats/shared/definitions/routes_redirects.jsonnet
Trello: https://trello.com/c/OE0mGWzN/1630-create-pharmacy-collect-short-urls-for-13-september
This changes the schema validation for redirect destinations from
something quite restrictive to something much more permissive. The
reason for taking a permissive approach here is because of duplication
of validation efforts.
Currently Publishing API has an involved redirect destination validation
process, which is used for both unpublishing and individual redirects [1].
This schema has not kept up with this validation and is currently out of
sync. Rather than trying to continue a process of keeping a schema and a
Rails validator in sync, it seems simpler and more accurate to make the
schema permissive and rely on the Publishing API validator as the
validating entity.
The prompt for this change …
> Simplify the URI required for redirect destinations

- dist/formats/generic/frontend/schema.json
- dist/formats/generic/notification/schema.json
- dist/formats/generic/publisher_v2/schema.json
- dist/formats/generic_with_external_related_links/frontend/schema.json
- dist/formats/generic_with_external_related_links/notification/schema.json
- dist/formats/generic_with_external_related_links/publisher_v2/schema.json
- dist/formats/placeholder/frontend/schema.json
- dist/formats/placeholder/notification/schema.json
- dist/formats/placeholder/publisher_v2/schema.json
- dist/formats/special_route/frontend/schema.json
- dist/formats/special_route/notification/schema.json
- dist/formats/special_route/publisher_v2/schema.json
- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/specialist_document/frontend/oim-project.json
- formats/shared/definitions/_specialist_document.jsonnet
- formats/specialist_document.jsonnet
- lib/govuk_content_schemas/allowed_document_types.yml
Add OIM_project to specialist document schema.
- Related specialist publisher [PR](https://github.com/alphagov/specialist-publisher/pull/1910)
- Related search api [PR](https://github.com/alphagov/search-api/pull/2326)
- [Trello](https://trello.com/c/vN0SFEyb/2700-create-new-specialist-document-and-finder-office-for-the-internal-market-projects)
> Add OIM Projects to specialist document type content schema

- examples/specialist_document/frontend/product-safety-alert.json
This was a late request in
https://trello.com/c/ojsFViiX/2746-create-new-specialist-document-and-finder-product-safety-alerts-unsafe-products-and-recalls-3
Follows on from #1077.
> Rename 'Unsafe Product Report' to 'Product Safety Report'

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
The value needs to be 'not-provided' to match the input name given
in HTML:
https://github.com/alphagov/govuk-content-schemas/pull/1081/files#diff-347660f78070dce5f87642959d0b58ec9e51cfc53c84bd2b2eb3ff5f98143fd4R150
Tweaking the schema should fix https://govuk.zendesk.com/agent/tickets/4882031[](https://github.com/ChrisBAshton).
> Fix product safety alerts 'risk level' option

- dist/formats/topic/frontend/schema.json
- dist/formats/topic/notification/schema.json
- dist/formats/topic/publisher_v2/schema.json
- formats/topic.jsonnet
We want to reference the Content id of Mainstream browse page the topic originated from as a part of unified topic system work.
Until the work is completed we will need to keep the Mainstream browse page and
the cloned Topic is sync. Since other attributes of the Mainstream browse page
such as title or slug can change, this adds a unique reference we can use to
identify the cloned Topic.
The presence of this attribute can still acts as a flag.
It may also be useful to include reverse association in the Mainstream browse page schema to the cloned Topic's content_id.
> Replace mainstream_browse_type with mainstream_browse_origin in Topic schema

- examples/hmrc_manual/frontend/vat-government-public-bodies.json
- examples/hmrc_manual_section/frontend/vatgpb2000.json
- examples/manual/frontend/content-design.json
- examples/manual_section/frontend/what-is-content-design.json
This PR updates the manual related example schemas for frontend. This is needed as some schemas are missing data (links, timestamps etc), which should be present. I've also updated some of the data to make life easier in testing, which is taken advantage of in https://github.com/alphagov/government-frontend/pull/2424.
Trello:
https://trello.com/c/YmmLFXu5/1127-manuals-migrate-manuals-frontend-code-to-government-frontend
> Update manual examples

- dist/formats/topical_event/frontend/schema.json
- dist/formats/topical_event/notification/schema.json
- dist/formats/topical_event/publisher_v2/links.json
- dist/formats/topical_event/publisher_v2/schema.json
- formats/topical_event.jsonnet
This has previously used a generic default schema (named `placeholder`) for Topical Events.
We are now adding additional content to allow this to be served from a frontend application that is not Whitehall.
The first step is adding the format's own schema so we can customise it later.  Additionally, we will add the first customisation (including an array of featured documents).
[Trello card](https://trello.com/c/vYckhQzi)
> Add schema for Topical Events

- dist/formats/topical_event/frontend/schema.json
- dist/formats/topical_event/notification/schema.json
- dist/formats/topical_event/publisher_v2/schema.json
- formats/topical_event.jsonnet
We are in the process of migrating the rendering of Topical Events out of Whitehall.
As part of this, we need to include all the relevant information in the content item.
This will allow us to store social media links, in the same way we do for organisations.
[Trello card](https://trello.com/c/DOsCLwQL)
> Add social media links to topical event schema

- examples/manual_section/frontend/what-is-content-design.json
The example was missing the organisation links.
Trello:
https://trello.com/c/qCSHqqN7/1287-use-parent-manual-timestamps-for-manual-sections
> Update manual section example to be more realistic

- dist/formats/topical_event/frontend/schema.json
- dist/formats/topical_event/notification/schema.json
- dist/formats/topical_event/publisher_v2/schema.json
- formats/topical_event.jsonnet
Topical Events are being migrated away from Whitehall rendering.  Therefore we need to include the body field in the content item.
[Trello card](https://trello.com/c/BRkBpgxD)
> Add body field to Topical Events

- Jenkinsfile
CI is currently attempting to run a job against `manuals-frontend`, but this application was removed from CI in https://github.com/alphagov/govuk-puppet/pull/11587.
This removes that job from being run when `govuk-content-schemas` are being built.
> Remove `manuals-frontend` from Jenkinsfile

- dist/formats/topical_event/frontend/schema.json
- dist/formats/topical_event/notification/schema.json
- dist/formats/topical_event/publisher_v2/schema.json
- formats/topical_event.jsonnet
This is needed to allow us to include the topical event's logo or image in the content item.
The page is currently rendered by Whitehall, but will be migrated to Collections, which is why this now needs to be included in the content item.
[Trello card](https://trello.com/c/uNbOV24p)
> Add Topical Event image

- dist/formats/topical_event/frontend/schema.json
- dist/formats/topical_event/notification/schema.json
- dist/formats/topical_event/publisher_v2/schema.json
- formats/topical_event.jsonnet
This is needed to allow us to include emphasised organisations in the
content item for a topical event.
The page is currently rendered by whitehall, but will be rendered by
collections, which is why this now needs to be included.
Trello: https://trello.com/c/iIfXqVKi/71-add-rendering-of-topical-event-organisation-names-and-logos-to-collections
> Add emphasised organisations to topical event

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- formats/shared/definitions/_specialist_document.jsonnet
[Trello ticket link](https://trello.com/c/RqdVvCSV/548-add-a-new-option-to-case-type-filter-on-cma-cases-specialist-finder)
This PR adds the "information-and-advice-to-government" option to the filter options for case_type in cma_cases.
> Add new filter option for case_type filter in cma_cases

- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/notification/schema.json
- dist/formats/hmrc_manual_section/publisher_v2/schema.json
- examples/hmrc_manual_section/frontend/vatgpb2000.json
- examples/hmrc_manual_section/publisher_v2/hmrc_manual_section.json
- formats/hmrc_manual_section.jsonnet
- formats/shared/definitions/hmrc_manual.jsonnet
Add manual title to HMRC manuals section schema, needed to render HMRC manuals more efficiently now they've been moved to government-frontend.
Note that this field will be required when tasks have been run to add titles to all existing and new documents.
https://trello.com/c/NToovfjr/1349-add-parent-manuals-title-to-the-hmrc-section-content-item
> Add title to manuals block of HMRC manuals section schema

- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/notification/schema.json
- dist/formats/hmrc_manual_section/publisher_v2/schema.json
- formats/shared/definitions/hmrc_manual.jsonnet
Trello:
https://trello.com/c/ItYKGMqF/1464-revert-add-parent-manuals-title-to-the-hmrc-section-content-item
> Remove requirement for title

- dist/formats/hmrc_manual_section/frontend/schema.json
- dist/formats/hmrc_manual_section/notification/schema.json
- dist/formats/hmrc_manual_section/publisher_v2/schema.json
- examples/hmrc_manual_section/frontend/vatgpb2000.json
- examples/hmrc_manual_section/publisher_v2/hmrc_manual_section.json
- formats/hmrc_manual_section.jsonnet
- formats/shared/definitions/hmrc_manual.jsonnet
We can merge this after all PRs listed in the [Trello card](https://trello.com/c/ItYKGMqF/1403-revert-add-parent-manuals-title-to-the-hmrc-section-content-item) have been deployed and https://github.com/alphagov/publishing-api/pull/2121 has been run in production.
> Revert "Add title to manuals block of HMRC manuals section schema"

- dist/formats/organisation/frontend/schema.json
- dist/formats/organisation/notification/schema.json
- dist/formats/organisation/publisher_v2/schema.json
- dist/formats/world_location_news/frontend/schema.json
- dist/formats/world_location_news/notification/schema.json
- dist/formats/world_location_news/publisher_v2/links.json
- dist/formats/world_location_news/publisher_v2/schema.json
- formats/organisation.jsonnet
- formats/shared/definitions/_whitehall.jsonnet
- formats/world_location_news.jsonnet
This was previously using a placeholder schema, but this PR introduces a schema for world location news.
There are several elements that are shared with organisations, which have been moved to the shared whitehall definitions so that both schemas can use the same definitions.
I have made the elements of the details hash mandatory. This doesn't seem to be a standard approach across our schemas, but making them mandatory does seem to be more helpful in a schema, guaranteeing the presence of these fields. This makes sense for the featured links and featured documents as they are always present (although can be empty, which is allowable by the schema). Mission statement can in theory be nil (they are nullable in the database and there are two world locations for which this is the case, but …
> Add format for world location news

- dist/formats/world_location_news/frontend/schema.json
- dist/formats/world_location_news/notification/schema.json
- dist/formats/world_location_news/publisher_v2/schema.json
- formats/world_location_news.jsonnet
This is required so we can add a label to the World Location News page telling users whether the news relates to a World Location or International Delegation.
[Trello card](https://trello.com/c/zxDhAkI3)
> Add location type to World Location news page

- Gemfile
- Gemfile.lock
This is needed so that the app gets deployed correctly to Heroku.
https://trello.com/c/aSPjC2s0/2955-remove-dependencies-from-eol-heroku-stacks-3
> Read ruby version from .ruby-version

- dist/formats/role/frontend/schema.json
- dist/formats/role/notification/schema.json
- dist/formats/role/publisher_v2/schema.json
- formats/role.jsonnet
The Role content type defines a role_payment_type field. It was previously defined as an enum both in this repo, and also in the [downstream app Whitehall][1] which publishes Roles.
We've had a request to add new values to the select list of Role Payment Types in Whitehall. However this would require updating the enum lists in both repositories (i.e. govuk-content-schemas and Whitehall) with the new values – which leads to duplicated effort.
After some digging, we learned that the role_payment_type field is only [used by the frontend][2] to output directly [on the page][3]. It's not used for filtering, sorting, or any other functionality that would reasonably warrant the need for the field to be an enum. In other words: the allowed values in this field don't need to be tightly controlled …
> Remove the enum on role_payment_type

- dist/formats/specialist_document/frontend/schema.json
- dist/formats/specialist_document/notification/schema.json
- dist/formats/specialist_document/publisher_v2/schema.json
- examples/finder/frontend/maib-reports.json
- examples/specialist_document/frontend/maib-reports.json
- formats/shared/definitions/_specialist_document.jsonnet
Changing label only (partially reverting previous PR)
[Trello card](https://trello.com/c/6OoRo5vK/708-change-report-type-for-marine-accident-investigation-branch-reports)
> Change report type for Marine Accident Investigation Branch reports

- Gemfile
- Gemfile.lock
This was removed from the standard lib in ruby 3. It's required for the preview app.
> Add puma as a dependency

- examples/specialist_document/frontend/utaac-decision.json
We've had a request to add some judges to the judges filter for `utaac_decsision.json` 
https://trello.com/c/SqwF3iHI/826-5106299-add-2-judges-to-filter-on-administrative-appeals-tribunal-decisions-content-change-request-hm-courts-tribunals-service-h
> Add judges to 'utaac-decision.json'

- Jenkinsfile
Trello: https://trello.com/c/amnaU0V9/853-decommission-the-publishing-end-to-end-tests
As per: https://github.com/alphagov/govuk-jenkinslib/commit/99e8541c7a44c7cfebff0da171b3643573ad869b
> Replace deprecated deployIntegration function

- dist/formats/world_location_news/frontend/schema.json
- dist/formats/world_location_news/notification/schema.json
- dist/formats/world_location_news/publisher_v2/links.json
- formats/world_location_news.jsonnet
International Delegations have a number of additional links required to present their content outside of Whitehall.
Presentation of these links was added in https://github.com/alphagov/whitehall/pull/7023.
We do not need to add `organisations` as this is already present in the base links we inherit.
[Trello card](https://trello.com/c/4FWd2mRD/363-add-international-delegation-page-content-to-their-content-item)
> Add additional links for International Delegations
